// rating-engine.js — TWQS / QAQS / Combined computation for Worker Output Search Ratings tab.
// Engine v6.2: recalibrated TW/QA/combined percentile μ/σ from rebuilt dive.db.

const RE_VERSION = '6.2';
const RE_MS_PER_DAY = 86400000;
const RE_HALFLIFE_DAYS = 90;
const RE_DIAG_SAMPLE_ROWS = 5;
const RE_DISCARDED_STALE_DAYS = 7;

// Terminal task status → quality score (mirrors rank-workers.py STATUS_QUALITY).
// Statuses not listed here are in-flight — excluded from outcome quality denominator.
const RE_STATUS_QUALITY = {
    production: 1.0,
    bugged: 0.5,
    'escalated-fleet-review': 0.5,
    discarded: 0.15,
    dismissed: 0.0,
};
const RE_CLOSURE_QUALITY = {
    production: 1.0,
    discarded: 0.5,
    dismissed: 0.0,
};

// WPS (TWQS) per-axis shrinkage constants calibrated from dive.db baseline (rank-workers v1.2).
const RE_TWQS_C = {
    outcomeQuality:       10,
    positiveFeedbackRate: 10,
    nonBottomScoreRate:    5,
    firstPassAcceptance:   5,
    disputeLossAvoidance:  5,
};
const RE_TWQS_PRIOR = {
    outcomeQuality:       0.7906,
    positiveFeedbackRate: 0.4800,
    nonBottomScoreRate:   0.9635,
    firstPassAcceptance:  0.4606,
    disputeLossAvoidance: 1.0,
};

// QPS (QAQS) per-axis shrinkage constants calibrated from dive.db baseline (rank-qa v2.0).
const RE_QAQS_RET_EFF_C         = 10;
const RE_QAQS_RET_EFF_PRIOR     = 0.4893;
const RE_QAQS_RET_ACT_C         = 10;
const RE_QAQS_RET_ACT_PRIOR     = 0.6891;
const RE_QAQS_DISPUTE_DEF_C     = 5;
const RE_QAQS_DISPUTE_DEF_PRIOR = 1.0;
const RE_QAQS_LABEL_DISC_C      = 5;
const RE_QAQS_LABEL_DISC_PRIOR  = 0.1205;

const RE_TWQS_AXES = [
    { id: 'outcomeQuality',       label: 'Outcome Quality',        weight: 0.40 },
    { id: 'positiveFeedbackRate', label: 'Positive Feedback Rate', weight: 0.20 },
    { id: 'nonBottomScoreRate',   label: 'Non-Bottom Score Rate',  weight: 0.15 },
    { id: 'firstPassAcceptance',  label: 'First-Pass Acceptance',  weight: 0.15 },
    { id: 'disputeLossAvoidance', label: 'Dispute Loss Avoidance', weight: 0.10 },
];

const RE_QAQS_AXES = [
    { id: 'returnEffectiveness', label: 'Return Effectiveness', weight: 0.40 },
    { id: 'returnActionability', label: 'Return Actionability', weight: 0.25 },
    { id: 'disputeDefense',      label: 'Dispute Loss Avoidance', weight: 0.20 },
    { id: 'labelDiscrimination', label: 'Label Discrimination', weight: 0.15 },
];

const RE_BANDS = [
    { min: 80, label: 'Excellent' },
    { min: 70, label: 'Good' },
    { min: 58, label: 'Average' },
    { min: 48, label: 'Needs attention' },
    { min: 0,  label: 'Concerning' }
];

// Parametric percentile distributions (μ, σ) fitted from current dive.db scores.
// Estimated percentile = 100 × Φ((score − μ) / σ).  No individual scores stored.
// Regenerated by local/db/utils/compute-percentile-calibration.py
// Snapshot: 1316 WPS / 285 QPS / 1303 combined; flat + recency90d (2026-07-14).
const RE_PERCENTILE_PARAMS = {
    twqs: {
        flat:    { mu: 71.2721, sigma: 7.0185 },
        recency: { mu: 71.8981, sigma: 6.0681 },
    },
    qaqs: {
        flat:    { mu: 57.5310, sigma: 6.4085 },
        recency: { mu: 57.2588, sigma: 6.1915 },
    },
    combined: {
        flat:    { mu: 69.0315, sigma: 7.6468 },
        recency: { mu: 69.6143, sigma: 7.1324 },
    },
};

// ---------------------------------------------------------------------------
// Utility helpers
// ---------------------------------------------------------------------------

function reLib() {
    return Context.dashboardLib || null;
}

function reFeedbackTimestamp(entry) {
    return String((entry && (entry.feedbackAt || entry.created_at)) || '').trim();
}

function reTaskTimestamp(task, item) {
    return String((task && (task.createdAt || task.created_at)) || (item && item.sortAt) || '').trim();
}

function reIdsEqual(a, b) {
    return String(a || '').trim() === String(b || '').trim();
}

function reResolveFeedbackId(id, remap) {
    const key = String(id || '').trim();
    if (!key) return '';
    return String((remap && remap[key]) || key);
}

function reFeedbackAtForResolvedId(task, feedbackId) {
    const fid = String(feedbackId || '').trim();
    if (!fid || !task) return '';
    for (const entry of task.allFeedback || []) {
        if (!reIsHumanFeedback(entry)) continue;
        if (reIdsEqual(entry.id, fid)) return reFeedbackTimestamp(entry);
    }
    return '';
}

function reIsHumanFeedback(entry) {
    if (!entry) return false;
    if (entry.isVerifierFailure || entry.isSystemFeedback) return false;
    if (entry.display && (entry.display.isVerifierFailure || entry.display.isSystemFeedback)) return false;
    return true;
}

// Returns quality score for terminal tasks; null for in-flight (mirrors rank-workers.py task_terminal_quality).
function reTaskTerminalQuality(task, nowMs) {
    const status = String((task && task.status) || '').toLowerCase().trim();
    if (!status) return null;
    if (status === 'discarded') {
        const createdAt = String((task && (task.createdAt || task.created_at)) || '').trim();
        const ts = Date.parse(createdAt);
        if (Number.isNaN(ts)) return null;
        const ageDays = Math.max(0, (nowMs - ts) / RE_MS_PER_DAY);
        if (ageDays < RE_DISCARDED_STALE_DAYS) return null;
        return RE_STATUS_QUALITY.discarded;
    }
    const quality = RE_STATUS_QUALITY[status];
    return quality !== undefined ? quality : null;
}

// Closure quality intentionally does not apply the discarded stale-age gate.
// It measures the eventual path for tasks that were not bugged/flagged.
function reTaskClosureQuality(task) {
    const status = String((task && task.status) || '').toLowerCase().trim();
    const quality = RE_CLOSURE_QUALITY[status];
    return quality !== undefined ? quality : null;
}

// Standard normal CDF approximation (Abramowitz–Stegun rational, max error ≈7.5×10⁻⁸).
function reNormalCdf(z) {
    const t = 1 / (1 + 0.2316419 * Math.abs(z));
    const poly = t * (0.319381530 + t * (-0.356563782 + t * (1.781477937 + t * (-1.821255978 + t * 1.330274429))));
    const pdf = Math.exp(-0.5 * z * z) / Math.sqrt(2 * Math.PI);
    const cdf = 1 - pdf * poly;
    return z >= 0 ? cdf : 1 - cdf;
}

// Estimated percentile via Φ((score − μ) / σ). Returns integer 0–100, or null.
function reEstimatePercentile(score, params) {
    if (score == null || !Number.isFinite(score)) return null;
    if (!params || !Number.isFinite(params.mu) || !Number.isFinite(params.sigma) || params.sigma <= 0) return null;
    const z = (score - params.mu) / params.sigma;
    const pct = reNormalCdf(z) * 100;
    return Math.max(0, Math.min(100, Math.round(pct)));
}

function reOrdinalSuffix(n) {
    const v = Math.abs(Math.trunc(Number(n)));
    if (!Number.isFinite(v)) return 'th';
    const mod100 = v % 100;
    if (mod100 >= 11 && mod100 <= 13) return 'th';
    const mod10 = v % 10;
    if (mod10 === 1) return 'st';
    if (mod10 === 2) return 'nd';
    if (mod10 === 3) return 'rd';
    return 'th';
}

/** Formats an integer percentile as e.g. "72nd". Returns '' if invalid. */
function reFormatPercentile(n) {
    if (n == null || !Number.isFinite(Number(n))) return '';
    const v = Math.round(Number(n));
    return String(v) + reOrdinalSuffix(v);
}

// Empirical-Bayes shrinkage toward cohort prior.
function reShrunkRate(k, n, C, prior) {
    return (k + C * prior) / (n + C);
}

function reBandLabel(score) {
    const n = Number(score);
    if (!Number.isFinite(n)) return '—';
    for (const band of RE_BANDS) {
        if (n >= band.min) return band.label;
    }
    return RE_BANDS[RE_BANDS.length - 1].label;
}

// TWQS confidence: based on terminal task count (mirrors rank-workers.py _confidence).
function reTwqsConfidenceBadge(terminalCount) {
    const n = Number(terminalCount) || 0;
    if (n < 10) return { tier: 'provisional', label: 'Provisional' };
    if (n < 50) return { tier: 'standard', label: 'Standard' };
    return { tier: 'high', label: 'High confidence' };
}

// QAQS confidence: based on feedback row count (mirrors rank-qa.py _confidence).
function reQaqsConfidenceBadge(feedbackRowCount) {
    const n = Number(feedbackRowCount) || 0;
    if (n < 25) return { tier: 'provisional', label: 'Provisional' };
    if (n < 100) return { tier: 'standard', label: 'Standard' };
    return { tier: 'high', label: 'High confidence' };
}

// Returns 0 when outside date window or timestamp unparseable.
// 'flat'    → 1.0 inside window (or always if no window)
// 'recency' → exp(−ln(2)·age/H) inside window (or always if no window)
function reEventWeight(isoTs, weighting, nowMs, window) {
    const ts = Date.parse(isoTs);
    if (Number.isNaN(ts)) return 0;
    if (window) {
        if (window.afterIso && isoTs < window.afterIso) return 0;
        if (window.beforeIso && isoTs > window.beforeIso) return 0;
    }
    if (weighting === 'flat') return 1;
    const ageDays = Math.max(0, (nowMs - ts) / RE_MS_PER_DAY);
    return Math.exp(-Math.LN2 * ageDays / RE_HALFLIFE_DAYS);
}

function reResolveWindow(committed) {
    const lib = reLib();
    const afterLocal = String((committed && committed.afterLocal) || '').trim();
    const beforeLocal = String((committed && committed.beforeLocal) || '').trim();
    let afterIso = '';
    let beforeIso = '';
    if (lib && typeof lib.validateCreatedAtRange === 'function') {
        const check = lib.validateCreatedAtRange(afterLocal, beforeLocal);
        if (check && check.valid) {
            afterIso = check.afterIso || '';
            beforeIso = check.beforeIso || '';
        }
    }
    return { afterLocal, beforeLocal, afterIso, beforeIso };
}

function reWeightedMean(pairs) {
    let wSum = 0;
    let total = 0;
    for (const { value, weight } of pairs) {
        if (!weight || weight <= 0) continue;
        wSum += weight;
        total += value * weight;
    }
    if (wSum <= 0) return null;
    return total / wSum;
}

function reCombineAxes(axisDefs) {
    const defined = axisDefs.filter((p) => p.defined !== false && p.score != null && Number.isFinite(p.score));
    if (defined.length === 0) {
        return { score: null, band: '—', axes: axisDefs };
    }
    const baseSum = defined.reduce((s, p) => s + p.baseWeight, 0);
    let composite = 0;
    for (const p of axisDefs) {
        if (p.defined === false || p.score == null || !Number.isFinite(p.score)) {
            p.effectiveWeight = 0;
            continue;
        }
        p.effectiveWeight = p.baseWeight / baseSum;
        composite += p.score * p.effectiveWeight;
    }
    const score = Math.round(composite * 1000) / 10;
    return { score, band: reBandLabel(score), axes: axisDefs };
}

function reCohortPriors(kind, cohort) {
    const global = kind === 'twqs' ? RE_TWQS_PRIOR : {
        returnEffectiveness: RE_QAQS_RET_EFF_PRIOR,
        returnActionability: RE_QAQS_RET_ACT_PRIOR,
        disputeDefense: RE_QAQS_DISPUTE_DEF_PRIOR,
        labelDiscrimination: RE_QAQS_LABEL_DISC_PRIOR,
    };
    const supplied = cohort && cohort.priors && cohort.priors[kind];
    return { ...global, ...(supplied || {}) };
}

function reCohortKey(task, dimension) {
    if (!task) return '';
    if (dimension === 'team') return String(task.team || task.teamId || '').trim();
    if (dimension === 'env') return String(task.envKey || task.environment || '').trim();
    if (dimension === 'month') {
        const ts = String(task.createdAt || task.created_at || '').trim();
        return /^\d{4}-\d{2}/.test(ts) ? ts.slice(0, 7) : '';
    }
    return '';
}

function reBlendCohortBlocks(mainBlock, slices, confidenceFn) {
    if (!mainBlock || mainBlock.score == null) return null;
    let mainWeight = 0.5;
    const channels = {};
    for (const dimension of ['team', 'env', 'month']) {
        const rows = slices[dimension] || [];
        const usable = rows.filter((row) => row.block && row.block.score != null && row.volume > 0);
        const initialWeight = 1 / 6;
        if (!usable.length) {
            mainWeight += initialWeight;
            channels[dimension] = { score: null, volume: 0, weight: 0, provisional: false, keys: [] };
            continue;
        }
        const totalVolume = usable.reduce((sum, row) => sum + row.volume, 0);
        const score = usable.reduce((sum, row) => sum + row.block.score * row.volume, 0) / totalVolume;
        const provisional = confidenceFn(totalVolume).tier === 'provisional';
        const weight = provisional ? initialWeight / 2 : initialWeight;
        mainWeight += initialWeight - weight;
        channels[dimension] = {
            score,
            volume: totalVolume,
            weight,
            provisional,
            keys: usable.map((row) => row.key),
        };
    }
    const score = mainWeight * mainBlock.score
        + Object.values(channels).reduce((sum, channel) => sum + (channel.score == null ? 0 : channel.weight * channel.score), 0);
    return {
        score: Math.round(score * 10) / 10,
        band: reBandLabel(score),
        estimatedPercentile: mainBlock.estimatedPercentile,
        confidence: mainBlock.confidence,
        main: { score: mainBlock.score, weight: mainWeight },
        channels,
    };
}

function reHumanFeedbackChronological(task) {
    return (task.allFeedback || [])
        .filter(reIsHumanFeedback)
        .sort((a, b) => reFeedbackTimestamp(a).localeCompare(reFeedbackTimestamp(b)));
}

function reIsoWeekKey(iso) {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return null;
    const utc = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
    const dayNum = utc.getUTCDay() || 7;
    utc.setUTCDate(utc.getUTCDate() + 4 - dayNum);
    const yearStart = new Date(Date.UTC(utc.getUTCFullYear(), 0, 1));
    const weekNo = Math.ceil((((utc - yearStart) / RE_MS_PER_DAY) + 1) / 7);
    return utc.getUTCFullYear() + '-W' + String(weekNo).padStart(2, '0');
}

function reMedian(values) {
    const nums = values.filter((v) => Number.isFinite(v)).sort((a, b) => a - b);
    if (!nums.length) return null;
    const mid = Math.floor(nums.length / 2);
    return nums.length % 2 ? nums[mid] : (nums[mid - 1] + nums[mid]) / 2;
}

function reSlugify(text) {
    return String(text || 'worker')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 48) || 'worker';
}

function reFormatPct(score) {
    const lib = reLib();
    if (lib && typeof lib.formatPercent === 'function') return lib.formatPercent(score * 100);
    return (Math.round(score * 1000) / 10).toFixed(1);
}

function rePctOneDecimal(fraction) {
    if (fraction == null || !Number.isFinite(fraction)) return null;
    return Math.round(fraction * 1000) / 10;
}

function reAxisExportRow(axis) {
    const defined = axis && axis.defined !== false && axis.score != null && Number.isFinite(axis.score);
    return {
        id: String((axis && axis.id) || ''),
        label: String((axis && axis.label) || ''),
        baseWeightPct: rePctOneDecimal(axis && axis.baseWeight),
        effectiveWeightPct: defined ? rePctOneDecimal(axis.effectiveWeight) : 0,
        subScorePct: defined ? rePctOneDecimal(axis.score) : null,
        defined
    };
}

function reSortedAxesForExport(axes) {
    return [...(axes || [])].sort((a, b) => {
        const wDiff = (b.baseWeight || 0) - (a.baseWeight || 0);
        if (wDiff !== 0) return wDiff;
        return String(a.label || '').localeCompare(String(b.label || ''));
    });
}

function reScoreBlockExport(block) {
    if (!block) return null;
    return {
        score: block.score,
        band: block.band,
        estimatedPercentile: block.estimatedPercentile != null ? block.estimatedPercentile : null,
        confidence: block.confidence || null,
        axes: reSortedAxesForExport(block.axes).map(reAxisExportRow)
    };
}

function reWorkerJsonExport(workerReport) {
    const src = workerReport || {};
    const flatTwqs = src.twqs && src.twqs.flat;
    const recencyTwqs = src.twqs && src.twqs.recency;
    const flatQaqs = src.qaqs && src.qaqs.flat;
    const recencyQaqs = src.qaqs && src.qaqs.recency;
    const flatComb = src.combined && src.combined.flat;
    const recencyComb = src.combined && src.combined.recency;

    const exportCombinedBlock = (c) => {
        if (!c) return null;
        return {
            score: c.score,
            band: c.band,
            estimatedPercentile: c.estimatedPercentile != null ? c.estimatedPercentile : null,
            writerRatio: c.writerRatio,
            qaRatio: c.qaRatio,
            nTerminal: c.nTerminal,
            nFeedback: c.nFeedback
        };
    };

    return {
        workerId: src.workerId,
        name: src.name,
        email: src.email || '',
        window: src.window || {},
        computedAt: src.computedAt || null,
        engineVersion: src.engineVersion || RE_VERSION,
        exportDate: src.exportDate || null,
        weighting: {
            flat: {
                twqs: reScoreBlockExport(flatTwqs),
                qaqs: reScoreBlockExport(flatQaqs),
                combined: exportCombinedBlock(flatComb)
            },
            recency: {
                twqs: reScoreBlockExport(recencyTwqs),
                qaqs: reScoreBlockExport(recencyQaqs),
                combined: exportCombinedBlock(recencyComb)
            }
        }
    };
}

function reAxisOmitReason(axis) {
    if (!axis || axis.defined !== false) return null;
    switch (axis.id) {
        case 'disputeDefense':
        case 'disputeLossAvoidance':
            return 'Always defined; only dispute losses reduce this score';
        case 'returnActionability':
            return 'No negative feedback on production tasks in scope';
        default:
            return 'Axis undefined';
    }
}

function reFieldAuditRow(entry, task, workerId) {
    const ts = reFeedbackTimestamp(entry);
    const allFb = reHumanFeedbackChronological(task);
    const chronoIdx = allFb.findIndex((e) => String(e.id) === String(entry.id));
    return {
        feedbackId: String(entry.id || ''),
        taskId: String((task && task.id) || ''),
        feedbackAt: ts || null,
        created_at_legacy: String((entry && entry.created_at) || '') || null,
        reviewerId: String((entry.reviewer && entry.reviewer.id) || ''),
        returnType: (() => {
            if (entry.isPositive) return 'accepted';
            if (entry.isEscalated) return 'escalated';
            if (entry.isFlaggedAsBugged) return 'bugged';
            return 'returned';
        })(),
        chronologicalIndex: chronoIdx,
        totalHumanFeedbackOnTask: allFb.length,
        isFirstQaOnTask: chronoIdx === 0,
        timestampResolvable: Boolean(ts)
    };
}

// Collects all QA feedback rows for a reviewer across hydrated items, deduped by feedback ID.
// Excludes system/verifier entries and self-reviews (where reviewer === task author).
function reCollectQaqsFeedbackRows(workerId, hydratedItems) {
    const feedbackById = new Map();
    for (const item of hydratedItems) {
        const task = item.task;
        if (!task) continue;
        const authorId = task.author && task.author.id;
        for (const entry of task.allFeedback || []) {
            if (!reIsHumanFeedback(entry)) continue;
            const reviewerId = entry.reviewer && entry.reviewer.id;
            if (!reIdsEqual(reviewerId, workerId)) continue;
            if (authorId && reIdsEqual(reviewerId, authorId)) continue;
            feedbackById.set(String(entry.id), { entry, task, item });
        }
    }
    return [...feedbackById.values()];
}

// ---------------------------------------------------------------------------
// Combined score block (volume-weighted WPS + QPS blend, mirrors rank-combined.py)
// ---------------------------------------------------------------------------

function reCombinedScoreBlock(twqsBlock, qaqsBlock, nTerminal, nFeedback, weighting) {
    const twqsScore = twqsBlock && twqsBlock.score != null ? twqsBlock.score : null;
    const qaqsScore = qaqsBlock && qaqsBlock.score != null ? qaqsBlock.score : null;
    const nTotal = nTerminal + nFeedback;

    let score = null;
    let writerRatio = null;
    let qaRatio = null;

    if (twqsScore != null && qaqsScore != null && nTotal > 0) {
        score = (twqsScore * nTerminal + qaqsScore * nFeedback) / nTotal;
        writerRatio = nTerminal / nTotal;
        qaRatio = nFeedback / nTotal;
    } else if (twqsScore != null) {
        score = twqsScore;
    } else if (qaqsScore != null) {
        score = qaqsScore;
    }

    if (score == null) return null;

    const roundedScore = Math.round(score * 10) / 10;
    const params = RE_PERCENTILE_PARAMS.combined[weighting];
    const estimatedPercentile = reEstimatePercentile(roundedScore, params);

    return {
        score: roundedScore,
        band: reBandLabel(roundedScore),
        estimatedPercentile,
        writerRatio,
        qaRatio,
        nTerminal,
        nFeedback
    };
}

// ---------------------------------------------------------------------------
// RatingEngine
// ---------------------------------------------------------------------------

const RatingEngine = {
    VERSION: RE_VERSION,
    ordinalSuffix: reOrdinalSuffix,
    formatPercentile: reFormatPercentile,
    setCohortBaselines(baselines) {
        Context.ratingCohortBaselines = baselines || {};
    },

    compute(options) {
        const opts = options || {};
        const cachedItems = opts.cachedItems || [];
        const committed = opts.committed || {};
        const nowMs = Number.isFinite(opts.nowMs) ? opts.nowMs : Date.now();
        const authorIds = [...new Set((committed.authorIds || []).filter(Boolean))];
        const hydratedItems = cachedItems.filter((item) => item && item.hydrated === true);
        const unhydratedCount = cachedItems.length - hydratedItems.length;
        const window = reResolveWindow(committed);
        const profiles = opts.workerProfiles || {};
        const cohortBaselines = opts.cohortBaselines || Context.ratingCohortBaselines || {};

        const workers = authorIds.map((workerId) => {
            const profile = profiles[workerId] || {};

            const flatTwqs = this._computeTwqs(workerId, hydratedItems, 'flat', window, nowMs);
            const recencyTwqs = this._computeTwqs(workerId, hydratedItems, 'recency', window, nowMs);
            const flatQaqs = this._computeQaqs(workerId, hydratedItems, 'flat', window, nowMs);
            const recencyQaqs = this._computeQaqs(workerId, hydratedItems, 'recency', window, nowMs);

            // Volume counts are unweighted in-scope counts, shared by both variants.
            const nTerminal = (flatTwqs && flatTwqs.display && flatTwqs.display.terminalTaskCount) || 0;
            const nFeedback = (flatQaqs && flatQaqs.display && flatQaqs.display.inScopeFeedbackCount) || 0;

            const flatCombined = reCombinedScoreBlock(flatTwqs, flatQaqs, nTerminal, nFeedback, 'flat');
            const recencyCombined = reCombinedScoreBlock(recencyTwqs, recencyQaqs, nTerminal, nFeedback, 'recency');
            const cohort = this._computeCohortBlend(
                workerId, hydratedItems, window, nowMs, cohortBaselines,
                { flatTwqs, recencyTwqs, flatQaqs, recencyQaqs }
            );

            return {
                workerId,
                name: profile.name || profile.label || workerId,
                email: profile.email || '',
                window,
                twqs: { flat: flatTwqs, recency: recencyTwqs },
                qaqs: { flat: flatQaqs, recency: recencyQaqs },
                combined: (flatCombined || recencyCombined)
                    ? { flat: flatCombined, recency: recencyCombined }
                    : null,
                cohort,
                meta: { hydratedCount: hydratedItems.length, unhydratedCount }
            };
        });

        return {
            version: RE_VERSION,
            computedAt: new Date(nowMs).toISOString(),
            window,
            workers,
            meta: {
                hydratedCount: hydratedItems.length,
                unhydratedCount,
                totalCount: cachedItems.length,
                workerCount: workers.length
            }
        };
    },

    _computeCohortBlend(workerId, hydratedItems, window, nowMs, baselines, main) {
        const output = { flat: {}, recency: {} };
        for (const weighting of ['flat', 'recency']) {
            const twSlices = { team: [], env: [], month: [] };
            const qaSlices = { team: [], env: [], month: [] };
            for (const dimension of ['team', 'env', 'month']) {
                const keyedItems = new Map();
                for (const item of hydratedItems) {
                    const key = reCohortKey(item.task, dimension);
                    if (!key) continue;
                    if (!keyedItems.has(key)) keyedItems.set(key, []);
                    keyedItems.get(key).push(item);
                }
                for (const [key, sliceItems] of keyedItems) {
                    const baseline = baselines && baselines[dimension] && baselines[dimension][key];
                    const twBlock = this._computeTwqs(workerId, sliceItems, weighting, window, nowMs, baseline);
                    const qaBlock = this._computeQaqs(workerId, sliceItems, weighting, window, nowMs, baseline);
                    if (twBlock) twSlices[dimension].push({
                        key,
                        block: twBlock,
                        volume: (twBlock.display && twBlock.display.terminalTaskCount) || 0,
                    });
                    if (qaBlock) qaSlices[dimension].push({
                        key,
                        block: qaBlock,
                        volume: (qaBlock.display && qaBlock.display.inScopeFeedbackCount) || 0,
                    });
                }
            }
            const twqs = reBlendCohortBlocks(main[weighting + 'Twqs'], twSlices, reTwqsConfidenceBadge);
            const qaqs = reBlendCohortBlocks(main[weighting + 'Qaqs'], qaSlices, reQaqsConfidenceBadge);
            const nTerminal = (main[weighting + 'Twqs'] && main[weighting + 'Twqs'].display.terminalTaskCount) || 0;
            const nFeedback = (main[weighting + 'Qaqs'] && main[weighting + 'Qaqs'].display.inScopeFeedbackCount) || 0;
            const combined = reCombinedScoreBlock(twqs, qaqs, nTerminal, nFeedback, weighting);
            output[weighting] = { twqs, qaqs, combined };
        }
        return output;
    },

    _writerItems(workerId, hydratedItems) {
        return hydratedItems.filter((item) => {
            const authorId = item.task && item.task.author && item.task.author.id;
            return reIdsEqual(authorId, workerId);
        });
    },

    // Computes WPS-aligned TWQS (five-axis, rank-workers.py v1.2 formula).
    _computeTwqs(workerId, hydratedItems, weighting, window, nowMs, cohort) {
        const writerItems = this._writerItems(workerId, hydratedItems);
        if (writerItems.length === 0) return null;

        // Outcome Quality: terminal tasks, recency-weighted quality sum
        // A = status-weighted (includes bugged); B = excludes bugged statuses entirely
        let oqKsumA = 0, oqNsumA = 0, oqTerminalCount = 0;
        let oqKsumB = 0, oqNsumB = 0;
        // Positive Feedback Rate: all human feedback, recency-weighted
        let pfKsum = 0, pfNsum = 0;
        // Non-Bottom Score Rate: explicitly scored feedback only (qualityRatingRaw), recency-weighted
        let nbKsum = 0, nbNsum = 0;
        // First-Pass Acceptance: one per task (earliest in-scope feedback), recency-weighted
        let fpKsum = 0, fpNsum = 0;
        const fpSeenTasks = new Set();
        // Closure outcome: flat-only production/discarded/dismissed path.
        let oqClosureKsum = 0, oqClosureN = 0;
        const oqClosureStatuses = { production: 0, discarded: 0, dismissed: 0 };
        // Dispute Loss Avoidance: only rejected writer disputes are adverse.
        let dwLosses = 0, dwResolved = 0, dwWins = 0;

        let earliestTs = null;

        for (const item of writerItems) {
            const task = item.task;
            if (!task) continue;
            const taskCreatedAt = reTaskTimestamp(task, item);

            const tts = Date.parse(taskCreatedAt);
            if (!Number.isNaN(tts) && (earliestTs == null || tts < earliestTs)) earliestTs = tts;

            // Outcome Quality: terminal tasks only
            const terminalQuality = reTaskTerminalQuality(task, nowMs);
            const taskInScope = reEventWeight(taskCreatedAt, 'flat', nowMs, window) > 0;
            const taskStatus = String((task && task.status) || '').toLowerCase().trim();

            if (terminalQuality !== null && taskInScope) {
                oqTerminalCount += 1;
                const taskW = reEventWeight(taskCreatedAt, weighting, nowMs, window);
                if (taskW > 0) {
                    oqKsumA += terminalQuality * taskW;
                    oqNsumA += taskW;
                    if (taskStatus !== 'bugged') {
                        oqKsumB += terminalQuality * taskW;
                        oqNsumB += taskW;
                    }
                }
            }

            // Intentionally flat in both variants; window filtering still applies.
            const closureQuality = reTaskClosureQuality(task);
            if (closureQuality !== null && taskInScope) {
                oqClosureKsum += closureQuality;
                oqClosureN += 1;
                oqClosureStatuses[taskStatus] += 1;
            }

            // Human feedback axes: positive rate, non-bottom, first-pass
            const taskId = String(task.id || '');
            const allHumanFb = reHumanFeedbackChronological(task);

            for (const entry of allHumanFb) {
                const fbAt = reFeedbackTimestamp(entry);
                const fw = reEventWeight(fbAt, weighting, nowMs, window);
                if (fw <= 0) continue;

                // Positive Feedback Rate
                pfNsum += fw;
                if (entry.isPositive) pfKsum += fw;

                // Non-Bottom Score Rate (explicit score labels only via qualityRatingRaw)
                const rawRating = entry.display && entry.display.qualityRatingRaw;
                if (rawRating === 'Average' || rawRating === 'Top 10%' || rawRating === 'Bottom 10%') {
                    nbNsum += fw;
                    if (rawRating !== 'Bottom 10%') nbKsum += fw;
                }

                // First-Pass Acceptance: first in-scope feedback per task
                if (taskId && !fpSeenTasks.has(taskId)) {
                    fpSeenTasks.add(taskId);
                    fpNsum += fw;
                    if (entry.isPositive) fpKsum += fw;
                }
            }

            // Dispute Loss Avoidance: wins are informational only.
            for (const dispute of item.disputes || []) {
                if (!dispute.resolutionAt) continue;
                if (reEventWeight(dispute.resolutionAt, 'flat', nowMs, window) <= 0) continue;
                dwResolved += 1;
                if (dispute.isRejected) dwLosses += 1;
                if (dispute.isApproved) dwWins += 1;
            }
        }

        const priors = reCohortPriors('twqs', cohort);
        const oqScoreA = reShrunkRate(oqKsumA, oqNsumA, RE_TWQS_C.outcomeQuality, priors.outcomeQuality);
        const oqScoreB = oqNsumB > 0
            ? reShrunkRate(oqKsumB, oqNsumB, RE_TWQS_C.outcomeQuality, priors.outcomeQuality)
            : null;
        const oqCurrentScore = oqScoreB != null
            ? (0.5 * oqScoreA + 0.5 * oqScoreB)
            : oqScoreA;
        const oqClosureScore = oqClosureN > 0
            ? reShrunkRate(oqClosureKsum, oqClosureN, RE_TWQS_C.outcomeQuality, priors.outcomeQuality)
            : null;
        const oqScore = oqClosureScore != null
            ? (0.5 * oqCurrentScore + 0.5 * oqClosureScore)
            : oqCurrentScore;
        const pfScore = reShrunkRate(pfKsum, pfNsum, RE_TWQS_C.positiveFeedbackRate, priors.positiveFeedbackRate);
        const nbScore = reShrunkRate(nbKsum, nbNsum, RE_TWQS_C.nonBottomScoreRate, priors.nonBottomScoreRate);
        const fpScore = reShrunkRate(fpKsum, fpNsum, RE_TWQS_C.firstPassAcceptance, priors.firstPassAcceptance);
        const dwScore = reShrunkRate(0, dwLosses, RE_TWQS_C.disputeLossAvoidance, priors.disputeLossAvoidance);

        const axes = RE_TWQS_AXES.map((def) => {
            let score = null;
            let defined = true;
            let raw = {};
            switch (def.id) {
                case 'outcomeQuality':
                    score = oqScore;
                    raw = {
                        terminalTaskCount: oqTerminalCount,
                        weightedQualitySum: Math.round(oqKsumA * 1000) / 1000,
                        weightedN: Math.round(oqNsumA * 1000) / 1000,
                        statusWeightedScore: Math.round(oqScoreA * 1000) / 1000,
                        ignoreBuggedScore: oqScoreB != null ? Math.round(oqScoreB * 1000) / 1000 : null,
                        ignoreBuggedWeightedN: Math.round(oqNsumB * 1000) / 1000,
                        currentScore: Math.round(oqCurrentScore * 1000) / 1000,
                        closureScore: oqClosureScore != null ? Math.round(oqClosureScore * 1000) / 1000 : null,
                        closureN: oqClosureN,
                        closureStatusCounts: oqClosureStatuses,
                        blend: oqClosureScore != null
                            ? '0.5*currentOutcome + 0.5*closureOutcome'
                            : 'currentOutcome (no closure outcomes)'
                    };
                    break;
                case 'positiveFeedbackRate':
                    score = pfScore;
                    raw = {
                        weightedPositive: Math.round(pfKsum * 1000) / 1000,
                        weightedTotal: Math.round(pfNsum * 1000) / 1000
                    };
                    break;
                case 'nonBottomScoreRate':
                    score = nbScore;
                    raw = {
                        weightedNonBottom: Math.round(nbKsum * 1000) / 1000,
                        weightedScored: Math.round(nbNsum * 1000) / 1000
                    };
                    break;
                case 'firstPassAcceptance':
                    score = fpScore;
                    raw = {
                        weightedAccepted: Math.round(fpKsum * 1000) / 1000,
                        weightedEligible: Math.round(fpNsum * 1000) / 1000,
                        taskCount: fpSeenTasks.size
                    };
                    break;
                case 'disputeLossAvoidance':
                    score = dwScore;
                    raw = { losses: dwLosses, wins: dwWins, resolved: dwResolved };
                    break;
                default:
                    break;
            }
            return { id: def.id, label: def.label, baseWeight: def.weight, score, defined, raw };
        });

        const combined = reCombineAxes(axes);
        const params = RE_PERCENTILE_PARAMS.twqs[weighting] || {};
        combined.estimatedPercentile = reEstimatePercentile(combined.score, params);
        combined.confidence = reTwqsConfidenceBadge(oqTerminalCount);
        combined.display = {
            writerItemCount: writerItems.length,
            terminalTaskCount: oqTerminalCount,
            tenureDays: earliestTs != null
                ? Math.max(0, Math.round((nowMs - earliestTs) / RE_MS_PER_DAY))
                : null
        };
        combined.raw = {
            oqKsum: Math.round(oqKsumA * 1000) / 1000,
            oqNsum: Math.round(oqNsumA * 1000) / 1000,
            pfKsum: Math.round(pfKsum * 1000) / 1000,
            pfNsum: Math.round(pfNsum * 1000) / 1000,
            nbKsum: Math.round(nbKsum * 1000) / 1000,
            nbNsum: Math.round(nbNsum * 1000) / 1000,
            fpKsum: Math.round(fpKsum * 1000) / 1000,
            fpNsum: Math.round(fpNsum * 1000) / 1000,
            oqClosureKsum: Math.round(oqClosureKsum * 1000) / 1000,
            oqClosureN,
            dwLosses,
            dwWins,
            dwResolved
        };

        return combined;
    },

    // Computes QPS-aligned QAQS (four-axis, rank-qa.py v2.1 formula).
    _computeQaqs(workerId, hydratedItems, weighting, window, nowMs, cohort) {
        const feedbackRows = reCollectQaqsFeedbackRows(workerId, hydratedItems);
        if (feedbackRows.length === 0) return null;

        // Return Effectiveness: neg feedback on terminal tasks → production
        let reKsum = 0, reNsum = 0;
        // Return Actionability: neg on production → next human row positive?
        let raKsum = 0, raNsum = 0;
        // Label Discrimination: explicit score labels (qualityRatingRaw)
        let ldKsum = 0, ldNsum = 0;
        // Dispute Loss Avoidance: sole-neg attribution, unweighted.
        let ddLosses = 0, ddDenom = 0, ddWins = 0;

        let inScopeFeedbackCount = 0;
        let earliestTs = null;

        for (const { entry, task } of feedbackRows) {
            const fbAt = reFeedbackTimestamp(entry);
            const inScope = reEventWeight(fbAt, 'flat', nowMs, window) > 0;
            if (!inScope) continue;

            inScopeFeedbackCount += 1;
            const ts = Date.parse(fbAt);
            if (!Number.isNaN(ts) && (earliestTs == null || ts < earliestTs)) earliestTs = ts;

            const fw = reEventWeight(fbAt, weighting, nowMs, window);
            const taskStatus = String((task && task.status) || '').toLowerCase().trim();

            // Return Effectiveness: neg feedback on terminal tasks
            if (!entry.isPositive) {
                const termQ = reTaskTerminalQuality(task, nowMs);
                if (termQ !== null) {
                    reNsum += fw;
                    if (taskStatus === 'production') reKsum += fw;
                }
            }

            // Return Actionability: neg on production → next human row positive?
            if (!entry.isPositive && taskStatus === 'production') {
                raNsum += fw;
                const allHuman = reHumanFeedbackChronological(task);
                const idx = allHuman.findIndex((e) => reIdsEqual(e.id, entry.id));
                if (idx >= 0 && idx + 1 < allHuman.length && allHuman[idx + 1].isPositive) {
                    raKsum += fw;
                }
            }

            // Label Discrimination: explicit score labels only (qualityRatingRaw)
            const rawRating = entry.display && entry.display.qualityRatingRaw;
            if (rawRating === 'Average' || rawRating === 'Top 10%' || rawRating === 'Bottom 10%') {
                ldNsum += fw;
                if (rawRating !== 'Average') ldKsum += fw;
            }
        }

        // Dispute Defense: sole-neg reviewer attribution (mirrors fill_dispute_defense).
        // A dispute is attributed to workerId only if workerId is the sole distinct
        // negative reviewer on that task. Counts are unweighted.
        for (const item of hydratedItems) {
            const task = item.task;
            if (!task) continue;

            // Collect distinct neg reviewer IDs on this task
            const negReviewerIds = new Set();
            for (const entry of task.allFeedback || []) {
                if (!reIsHumanFeedback(entry)) continue;
                if (!entry.isPositive) {
                    const rid = entry.reviewer && entry.reviewer.id;
                    if (rid) negReviewerIds.add(String(rid));
                }
            }

            if (negReviewerIds.size !== 1) continue;
            const soleNegId = [...negReviewerIds][0];
            if (!reIdsEqual(soleNegId, workerId)) continue;

            for (const dispute of item.disputes || []) {
                if (!dispute.resolutionAt) continue;
                if (reEventWeight(dispute.resolutionAt, 'flat', nowMs, window) <= 0) continue;
                ddDenom += 1;
                if (dispute.isApproved) ddLosses += 1;
                if (dispute.isRejected) ddWins += 1;
            }
        }

        // Shrunk scores.
        // returnEffectiveness and labelDiscrimination are always defined (prior when n=0).
        const priors = reCohortPriors('qaqs', cohort);
        const reScore = reShrunkRate(reKsum, reNsum, RE_QAQS_RET_EFF_C, priors.returnEffectiveness);
        const raDefined = raNsum > 0;
        const raScore = raDefined ? reShrunkRate(raKsum, raNsum, RE_QAQS_RET_ACT_C, priors.returnActionability) : null;
        const ldScore = reShrunkRate(ldKsum, ldNsum, RE_QAQS_LABEL_DISC_C, priors.labelDiscrimination);
        const ddScore = reShrunkRate(0, ddLosses, RE_QAQS_DISPUTE_DEF_C, priors.disputeDefense);

        const axes = RE_QAQS_AXES.map((def) => {
            let score = null;
            let defined = true;
            let raw = {};
            switch (def.id) {
                case 'returnEffectiveness':
                    score = reScore;
                    raw = {
                        weightedResolved: Math.round(reKsum * 1000) / 1000,
                        weightedNegTerminal: Math.round(reNsum * 1000) / 1000
                    };
                    break;
                case 'returnActionability':
                    defined = raDefined;
                    score = raScore;
                    raw = {
                        weightedOneRound: Math.round(raKsum * 1000) / 1000,
                        weightedNegProduction: Math.round(raNsum * 1000) / 1000
                    };
                    break;
                case 'disputeDefense':
                    score = ddScore;
                    raw = { losses: ddLosses, wins: ddWins, resolved: ddDenom };
                    break;
                case 'labelDiscrimination':
                    score = ldScore;
                    raw = {
                        weightedNonStd: Math.round(ldKsum * 1000) / 1000,
                        weightedScored: Math.round(ldNsum * 1000) / 1000
                    };
                    break;
                default:
                    break;
            }
            return { id: def.id, label: def.label, baseWeight: def.weight, score, defined, raw };
        });

        const combined = reCombineAxes(axes);
        const params = RE_PERCENTILE_PARAMS.qaqs[weighting] || {};
        combined.estimatedPercentile = reEstimatePercentile(combined.score, params);
        combined.confidence = reQaqsConfidenceBadge(inScopeFeedbackCount);
        combined.display = {
            feedbackRowCount: feedbackRows.length,
            inScopeFeedbackCount,
            tenureDays: earliestTs != null
                ? Math.max(0, Math.round((nowMs - earliestTs) / RE_MS_PER_DAY))
                : null,
            negOnTerminalCount: Math.round(reNsum),
            negOnProductionCount: Math.round(raNsum)
        };
        combined.raw = {
            reKsum: Math.round(reKsum * 1000) / 1000,
            reNsum: Math.round(reNsum * 1000) / 1000,
            raKsum: Math.round(raKsum * 1000) / 1000,
            raNsum: Math.round(raNsum * 1000) / 1000,
            ldKsum: Math.round(ldKsum * 1000) / 1000,
            ldNsum: Math.round(ldNsum * 1000) / 1000,
            ddLosses,
            ddWins,
            ddDenom
        };

        return combined;
    },

    buildDiagnosticsReport(workerReport, context) {
        const ctx = context || {};
        const cachedItems = (ctx.cachedItems || []).filter((item) => item && item.hydrated === true);
        const workerId = workerReport.workerId;
        const window = workerReport.window || reResolveWindow(ctx.committed);
        const nowMs = Date.parse(workerReport.computedAt) || Date.now();

        const feedbackRows = reCollectQaqsFeedbackRows(workerId, cachedItems);
        let feedbackRowsBeforeDedupe = 0;
        for (const item of cachedItems) {
            const task = item.task;
            if (!task) continue;
            for (const entry of task.allFeedback || []) {
                if (!reIsHumanFeedback(entry)) continue;
                if (!reIdsEqual(entry.reviewer && entry.reviewer.id, workerId)) continue;
                feedbackRowsBeforeDedupe += 1;
            }
        }

        const returnTypeCounts = { accepted: 0, returned: 0, escalated: 0, bugged: 0, other: 0 };
        let timestampMissingCount = 0;
        let inScopeCount = 0;
        const fieldAuditSamples = [];
        const seenAuditIds = new Set();

        for (const { entry, task } of feedbackRows) {
            const ts = reFeedbackTimestamp(entry);
            if (!ts) timestampMissingCount += 1;
            if (reEventWeight(ts, 'flat', nowMs, window) > 0) inScopeCount += 1;

            if (entry.isPositive) returnTypeCounts.accepted += 1;
            else if (entry.isEscalated) returnTypeCounts.escalated += 1;
            else if (entry.isFlaggedAsBugged) returnTypeCounts.bugged += 1;
            else if (!entry.isSystemFeedback) returnTypeCounts.returned += 1;
            else returnTypeCounts.other += 1;

            const audit = reFieldAuditRow(entry, task, workerId);
            const isAnomalous = !audit.timestampResolvable;
            if (fieldAuditSamples.length < RE_DIAG_SAMPLE_ROWS || isAnomalous) {
                if (!seenAuditIds.has(audit.feedbackId)) {
                    seenAuditIds.add(audit.feedbackId);
                    fieldAuditSamples.push(audit);
                }
            }
        }

        const feedbackIds = new Set(feedbackRows.map((r) => String(r.entry.id)));
        const disputesInScope = [];

        for (const item of cachedItems) {
            const task = item.task;
            if (!task) continue;
            const remap = task.systemFeedbackIdRemap || {};
            const hasQaOnTask = (task.allFeedback || []).some((e) => {
                return reIsHumanFeedback(e) && reIdsEqual(e.reviewer && e.reviewer.id, workerId);
            });
            if (!hasQaOnTask) continue;

            for (const dispute of item.disputes || []) {
                const rawFid = String(dispute.feedbackId || '').trim();
                const resolvedFid = reResolveFeedbackId(dispute.feedbackId, remap);
                disputesInScope.push({
                    disputeId: String(dispute.id || ''),
                    feedbackId: rawFid,
                    resolvedFeedbackId: resolvedFid,
                    matchesWorkerFeedback: Boolean(resolvedFid && feedbackIds.has(resolvedFid)),
                    status: dispute.status || null,
                    resolutionAt: dispute.resolutionAt || null,
                    isRejected: Boolean(dispute.isRejected),
                    isApproved: Boolean(dispute.isApproved)
                });
            }
        }

        const recencyTwqs = workerReport.twqs && workerReport.twqs.recency;
        const recencyQaqs = workerReport.qaqs && workerReport.qaqs.recency;

        const qaqsAxisDebug = ((recencyQaqs && recencyQaqs.axes) || []).map((p) => ({
            id: p.id, label: p.label, defined: p.defined !== false,
            whyOmitted: reAxisOmitReason(p), score: p.score, raw: p.raw || {}
        }));

        const twqsAxisDebug = ((recencyTwqs && recencyTwqs.axes) || []).map((p) => ({
            id: p.id, label: p.label, defined: p.defined !== false,
            whyOmitted: reAxisOmitReason(p), score: p.score, raw: p.raw || {}
        }));

        return {
            meta: {
                engineVersion: RE_VERSION,
                computedAt: workerReport.computedAt || new Date(nowMs).toISOString(),
                workerId,
                name: workerReport.name || workerId,
                email: workerReport.email || '',
                window,
                hydratedCount: cachedItems.length,
                unhydratedCount: ctx.unhydratedCount != null
                    ? ctx.unhydratedCount
                    : Math.max(0, (ctx.cachedItems || []).length - cachedItems.length)
            },
            warnings: ctx.warnings || [],
            fieldAudit: {
                accessorNotes: {
                    feedbackTimestamp: 'Uses entry.feedbackAt with fallback to entry.created_at',
                    taskTimestamp: 'Uses task.createdAt with fallback to item.sortAt',
                    disputeFeedbackId: 'Applies task.systemFeedbackIdRemap before matching QA feedback rows'
                },
                samples: fieldAuditSamples
            },
            qaqs: {
                feedbackRowsBeforeDedupe,
                feedbackRowsDeduped: feedbackRows.length,
                inScopeCount,
                timestampMissingCount,
                returnTypeCounts,
                disputesInScope,
                axisDebug: qaqsAxisDebug
            },
            twqs: recencyTwqs ? {
                writerItemCount: this._writerItems(workerId, cachedItems).length,
                axisDebug: twqsAxisDebug
            } : null,
            scores: {
                flat: {
                    twqs: workerReport.twqs && workerReport.twqs.flat
                        ? { score: workerReport.twqs.flat.score, band: workerReport.twqs.flat.band } : null,
                    qaqs: workerReport.qaqs && workerReport.qaqs.flat
                        ? { score: workerReport.qaqs.flat.score, band: workerReport.qaqs.flat.band } : null,
                    combined: workerReport.combined && workerReport.combined.flat
                        ? { score: workerReport.combined.flat.score, band: workerReport.combined.flat.band } : null
                },
                recency: {
                    twqs: recencyTwqs ? { score: recencyTwqs.score, band: recencyTwqs.band } : null,
                    qaqs: recencyQaqs ? { score: recencyQaqs.score, band: recencyQaqs.band } : null,
                    combined: workerReport.combined && workerReport.combined.recency
                        ? { score: workerReport.combined.recency.score, band: workerReport.combined.recency.band } : null
                }
            }
        };
    },

    buildExportFilename(workerReport, scoreType, ext) {
        const name = reSlugify(workerReport.name || workerReport.workerId);
        const date = (workerReport.exportDate || new Date().toISOString().slice(0, 10));
        return 'rating-' + name + '-' + scoreType + '-' + date + '.' + ext;
    },

    buildDiagnosticsFilename(workerReport) {
        const name = reSlugify(workerReport.name || workerReport.workerId);
        const date = (workerReport.exportDate || new Date().toISOString().slice(0, 10));
        return 'rating-' + name + '-diagnostics-' + date + '.json';
    },

    serializeJson(report) {
        return JSON.stringify(reWorkerJsonExport(report), null, 2);
    },

    serializeDiagnosticsJson(report) {
        return JSON.stringify(report, null, 2);
    },

    serializeMarkdown(workerReport) {
        const lines = [];
        lines.push('# Worker Rating Report');
        lines.push('');
        lines.push('- **Worker:** ' + (workerReport.name || workerReport.workerId));
        if (workerReport.email) lines.push('- **Email:** ' + workerReport.email);
        lines.push('- **Computed:** ' + (workerReport.computedAt || new Date().toISOString()));
        const win = workerReport.window || {};
        if (win.afterLocal || win.beforeLocal) {
            lines.push('- **Window:** ' + (win.afterLocal || '…') + ' → ' + (win.beforeLocal || '…'));
        } else {
            lines.push('- **Window:** All time');
        }
        lines.push('- **Engine version:** ' + (workerReport.engineVersion || RE_VERSION));
        lines.push('');

        const renderScoreBlock = (title, block) => {
            if (!block || block.score == null) return;
            lines.push('## ' + title);
            lines.push('');
            let scoreStr = String(Math.round(block.score)) + ' / 100 · ' + block.band;
            if (block.estimatedPercentile != null) {
                scoreStr += ' · ~' + reFormatPercentile(block.estimatedPercentile) + ' percentile (estimated)';
            }
            lines.push('**Score:** ' + scoreStr);
            lines.push('**Confidence:** ' + (block.confidence && block.confidence.label));
            lines.push('');
            lines.push('| Axis | Sub-score | Weight |');
            lines.push('| --- | ---: | ---: |');
            for (const p of block.axes || []) {
                const wt = p.effectiveWeight != null
                    ? (Math.round(p.effectiveWeight * 1000) / 10) + '%'
                    : '—';
                const sc = p.defined === false ? 'omitted' : reFormatPct(p.score || 0);
                lines.push('| ' + p.label + ' | ' + sc + ' | ' + wt + ' |');
            }
            lines.push('');
        };

        const renderCombinedBlock = (title, block) => {
            if (!block || block.score == null) return;
            lines.push('## ' + title);
            lines.push('');
            let scoreStr = String(Math.round(block.score)) + ' / 100 · ' + block.band;
            if (block.estimatedPercentile != null) {
                scoreStr += ' · ~' + reFormatPercentile(block.estimatedPercentile) + ' percentile (estimated)';
            }
            lines.push('**Score:** ' + scoreStr);
            if (block.writerRatio != null) {
                lines.push('**Volume blend:** ' + Math.round(block.writerRatio * 100) + '% writer + '
                    + Math.round(block.qaRatio * 100) + '% QA (' + block.nTerminal + ' tasks / ' + block.nFeedback + ' feedbacks)');
            }
            lines.push('');
        };

        for (const weighting of ['recency', 'flat']) {
            const label = weighting === 'recency' ? 'Recency-weighted (90-day half-life)' : 'Flat-weighted';
            const twqs = workerReport.twqs && workerReport.twqs[weighting];
            const qaqs = workerReport.qaqs && workerReport.qaqs[weighting];
            const comb = workerReport.combined && workerReport.combined[weighting];

            if (twqs || qaqs) {
                lines.push('---');
                lines.push('');
                lines.push('# ' + label);
                lines.push('');
                renderScoreBlock('Task Writer Quality Score (TWQS)', twqs);
                renderScoreBlock('QA Quality Score (QAQS)', qaqs);
                renderCombinedBlock('Combined Score', comb);
            }
        }

        if (workerReport.meta) {
            lines.push('## Meta');
            lines.push('- Hydrated items used: ' + workerReport.meta.hydratedCount);
            lines.push('- Unhydrated items excluded: ' + workerReport.meta.unhydratedCount);
        }

        return lines.join('\n');
    }
};

const plugin = {
    id: 'rating-engine',
    name: 'Rating Engine',
    description: 'TWQS, QAQS, and Combined computation for Worker Output Search ratings (WPS/QPS aligned)',
    _version: '6.2',
    phase: 'core',
    enabledByDefault: true,
    initialState: { registered: false },

    init(state) {
        if (state && state.registered) {
            Logger.debug('rating-engine: already registered — skipping re-init');
            return;
        }
        Context.ratingEngine = RatingEngine;
        if (state) state.registered = true;
        Logger.log('rating-engine: module registered (Context.ratingEngine) v' + RE_VERSION);
    }
};
