// rating-engine.js — TWQS / QAQS computation for Worker Output Search Ratings tab.
// Engine v11.0: population tiers reflect score cutoffs without volume demotion.

const RE_VERSION = '11.0';
const RE_MS_PER_DAY = 86400000;
const RE_HALFLIFE_DAYS = 30;
const RE_DIAG_SAMPLE_ROWS = 5;
const RE_DISCARDED_STALE_DAYS = 7;
// Reserved percent points on each end of the estimated-percentile scale (UI + exports).
const RE_PERCENTILE_MARGIN_BOTTOM = 10;
const RE_PERCENTILE_MARGIN_TOP = 20;

// Terminal task status → quality score (mirrors rank-workers.py STATUS_QUALITY).
// Statuses not listed here are in-flight — excluded from outcome quality denominator.
const RE_STATUS_QUALITY = {
    production: 1.0,
    bugged: 0.5,
    'escalated-fleet-review': 0.5,
    discarded: 0.15,
    dismissed: 0.0,
};
const RE_CLOSURE_QUALITY = {
    production: 1.0,
    discarded: 0.5,
    dismissed: 0.0,
};

// Explicit prompt-quality labels → ordinal Task Rating Quality points.
const RE_TASK_RATING_QUALITY_VALUE = {
    'Bottom 10%': 0,
    Average: 0.5,
    'Top 10%': 1,
};

// WPS (TWQS) per-axis shrinkage strengths (C). Priors come from encrypted Ops baselines.
const RE_TWQS_C = {
    outcomeQuality:       10,
    positiveFeedbackRate: 10,
    taskRatingQuality:     5,
    firstPassAcceptance:   5,
    disputeLossAvoidance:  5,
};

// QPS (QAQS) per-axis shrinkage strengths (C). Priors come from encrypted Ops baselines.
const RE_QAQS_RET_EFF_C         = 10;
const RE_QAQS_RET_ACT_C         = 10;
const RE_QAQS_DISPUTE_DEF_C     = 5;
const RE_QAQS_LABEL_DISC_C      = 5;
// Omit Label Discrimination on thin QA samples (matches TW provisional threshold).
const RE_QAQS_LABEL_DISC_MIN_N  = 10;

// Documented generation-time cutoffs (applied by compute-cohort-baselines.py).
// Live engine uses presence of a shipped role pack — not these numbers — for selection.
const RE_BASELINE_POLICY = {
    twqs: { minTasks: 500, minWriters: 20 },
    qaqs: { minFeedback: 500, minReviewers: 20 },
};

const RE_TWQS_AXES = [
    { id: 'outcomeQuality',       label: 'Outcome Quality',        weight: 0.40 },
    { id: 'positiveFeedbackRate', label: 'Positive Feedback Rate', weight: 0.20 },
    { id: 'taskRatingQuality',    label: 'Task Rating Quality',    weight: 0.15 },
    { id: 'firstPassAcceptance',  label: 'First-Pass Acceptance',  weight: 0.15 },
    { id: 'disputeLossAvoidance', label: 'Dispute Loss Avoidance', weight: 0.10 },
];

const RE_QAQS_AXES = [
    { id: 'returnEffectiveness', label: 'Return Effectiveness', weight: 0.40 },
    { id: 'returnActionability', label: 'Return Actionability', weight: 0.25 },
    { id: 'disputeDefense',      label: 'Dispute Loss Avoidance', weight: 0.20 },
    { id: 'labelDiscrimination', label: 'Label Discrimination', weight: 0.15 },
];

// Population tier labels (card primary). Absolute top pegs + empirical p10/p30/p70.
// Regenerated by local/db/utils/compute-percentile-calibration.py (tierThresholds).
// Snapshot: 1316 WPS / 285 QPS; flat + recency30d (Task Rating Quality).
const RE_TIER_TOP_PEG = { twqs: 80, qaqs: 70 };
const RE_TIER_DEFS = [
    { id: 'poor', label: 'Poor' },
    { id: 'below_average', label: 'Below average' },
    { id: 'typical', label: 'Typical' },
    { id: 'above_average', label: 'Above average' },
    { id: 'top_tier', label: 'Top tier' },
];
const RE_TIER_THRESHOLDS = {
    twqs: {
        flat:    { p10: 55.725, p30: 61.41, p70: 68.44, topMin: 80 },
        recency: { p10: 60.0, p30: 64.23, p70: 67.48, topMin: 80 },
    },
    qaqs: {
        flat:    { p10: 49.14, p30: 54.526, p70: 60.76, topMin: 70 },
        recency: { p10: 49.146, p30: 54.602, p70: 60.206, topMin: 70 },
    },
};

// Parametric percentile distributions (μ, σ) fitted from current dive.db scores.
// Estimated percentile (shown on cards, included in exports) =
// bottom + (100 − bottom − top) × Φ((score − μ) / σ)
// with bottom=10, top=20. Regenerated by compute-percentile-calibration.py.
// Snapshot: 1316 WPS / 285 QPS; flat + recency30d (Task Rating Quality).
const RE_PERCENTILE_PARAMS = {
    twqs: {
        flat:    { mu: 64.4979, sigma: 6.8760 },
        recency: { mu: 65.7865, sigma: 4.7910 },
    },
    qaqs: {
        flat:    { mu: 57.3562, sigma: 6.2947 },
        recency: { mu: 56.8314, sigma: 5.8665 },
    },
};

// ---------------------------------------------------------------------------
// Utility helpers
// ---------------------------------------------------------------------------

function reLib() {
    return Context.dashboardLib || null;
}

function reFeedbackTimestamp(entry) {
    return String((entry && (entry.feedbackAt || entry.created_at)) || '').trim();
}

function reTaskTimestamp(task, item) {
    return String((task && (task.createdAt || task.created_at)) || (item && item.sortAt) || '').trim();
}

function reIdsEqual(a, b) {
    return String(a || '').trim() === String(b || '').trim();
}

function reResolveFeedbackId(id, remap) {
    const key = String(id || '').trim();
    if (!key) return '';
    return String((remap && remap[key]) || key);
}

function reFeedbackAtForResolvedId(task, feedbackId) {
    const fid = String(feedbackId || '').trim();
    if (!fid || !task) return '';
    for (const entry of task.allFeedback || []) {
        if (!reIsHumanFeedback(entry)) continue;
        if (reIdsEqual(entry.id, fid)) return reFeedbackTimestamp(entry);
    }
    return '';
}

function reIsHumanFeedback(entry) {
    if (!entry) return false;
    if (entry.isVerifierFailure || entry.isSystemFeedback) return false;
    if (entry.display && (entry.display.isVerifierFailure || entry.display.isSystemFeedback)) return false;
    return true;
}

// Returns quality score for terminal tasks; null for in-flight (mirrors rank-workers.py task_terminal_quality).
function reTaskTerminalQuality(task, nowMs) {
    const status = String((task && task.status) || '').toLowerCase().trim();
    if (!status) return null;
    if (status === 'discarded') {
        const createdAt = String((task && (task.createdAt || task.created_at)) || '').trim();
        const ts = Date.parse(createdAt);
        if (Number.isNaN(ts)) return null;
        const ageDays = Math.max(0, (nowMs - ts) / RE_MS_PER_DAY);
        if (ageDays < RE_DISCARDED_STALE_DAYS) return null;
        return RE_STATUS_QUALITY.discarded;
    }
    const quality = RE_STATUS_QUALITY[status];
    return quality !== undefined ? quality : null;
}

// Closure quality intentionally does not apply the discarded stale-age gate.
// It measures the eventual path for tasks that were not bugged/flagged.
function reTaskClosureQuality(task) {
    const status = String((task && task.status) || '').toLowerCase().trim();
    const quality = RE_CLOSURE_QUALITY[status];
    return quality !== undefined ? quality : null;
}

// Standard normal CDF approximation (Abramowitz–Stegun rational, max error ≈7.5×10⁻⁸).
function reNormalCdf(z) {
    const t = 1 / (1 + 0.2316419 * Math.abs(z));
    const poly = t * (0.319381530 + t * (-0.356563782 + t * (1.781477937 + t * (-1.821255978 + t * 1.330274429))));
    const pdf = Math.exp(-0.5 * z * z) / Math.sqrt(2 * Math.PI);
    const cdf = 1 - pdf * poly;
    return z >= 0 ? cdf : 1 - cdf;
}

// Estimated percentile via bottom + (100 − bottom − top) × Φ((score − μ) / σ).
// Returns integer in [bottom, 100−top] (currently 10–80), or null.
function reEstimatePercentile(score, params) {
    if (score == null || !Number.isFinite(score)) return null;
    if (!params || !Number.isFinite(params.mu) || !Number.isFinite(params.sigma) || params.sigma <= 0) return null;
    const bottom = RE_PERCENTILE_MARGIN_BOTTOM;
    const top = RE_PERCENTILE_MARGIN_TOP;
    const span = 100 - bottom - top;
    const z = (score - params.mu) / params.sigma;
    const pct = bottom + span * reNormalCdf(z);
    return Math.max(bottom, Math.min(100 - top, Math.round(pct)));
}

function reOrdinalSuffix(n) {
    const v = Math.abs(Math.trunc(Number(n)));
    if (!Number.isFinite(v)) return 'th';
    const mod100 = v % 100;
    if (mod100 >= 11 && mod100 <= 13) return 'th';
    const mod10 = v % 10;
    if (mod10 === 1) return 'st';
    if (mod10 === 2) return 'nd';
    if (mod10 === 3) return 'rd';
    return 'th';
}

/** Formats an integer percentile as e.g. "72nd". Returns '' if invalid. */
function reFormatPercentile(n) {
    if (n == null || !Number.isFinite(Number(n))) return '';
    const v = Math.round(Number(n));
    return String(v) + reOrdinalSuffix(v);
}

// Empirical-Bayes shrinkage toward cohort prior.
function reShrunkRate(k, n, C, prior) {
    return (k + C * prior) / (n + C);
}

/** Population tier from empirical cutoffs + absolute top peg. */
function rePopulationTier(score, kind, weighting) {
    const n = Number(score);
    if (!Number.isFinite(n)) return { id: null, label: '—' };
    const params = (RE_TIER_THRESHOLDS[kind] && RE_TIER_THRESHOLDS[kind][weighting]) || null;
    if (!params) return { id: null, label: '—' };
    let topMin = Number(params.topMin);
    const p10 = Number(params.p10);
    const p30 = Number(params.p30);
    const p70 = Number(params.p70);
    if (!(topMin > p70)) topMin = p70 + 0.01;
    if (n >= topMin) return { id: RE_TIER_DEFS[4].id, label: RE_TIER_DEFS[4].label };
    if (n >= p70) return { id: RE_TIER_DEFS[3].id, label: RE_TIER_DEFS[3].label };
    if (n >= p30) return { id: RE_TIER_DEFS[2].id, label: RE_TIER_DEFS[2].label };
    if (n >= p10) return { id: RE_TIER_DEFS[1].id, label: RE_TIER_DEFS[1].label };
    return { id: RE_TIER_DEFS[0].id, label: RE_TIER_DEFS[0].label };
}

function reAnnotatePopulationTier(block, kind, weighting) {
    if (!block) return block;
    if (block.score == null || !Number.isFinite(Number(block.score))) {
        block.band = '—';
        block.tierId = null;
        return block;
    }
    const tier = rePopulationTier(block.score, kind, weighting);
    block.band = tier.label;
    block.tierId = tier.id;
    return block;
}

// TWQS confidence: based on terminal task count (mirrors rank-workers.py _confidence).
function reTwqsConfidenceBadge(terminalCount) {
    const n = Number(terminalCount) || 0;
    if (n < 10) return { tier: 'provisional', label: 'Provisional' };
    if (n < 50) return { tier: 'standard', label: 'Standard' };
    return { tier: 'high', label: 'High confidence' };
}

// QAQS confidence: based on feedback row count (mirrors rank-qa.py _confidence).
function reQaqsConfidenceBadge(feedbackRowCount) {
    const n = Number(feedbackRowCount) || 0;
    if (n < 25) return { tier: 'provisional', label: 'Provisional' };
    if (n < 100) return { tier: 'standard', label: 'Standard' };
    return { tier: 'high', label: 'High confidence' };
}

// Returns 0 when outside date window or timestamp unparseable.
// 'flat'    → 1.0 inside window (or always if no window)
// 'recency' → exp(−ln(2)·age/H) inside window (or always if no window)
function reEventWeight(isoTs, weighting, nowMs, window) {
    const ts = Date.parse(isoTs);
    if (Number.isNaN(ts)) return 0;
    if (window) {
        if (window.afterIso && isoTs < window.afterIso) return 0;
        if (window.beforeIso && isoTs > window.beforeIso) return 0;
    }
    if (weighting === 'flat') return 1;
    const ageDays = Math.max(0, (nowMs - ts) / RE_MS_PER_DAY);
    return Math.exp(-Math.LN2 * ageDays / RE_HALFLIFE_DAYS);
}

function reResolveWindow(committed) {
    const lib = reLib();
    const afterLocal = String((committed && committed.afterLocal) || '').trim();
    const beforeLocal = String((committed && committed.beforeLocal) || '').trim();
    let afterIso = '';
    let beforeIso = '';
    if (lib && typeof lib.validateCreatedAtRange === 'function') {
        const check = lib.validateCreatedAtRange(afterLocal, beforeLocal);
        if (check && check.valid) {
            afterIso = check.afterIso || '';
            beforeIso = check.beforeIso || '';
        }
    }
    return { afterLocal, beforeLocal, afterIso, beforeIso };
}

function reWeightedMean(pairs) {
    let wSum = 0;
    let total = 0;
    for (const { value, weight } of pairs) {
        if (!weight || weight <= 0) continue;
        wSum += weight;
        total += value * weight;
    }
    if (wSum <= 0) return null;
    return total / wSum;
}

function reCombineAxes(axisDefs) {
    const defined = axisDefs.filter((p) => p.defined !== false && p.score != null && Number.isFinite(p.score));
    if (defined.length === 0) {
        return { score: null, band: '—', tierId: null, axes: axisDefs };
    }
    const baseSum = defined.reduce((s, p) => s + p.baseWeight, 0);
    let composite = 0;
    for (const p of axisDefs) {
        if (p.defined === false || p.score == null || !Number.isFinite(p.score)) {
            p.effectiveWeight = 0;
            continue;
        }
        p.effectiveWeight = p.baseWeight / baseSum;
        composite += p.score * p.effectiveWeight;
    }
    const score = Math.round(composite * 1000) / 10;
    return { score, band: '—', tierId: null, axes: axisDefs };
}

function reTaskRatingQualityValue(rawRating) {
    const key = String(rawRating || '').trim();
    return Object.prototype.hasOwnProperty.call(RE_TASK_RATING_QUALITY_VALUE, key)
        ? RE_TASK_RATING_QUALITY_VALUE[key]
        : null;
}

function reExportTimestampSlug(value) {
    const parsed = value ? new Date(value) : new Date();
    const date = Number.isNaN(parsed.getTime()) ? new Date() : parsed;
    return date.toISOString().replace(/[:.]/g, '-');
}

function reWorkerExportIdentity(workerReport) {
    const name = reSlugify(workerReport.name || '');
    const workerId = reSlugify(workerReport.workerId || '');
    if (name && workerId && name !== workerId) return name + '-' + workerId;
    return name || workerId || 'worker';
}

function reValidateRolePriors(kind, priors) {
    if (!priors || typeof priors !== 'object') return null;
    const required = kind === 'twqs'
        ? ['outcomeQuality', 'positiveFeedbackRate', 'taskRatingQuality', 'firstPassAcceptance', 'disputeLossAvoidance']
        : ['returnEffectiveness', 'returnActionability', 'disputeDefense', 'labelDiscrimination'];
    const out = {};
    for (const id of required) {
        const n = Number(priors[id]);
        if (!Number.isFinite(n)) return null;
        out[id] = n;
    }
    return out;
}

function reValidateRatingBaselines(raw) {
    if (!raw || typeof raw !== 'object') return null;
    const globalTw = reValidateRolePriors('twqs', raw.global && raw.global.priors && raw.global.priors.twqs);
    const globalQa = reValidateRolePriors('qaqs', raw.global && raw.global.priors && raw.global.priors.qaqs);
    if (!globalTw || !globalQa) return null;
    const policy = {
        twqs: {
            minTasks: Number((raw.policy && raw.policy.twqs && raw.policy.twqs.minTasks)
                || RE_BASELINE_POLICY.twqs.minTasks),
            minWriters: Number((raw.policy && raw.policy.twqs && raw.policy.twqs.minWriters)
                || RE_BASELINE_POLICY.twqs.minWriters),
        },
        qaqs: {
            minFeedback: Number((raw.policy && raw.policy.qaqs && raw.policy.qaqs.minFeedback)
                || RE_BASELINE_POLICY.qaqs.minFeedback),
            minReviewers: Number((raw.policy && raw.policy.qaqs && raw.policy.qaqs.minReviewers)
                || RE_BASELINE_POLICY.qaqs.minReviewers),
        },
    };
    return {
        schemaVersion: Number(raw.schemaVersion) || 1,
        generatedAt: String(raw.generatedAt || '') || null,
        policy,
        global: {
            priors: { twqs: globalTw, qaqs: globalQa },
            volume: (raw.global && raw.global.volume) || null,
        },
        team: (raw.team && typeof raw.team === 'object') ? raw.team : {},
        env: (raw.env && typeof raw.env === 'object') ? raw.env : {},
        month: (raw.month && typeof raw.month === 'object') ? raw.month : {},
    };
}

function reLoadRatingBaselines(opts) {
    if (opts && opts.cohortBaselines) {
        const validated = reValidateRatingBaselines(opts.cohortBaselines);
        if (validated) return validated;
    }
    if (Context.ratingCohortBaselines) {
        const validated = reValidateRatingBaselines(Context.ratingCohortBaselines);
        if (validated) return validated;
    }
    const ops = Context.opsTab;
    if (ops && typeof ops.getRatingBaselines === 'function') {
        try {
            const fromOps = ops.getRatingBaselines();
            const validated = reValidateRatingBaselines(fromOps);
            if (validated) {
                Context.ratingCohortBaselines = validated;
                return validated;
            }
        } catch (_e) {
            // Fall through to unavailable.
        }
    }
    return null;
}

/** Resolve effective priors for a role. Subset packs are only present when eligible. */
function reResolveRolePriors(baselines, kind, dimension, key) {
    const globalPriors = baselines.global.priors[kind];
    if (!dimension || !key) {
        return {
            priors: globalPriors,
            source: 'global',
            reason: 'main',
            volume: baselines.global.volume || null,
        };
    }
    const pack = baselines[dimension] && baselines[dimension][key];
    const slicePriors = pack
        ? reValidateRolePriors(kind, pack.priors && pack.priors[kind])
        : null;
    if (!slicePriors) {
        return {
            priors: globalPriors,
            source: 'global',
            reason: 'notShipped',
            volume: (pack && pack.volume) || null,
            key,
            dimension,
        };
    }
    return {
        priors: slicePriors,
        source: 'subset',
        reason: 'shipped',
        volume: pack.volume || null,
        key,
        dimension,
    };
}

function reCohortPack(kind, resolved) {
    return {
        priors: { [kind]: resolved.priors },
        priorSource: {
            source: resolved.source,
            reason: resolved.reason,
            volume: resolved.volume,
            key: resolved.key || null,
            dimension: resolved.dimension || null,
        },
    };
}

function reCohortPriors(kind, cohort) {
    const supplied = cohort && cohort.priors && cohort.priors[kind];
    return supplied && typeof supplied === 'object' ? { ...supplied } : null;
}

function reCohortKey(task, dimension) {
    if (!task) return '';
    if (dimension === 'team') return String(task.team || task.teamId || '').trim();
    if (dimension === 'env') return String(task.envKey || task.environment || '').trim();
    if (dimension === 'month') {
        const ts = String(task.createdAt || task.created_at || '').trim();
        return /^\d{4}-\d{2}/.test(ts) ? ts.slice(0, 7) : '';
    }
    return '';
}

function reVolumeWeightedAxes(usable) {
    const byId = new Map();
    for (const row of usable || []) {
        const vol = Number(row.volume) || 0;
        if (vol <= 0 || !row.block) continue;
        for (const axis of row.block.axes || []) {
            if (!axis || axis.defined === false || axis.score == null) continue;
            const id = axis.id || axis.label;
            if (!id) continue;
            let agg = byId.get(id);
            if (!agg) {
                agg = {
                    id: axis.id,
                    label: axis.label,
                    baseWeight: axis.baseWeight,
                    scoreSum: 0,
                    volume: 0,
                };
                byId.set(id, agg);
            }
            agg.scoreSum += axis.score * vol;
            agg.volume += vol;
        }
    }
    return [...byId.values()].map((agg) => ({
        id: agg.id,
        label: agg.label,
        baseWeight: agg.baseWeight,
        score: agg.volume > 0 ? agg.scoreSum / agg.volume : null,
        defined: true,
        effectiveWeight: null,
        raw: { volume: Math.round(agg.volume * 1000) / 1000 },
    }));
}

function reBlendCohortBlocks(mainBlock, slices, confidenceFn, kind, weighting) {
    if (!mainBlock || mainBlock.score == null) return null;
    let mainWeight = 0.5;
    const channels = {};
    for (const dimension of ['team', 'env', 'month']) {
        const rows = slices[dimension] || [];
        const usable = rows.filter((row) => row.block && row.block.score != null && row.volume > 0);
        const initialWeight = 1 / 6;
        if (!usable.length) {
            mainWeight += initialWeight;
            channels[dimension] = {
                score: null, volume: 0, weight: 0, provisional: false, keys: [], axes: [], slices: [],
            };
            continue;
        }
        const totalVolume = usable.reduce((sum, row) => sum + row.volume, 0);
        const score = usable.reduce((sum, row) => sum + row.block.score * row.volume, 0) / totalVolume;
        const provisional = confidenceFn(totalVolume).tier === 'provisional';
        const weight = provisional ? initialWeight / 2 : initialWeight;
        mainWeight += initialWeight - weight;
        channels[dimension] = {
            score,
            volume: totalVolume,
            weight,
            provisional,
            keys: usable.map((row) => row.key),
            axes: reVolumeWeightedAxes(usable),
            slices: usable
                .slice()
                .sort((a, b) => (b.volume || 0) - (a.volume || 0) || String(a.key).localeCompare(String(b.key)))
                .map((row) => {
                    const sliceTier = rePopulationTier(row.block.score, kind, weighting);
                    return {
                        key: row.key,
                        score: row.block.score,
                        volume: row.volume,
                        band: sliceTier.label,
                        tierId: sliceTier.id,
                        estimatedPercentile: row.block.estimatedPercentile != null
                            ? row.block.estimatedPercentile
                            : null,
                        priorSource: row.priorSource || (row.block && row.block.priorSource) || null,
                        axes: (row.block.axes || []).map((axis) => ({ ...axis })),
                    };
                }),
        };
    }
    const score = mainWeight * mainBlock.score
        + Object.values(channels).reduce((sum, channel) => sum + (channel.score == null ? 0 : channel.weight * channel.score), 0);
    const rounded = Math.round(score * 10) / 10;
    const tier = rePopulationTier(rounded, kind, weighting);
    const pctParams = (RE_PERCENTILE_PARAMS[kind] && RE_PERCENTILE_PARAMS[kind][weighting]) || {};
    return {
        score: rounded,
        band: tier.label,
        tierId: tier.id,
        estimatedPercentile: reEstimatePercentile(rounded, pctParams),
        confidence: mainBlock.confidence,
        main: {
            score: mainBlock.score,
            weight: mainWeight,
            axes: (mainBlock.axes || []).map((axis) => ({ ...axis })),
        },
        channels,
    };
}

function reHumanFeedbackChronological(task) {
    return (task.allFeedback || [])
        .filter(reIsHumanFeedback)
        .sort((a, b) => reFeedbackTimestamp(a).localeCompare(reFeedbackTimestamp(b)));
}

function reIsoWeekKey(iso) {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return null;
    const utc = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
    const dayNum = utc.getUTCDay() || 7;
    utc.setUTCDate(utc.getUTCDate() + 4 - dayNum);
    const yearStart = new Date(Date.UTC(utc.getUTCFullYear(), 0, 1));
    const weekNo = Math.ceil((((utc - yearStart) / RE_MS_PER_DAY) + 1) / 7);
    return utc.getUTCFullYear() + '-W' + String(weekNo).padStart(2, '0');
}

function reMedian(values) {
    const nums = values.filter((v) => Number.isFinite(v)).sort((a, b) => a - b);
    if (!nums.length) return null;
    const mid = Math.floor(nums.length / 2);
    return nums.length % 2 ? nums[mid] : (nums[mid - 1] + nums[mid]) / 2;
}

function reSlugify(text) {
    return String(text || 'worker')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 48) || 'worker';
}

function reFormatPct(score) {
    const lib = reLib();
    if (lib && typeof lib.formatPercent === 'function') return lib.formatPercent(score * 100);
    return (Math.round(score * 1000) / 10).toFixed(1);
}

function rePctOneDecimal(fraction) {
    if (fraction == null || !Number.isFinite(fraction)) return null;
    return Math.round(fraction * 1000) / 10;
}

function reAxisExportRow(axis) {
    const defined = axis && axis.defined !== false && axis.score != null && Number.isFinite(axis.score);
    return {
        id: String((axis && axis.id) || ''),
        label: String((axis && axis.label) || ''),
        baseWeightPct: rePctOneDecimal(axis && axis.baseWeight),
        effectiveWeightPct: defined ? rePctOneDecimal(axis.effectiveWeight) : 0,
        subScorePct: defined ? rePctOneDecimal(axis.score) : null,
        defined
    };
}

function reSortedAxesForExport(axes) {
    return [...(axes || [])].sort((a, b) => {
        const wDiff = (b.baseWeight || 0) - (a.baseWeight || 0);
        if (wDiff !== 0) return wDiff;
        return String(a.label || '').localeCompare(String(b.label || ''));
    });
}

function reScoreBlockExport(block) {
    if (!block) return null;
    return {
        score: block.score,
        band: block.band,
        tierId: block.tierId != null ? block.tierId : null,
        estimatedPercentile: block.estimatedPercentile != null ? block.estimatedPercentile : null,
        confidence: block.confidence || null,
        axes: reSortedAxesForExport(block.axes).map(reAxisExportRow)
    };
}

function reWorkerJsonExport(workerReport) {
    const src = workerReport || {};
    const flatTwqs = src.twqs && src.twqs.flat;
    const recencyTwqs = src.twqs && src.twqs.recency;
    const flatQaqs = src.qaqs && src.qaqs.flat;
    const recencyQaqs = src.qaqs && src.qaqs.recency;

    return {
        workerId: src.workerId,
        name: src.name,
        email: src.email || '',
        window: src.window || {},
        computedAt: src.computedAt || null,
        engineVersion: src.engineVersion || RE_VERSION,
        exportDate: src.exportDate || null,
        weighting: {
            flat: {
                twqs: reScoreBlockExport(flatTwqs),
                qaqs: reScoreBlockExport(flatQaqs),
            },
            recency: {
                twqs: reScoreBlockExport(recencyTwqs),
                qaqs: reScoreBlockExport(recencyQaqs),
            }
        }
    };
}

function reAxisOmitReason(axis) {
    if (!axis || axis.defined !== false) return null;
    switch (axis.id) {
        case 'outcomeQuality':
            return 'No terminal tasks in scope';
        case 'positiveFeedbackRate':
            return 'No human feedback on authored tasks in scope';
        case 'taskRatingQuality':
        case 'nonBottomScoreRate':
            return 'No explicitly scored feedback in scope';
        case 'firstPassAcceptance':
            return 'No authored tasks with human feedback in scope';
        case 'disputeWinRate':
        case 'disputeLossAvoidance':
            return 'No resolved disputes in scope';
        case 'returnEffectiveness':
            return 'No terminal tasks returned by this reviewer in scope';
        case 'returnActionability':
            return 'No return feedback episodes in scope';
        case 'labelDiscrimination':
            return 'Fewer than 10 feedback rows in scope';
        case 'disputeDefense':
            return 'No resolved sole-negative-reviewer disputes in scope';
        case 'feedbackResolution':
            return 'No return episodes by this QA in scope';
        case 'reviewCallAccuracy':
        case 'disputeOutcomes':
            return 'No resolved disputes in scope';
        case 'consistency':
            return 'Fewer than 2 active calendar weeks of activity in scope';
        default:
            return 'Axis omitted';
    }
}

/** Integer in-window observation counts for LLM explain (never weighted mass). */
function reAxisObservedCountsForLlm(axis) {
    if (!axis) return null;
    const raw = axis.raw || {};
    if (raw.observedCounts && typeof raw.observedCounts === 'object') {
        return { ...raw.observedCounts };
    }
    switch (axis.id) {
        case 'outcomeQuality':
            return {
                terminalTasks: raw.terminalTaskCount != null ? raw.terminalTaskCount : null,
                closureOutcomes: raw.closureN != null ? raw.closureN : null,
                closureStatusCounts: raw.closureStatusCounts || null,
            };
        case 'disputeLossAvoidance':
        case 'disputeWinRate':
        case 'disputeDefense':
            return {
                losses: raw.losses != null ? raw.losses : null,
                wins: raw.wins != null ? raw.wins : null,
                resolved: raw.resolved != null ? raw.resolved : null,
            };
        default:
            return null;
    }
}

function reAxisIsNeutralNoEvidence(axis) {
    if (!axis) return false;
    const raw = axis.raw || {};
    if (raw.neutralNoEvidence === true) return true;
    if (axis.id === 'disputeLossAvoidance' || axis.id === 'disputeDefense' || axis.id === 'disputeWinRate') {
        return Number(raw.resolved) === 0;
    }
    return false;
}

function reSampleStatusForVolume(kind, volume) {
    const n = Number(volume) || 0;
    if (kind === 'qaqs') return reQaqsConfidenceBadge(n).tier;
    return reTwqsConfidenceBadge(n).tier;
}

function reAxisRowForLlm(axis) {
    const defined = axis && axis.defined !== false && axis.score != null && Number.isFinite(axis.score);
    const neutralNoEvidence = reAxisIsNeutralNoEvidence(axis);
    const row = {
        id: String((axis && axis.id) || ''),
        label: String((axis && axis.label) || ''),
        weightPct: rePctOneDecimal(axis && axis.baseWeight),
        // Recency-weighted + prior-shrunk axis score (0–100). Not a raw observed ratio.
        axisScorePct: defined ? rePctOneDecimal(axis.score) : null,
        defined,
        neutralNoEvidence,
    };
    if (!defined) {
        row.omittedReason = reAxisOmitReason(axis);
    } else {
        const observedCounts = reAxisObservedCountsForLlm(axis);
        if (observedCounts) row.observedCounts = observedCounts;
    }
    return row;
}

function reExtremeAxesForSlice(axes) {
    const usable = reSortedAxesForExport(axes).filter((axis) => {
        if (!axis || axis.defined === false || axis.score == null || !Number.isFinite(axis.score)) return false;
        if (reAxisIsNeutralNoEvidence(axis)) return false;
        return true;
    });
    if (!usable.length) return { strongestAxis: null, weakestAxis: null };
    let strongest = usable[0];
    let weakest = usable[0];
    for (const axis of usable) {
        if (axis.score > strongest.score) strongest = axis;
        if (axis.score < weakest.score) weakest = axis;
    }
    const toRef = (axis) => ({
        id: String(axis.id || ''),
        axisScorePct: rePctOneDecimal(axis.score),
    });
    if (strongest === weakest) {
        return { strongestAxis: toRef(strongest), weakestAxis: null };
    }
    return { strongestAxis: toRef(strongest), weakestAxis: toRef(weakest) };
}

function reCompactSliceForLlm(slice, kind, overallPercentile) {
    if (!slice) return null;
    const volume = slice.volume != null ? slice.volume : null;
    const estPct = slice.estimatedPercentile != null ? slice.estimatedPercentile : null;
    const overall = overallPercentile != null && Number.isFinite(Number(overallPercentile))
        ? Number(overallPercentile)
        : null;
    const extremes = reExtremeAxesForSlice(slice.axes);
    return {
        key: String(slice.key || ''),
        tier: slice.band || null,
        tierId: slice.tierId != null ? slice.tierId : null,
        estimatedPercentile: estPct,
        volume,
        sampleStatus: reSampleStatusForVolume(kind, volume),
        priorSource: (slice.priorSource && slice.priorSource.source) || null,
        percentileDeltaFromOverall: (estPct != null && overall != null)
            ? Math.round((Number(estPct) - overall) * 10) / 10
            : null,
        strongestAxis: extremes.strongestAxis,
        weakestAxis: extremes.weakestAxis,
    };
}

function reCompactSlicesForLlm(cohortEntry, kind, overallPercentile) {
    if (!cohortEntry || !cohortEntry.channels) return null;
    const dimensions = {};
    for (const dim of ['team', 'env', 'month']) {
        const channel = cohortEntry.channels[dim];
        const slices = (channel && Array.isArray(channel.slices)) ? channel.slices : [];
        if (!slices.length) continue;
        dimensions[dim] = slices
            .map((slice) => reCompactSliceForLlm(slice, kind, overallPercentile))
            .filter(Boolean)
            .sort((a, b) => {
                const volDiff = (Number(b.volume) || 0) - (Number(a.volume) || 0);
                if (volDiff !== 0) return volDiff;
                const deltaDiff = Math.abs(Number(b.percentileDeltaFromOverall) || 0)
                    - Math.abs(Number(a.percentileDeltaFromOverall) || 0);
                if (deltaDiff !== 0) return deltaDiff;
                return String(a.key).localeCompare(String(b.key));
            });
    }
    return Object.keys(dimensions).length ? dimensions : null;
}

/**
 * Card-aligned score block for LLM explain.
 * Headline fields match the cohort-blended card display when a blend exists;
 * axes come from the main (pre-blend) block used for driver explanation.
 */
function reScoreBlockForLlm(mainBlock, kind, cohortEntry) {
    if (!mainBlock || mainBlock.score == null) return null;
    const display = mainBlock.display || {};
    const volume = kind === 'qaqs'
        ? {
            feedbackRows: display.inScopeFeedbackCount != null
                ? display.inScopeFeedbackCount
                : display.feedbackRowCount,
            tenureDays: display.tenureDays != null ? display.tenureDays : null,
        }
        : {
            terminalTasks: display.terminalTaskCount != null ? display.terminalTaskCount : null,
            tenureDays: display.tenureDays != null ? display.tenureDays : null,
        };
    const headline = (cohortEntry && cohortEntry.score != null) ? cohortEntry : mainBlock;
    const overallPct = headline.estimatedPercentile != null
        ? headline.estimatedPercentile
        : mainBlock.estimatedPercentile;
    const axes = reSortedAxesForExport(mainBlock.axes).map(reAxisRowForLlm);
    const out = {
        score: headline.score,
        tier: headline.band || null,
        tierId: headline.tierId != null ? headline.tierId : null,
        estimatedPercentile: overallPct != null ? overallPct : null,
        confidence: (mainBlock.confidence && mainBlock.confidence.label) || null,
        volume,
        // axisScorePct values are recency-weighted (when weighting=recency) and prior-shrunk.
        axisScoreNote: 'axisScorePct is recency-weighted (when weighting is recency) and prior-shrunk; cite observedCounts for event totals, not axisScorePct as a raw ratio.',
        axes,
    };
    const slices = reCompactSlicesForLlm(cohortEntry, kind, overallPct);
    if (slices) out.slices = slices;
    return out;
}

/**
 * Token-lean per-worker payload for LLM explain / "LLM Data" export.
 * Headline matches the card; slices are compact; counts are integers.
 */
function reBuildLlmExplainData(worker, report, weighting) {
    const src = worker || {};
    const weight = (weighting === 'flat' || weighting === 'recency') ? weighting : 'recency';
    const pickBlock = (entry) => {
        if (!entry) return null;
        if (entry[weight]) return entry[weight];
        if (entry.score != null) return entry;
        return null;
    };
    const twqsBlock = pickBlock(src.twqs);
    const qaqsBlock = pickBlock(src.qaqs);
    const cohortEntry = src.cohort && src.cohort[weight] ? src.cohort[weight] : null;
    const out = {
        engineVersion: (report && report.version) || src.engineVersion || RE_VERSION,
        computedAt: (report && report.computedAt) || src.computedAt || null,
        window: (report && report.window) || src.window || {},
        worker: {
            name: src.name || src.workerId || '',
            // workerId intentionally omitted from LLM payload (token lean / privacy)
        },
        weighting: weight,
        scores: {},
    };
    const twqs = reScoreBlockForLlm(twqsBlock, 'twqs', cohortEntry && cohortEntry.twqs);
    const qaqs = reScoreBlockForLlm(qaqsBlock, 'qaqs', cohortEntry && cohortEntry.qaqs);
    if (twqs) out.scores.twqs = twqs;
    if (qaqs) out.scores.qaqs = qaqs;
    return out;
}

function reFieldAuditRow(entry, task, workerId) {
    const ts = reFeedbackTimestamp(entry);
    const allFb = reHumanFeedbackChronological(task);
    const chronoIdx = allFb.findIndex((e) => String(e.id) === String(entry.id));
    return {
        feedbackId: String(entry.id || ''),
        taskId: String((task && task.id) || ''),
        feedbackAt: ts || null,
        created_at_legacy: String((entry && entry.created_at) || '') || null,
        reviewerId: String((entry.reviewer && entry.reviewer.id) || ''),
        returnType: (() => {
            if (entry.isPositive) return 'accepted';
            if (entry.isEscalated) return 'escalated';
            if (entry.isFlaggedAsBugged) return 'bugged';
            return 'returned';
        })(),
        chronologicalIndex: chronoIdx,
        totalHumanFeedbackOnTask: allFb.length,
        isFirstQaOnTask: chronoIdx === 0,
        timestampResolvable: Boolean(ts)
    };
}

// Collects all QA feedback rows for a reviewer across hydrated items, deduped by feedback ID.
// Excludes system/verifier entries and self-reviews (where reviewer === task author).
function reCollectQaqsFeedbackRows(workerId, hydratedItems) {
    const feedbackById = new Map();
    for (const item of hydratedItems) {
        const task = item.task;
        if (!task) continue;
        const authorId = task.author && task.author.id;
        for (const entry of task.allFeedback || []) {
            if (!reIsHumanFeedback(entry)) continue;
            const reviewerId = entry.reviewer && entry.reviewer.id;
            if (!reIdsEqual(reviewerId, workerId)) continue;
            if (authorId && reIdsEqual(reviewerId, authorId)) continue;
            feedbackById.set(String(entry.id), { entry, task, item });
        }
    }
    return [...feedbackById.values()];
}

// ---------------------------------------------------------------------------
// RatingEngine
// ---------------------------------------------------------------------------

const RatingEngine = {
    VERSION: RE_VERSION,
    ordinalSuffix: reOrdinalSuffix,
    formatPercentile: reFormatPercentile,
    populationTier: rePopulationTier,
    TIER_DEFS: RE_TIER_DEFS,
    TIER_THRESHOLDS: RE_TIER_THRESHOLDS,
    TIER_TOP_PEG: RE_TIER_TOP_PEG,
    setCohortBaselines(baselines) {
        Context.ratingCohortBaselines = reValidateRatingBaselines(baselines) || baselines || {};
    },

    getBaselinePolicy() {
        return { ...RE_BASELINE_POLICY };
    },

    /** Estimated percentile (integer, margin-clamped) for a composite score. */
    estimatePercentile(score, kind, weighting) {
        const params = (RE_PERCENTILE_PARAMS[kind] && RE_PERCENTILE_PARAMS[kind][weighting]) || null;
        return reEstimatePercentile(score, params);
    },

    /** Token-lean explain payload for cards / LLM Data export. */
    buildLlmExplainData(worker, report, weighting) {
        return reBuildLlmExplainData(worker, report, weighting);
    },

    compute(options) {
        const opts = options || {};
        const cachedItems = opts.cachedItems || [];
        const committed = opts.committed || {};
        const nowMs = Number.isFinite(opts.nowMs) ? opts.nowMs : Date.now();
        const authorIds = [...new Set((committed.authorIds || []).filter(Boolean))];
        const hydratedItems = cachedItems.filter((item) => item && item.hydrated === true);
        const unhydratedCount = cachedItems.length - hydratedItems.length;
        const window = reResolveWindow(committed);
        const profiles = opts.workerProfiles || {};
        const baselines = reLoadRatingBaselines(opts);
        if (!baselines) {
            Logger.warn('rating-engine: baselines unavailable — unlock Ops secrets with ratingBaselines');
            return {
                version: RE_VERSION,
                computedAt: new Date(nowMs).toISOString(),
                window,
                workers: [],
                error: {
                    code: 'baselinesUnavailable',
                    message: 'Rating baselines are unavailable. Unlock the Ops dashboard so encrypted priors can load, then retry.'
                },
                meta: {
                    hydratedCount: hydratedItems.length,
                    unhydratedCount,
                    totalCount: cachedItems.length,
                    workerCount: 0,
                    baselinesReady: false
                }
            };
        }

        const globalTwCohort = reCohortPack('twqs', reResolveRolePriors(baselines, 'twqs', null, null));
        const globalQaCohort = reCohortPack('qaqs', reResolveRolePriors(baselines, 'qaqs', null, null));

        const workers = authorIds.map((workerId) => {
            const profile = profiles[workerId] || {};

            const flatTwqs = this._computeTwqs(workerId, hydratedItems, 'flat', window, nowMs, globalTwCohort);
            const recencyTwqs = this._computeTwqs(workerId, hydratedItems, 'recency', window, nowMs, globalTwCohort);
            const flatQaqs = this._computeQaqs(workerId, hydratedItems, 'flat', window, nowMs, globalQaCohort);
            const recencyQaqs = this._computeQaqs(workerId, hydratedItems, 'recency', window, nowMs, globalQaCohort);

            const cohort = this._computeCohortBlend(
                workerId, hydratedItems, window, nowMs, baselines,
                { flatTwqs, recencyTwqs, flatQaqs, recencyQaqs }
            );

            return {
                workerId,
                name: profile.name || profile.label || workerId,
                email: profile.email || '',
                window,
                twqs: { flat: flatTwqs, recency: recencyTwqs },
                qaqs: { flat: flatQaqs, recency: recencyQaqs },
                cohort,
                meta: { hydratedCount: hydratedItems.length, unhydratedCount }
            };
        });

        return {
            version: RE_VERSION,
            computedAt: new Date(nowMs).toISOString(),
            window,
            workers,
            meta: {
                hydratedCount: hydratedItems.length,
                unhydratedCount,
                totalCount: cachedItems.length,
                workerCount: workers.length,
                baselinesReady: true,
                baselinesGeneratedAt: baselines.generatedAt
            }
        };
    },

    _computeCohortBlend(workerId, hydratedItems, window, nowMs, baselines, main) {
        const output = { flat: {}, recency: {} };
        for (const weighting of ['flat', 'recency']) {
            const twSlices = { team: [], env: [], month: [] };
            const qaSlices = { team: [], env: [], month: [] };
            for (const dimension of ['team', 'env', 'month']) {
                const keyedItems = new Map();
                for (const item of hydratedItems) {
                    const key = reCohortKey(item.task, dimension);
                    if (!key) continue;
                    if (!keyedItems.has(key)) keyedItems.set(key, []);
                    keyedItems.get(key).push(item);
                }
                for (const [key, sliceItems] of keyedItems) {
                    const twResolved = reResolveRolePriors(baselines, 'twqs', dimension, key);
                    const qaResolved = reResolveRolePriors(baselines, 'qaqs', dimension, key);
                    const twCohort = reCohortPack('twqs', twResolved);
                    const qaCohort = reCohortPack('qaqs', qaResolved);
                    const twBlock = this._computeTwqs(workerId, sliceItems, weighting, window, nowMs, twCohort);
                    const qaBlock = this._computeQaqs(workerId, sliceItems, weighting, window, nowMs, qaCohort);
                    if (twBlock) twSlices[dimension].push({
                        key,
                        block: twBlock,
                        volume: (twBlock.display && twBlock.display.terminalTaskCount) || 0,
                        priorSource: twCohort.priorSource,
                    });
                    if (qaBlock) qaSlices[dimension].push({
                        key,
                        block: qaBlock,
                        volume: (qaBlock.display && qaBlock.display.inScopeFeedbackCount) || 0,
                        priorSource: qaCohort.priorSource,
                    });
                }
            }
            const twqs = reBlendCohortBlocks(main[weighting + 'Twqs'], twSlices, reTwqsConfidenceBadge, 'twqs', weighting);
            const qaqs = reBlendCohortBlocks(main[weighting + 'Qaqs'], qaSlices, reQaqsConfidenceBadge, 'qaqs', weighting);
            output[weighting] = { twqs, qaqs };
        }
        return output;
    },

    _writerItems(workerId, hydratedItems) {
        return hydratedItems.filter((item) => {
            const authorId = item.task && item.task.author && item.task.author.id;
            return reIdsEqual(authorId, workerId);
        });
    },

    // Computes WPS-aligned TWQS (five-axis, rank-workers.py v1.2 formula).
    _computeTwqs(workerId, hydratedItems, weighting, window, nowMs, cohort) {
        const writerItems = this._writerItems(workerId, hydratedItems);
        if (writerItems.length === 0) return null;

        // Outcome Quality: terminal tasks, recency-weighted quality sum
        // A = status-weighted (includes bugged); B = excludes bugged statuses entirely
        let oqKsumA = 0, oqNsumA = 0, oqTerminalCount = 0;
        let oqKsumB = 0, oqNsumB = 0;
        // Positive Feedback Rate: all human feedback, recency-weighted
        let pfKsum = 0, pfNsum = 0;
        let pfPositiveCount = 0, pfTotalCount = 0;
        // Task Rating Quality: explicitly scored feedback only (qualityRatingRaw), ordinal 0/0.5/1
        let trqKsum = 0, trqNsum = 0;
        let trqBottomW = 0, trqAverageW = 0, trqTopW = 0;
        let trqBottomCount = 0, trqAverageCount = 0, trqTopCount = 0, trqScoredCount = 0;
        // First-Pass Acceptance: one per task (earliest in-scope feedback), recency-weighted
        let fpKsum = 0, fpNsum = 0;
        let fpAcceptedCount = 0, fpEligibleCount = 0;
        const fpSeenTasks = new Set();
        // Closure outcome: flat-only production/discarded/dismissed path.
        let oqClosureKsum = 0, oqClosureN = 0;
        const oqClosureStatuses = { production: 0, discarded: 0, dismissed: 0 };
        // Dispute Loss Avoidance: only rejected writer disputes are adverse.
        let dwLosses = 0, dwResolved = 0, dwWins = 0;

        let earliestTs = null;

        for (const item of writerItems) {
            const task = item.task;
            if (!task) continue;
            const taskCreatedAt = reTaskTimestamp(task, item);

            const tts = Date.parse(taskCreatedAt);
            if (!Number.isNaN(tts) && (earliestTs == null || tts < earliestTs)) earliestTs = tts;

            // Outcome Quality: terminal tasks only
            const terminalQuality = reTaskTerminalQuality(task, nowMs);
            const taskInScope = reEventWeight(taskCreatedAt, 'flat', nowMs, window) > 0;
            const taskStatus = String((task && task.status) || '').toLowerCase().trim();

            if (terminalQuality !== null && taskInScope) {
                oqTerminalCount += 1;
                const taskW = reEventWeight(taskCreatedAt, weighting, nowMs, window);
                if (taskW > 0) {
                    oqKsumA += terminalQuality * taskW;
                    oqNsumA += taskW;
                    if (taskStatus !== 'bugged') {
                        oqKsumB += terminalQuality * taskW;
                        oqNsumB += taskW;
                    }
                }
            }

            // Intentionally flat in both variants; window filtering still applies.
            const closureQuality = reTaskClosureQuality(task);
            if (closureQuality !== null && taskInScope) {
                oqClosureKsum += closureQuality;
                oqClosureN += 1;
                oqClosureStatuses[taskStatus] += 1;
            }

            // Human feedback axes: positive rate, task rating quality, first-pass
            const taskId = String(task.id || '');
            const allHumanFb = reHumanFeedbackChronological(task);

            for (const entry of allHumanFb) {
                const fbAt = reFeedbackTimestamp(entry);
                const fw = reEventWeight(fbAt, weighting, nowMs, window);
                if (fw <= 0) continue;

                // Positive Feedback Rate
                pfNsum += fw;
                pfTotalCount += 1;
                if (entry.isPositive) {
                    pfKsum += fw;
                    pfPositiveCount += 1;
                }

                // Task Rating Quality (explicit score labels only via qualityRatingRaw)
                const rawRating = entry.display && entry.display.qualityRatingRaw;
                const ratingValue = reTaskRatingQualityValue(rawRating);
                if (ratingValue != null) {
                    trqNsum += fw;
                    trqKsum += ratingValue * fw;
                    trqScoredCount += 1;
                    if (rawRating === 'Bottom 10%') {
                        trqBottomW += fw;
                        trqBottomCount += 1;
                    } else if (rawRating === 'Average') {
                        trqAverageW += fw;
                        trqAverageCount += 1;
                    } else if (rawRating === 'Top 10%') {
                        trqTopW += fw;
                        trqTopCount += 1;
                    }
                }

                // First-Pass Acceptance: first in-scope feedback per task
                if (taskId && !fpSeenTasks.has(taskId)) {
                    fpSeenTasks.add(taskId);
                    fpNsum += fw;
                    fpEligibleCount += 1;
                    if (entry.isPositive) {
                        fpKsum += fw;
                        fpAcceptedCount += 1;
                    }
                }
            }

            // Dispute Loss Avoidance: wins are informational only.
            for (const dispute of item.disputes || []) {
                if (!dispute.resolutionAt) continue;
                if (reEventWeight(dispute.resolutionAt, 'flat', nowMs, window) <= 0) continue;
                dwResolved += 1;
                if (dispute.isRejected) dwLosses += 1;
                if (dispute.isApproved) dwWins += 1;
            }
        }

        const priors = reCohortPriors('twqs', cohort);
        if (!priors) return null;
        const oqScoreA = reShrunkRate(oqKsumA, oqNsumA, RE_TWQS_C.outcomeQuality, priors.outcomeQuality);
        const oqScoreB = oqNsumB > 0
            ? reShrunkRate(oqKsumB, oqNsumB, RE_TWQS_C.outcomeQuality, priors.outcomeQuality)
            : null;
        const oqCurrentScore = oqScoreB != null
            ? (0.5 * oqScoreA + 0.5 * oqScoreB)
            : oqScoreA;
        const oqClosureScore = oqClosureN > 0
            ? reShrunkRate(oqClosureKsum, oqClosureN, RE_TWQS_C.outcomeQuality, priors.outcomeQuality)
            : null;
        const oqScore = oqClosureScore != null
            ? (0.5 * oqCurrentScore + 0.5 * oqClosureScore)
            : oqCurrentScore;
        const pfScore = reShrunkRate(pfKsum, pfNsum, RE_TWQS_C.positiveFeedbackRate, priors.positiveFeedbackRate);
        const trqScore = reShrunkRate(trqKsum, trqNsum, RE_TWQS_C.taskRatingQuality, priors.taskRatingQuality);
        const fpScore = reShrunkRate(fpKsum, fpNsum, RE_TWQS_C.firstPassAcceptance, priors.firstPassAcceptance);
        const dwScore = reShrunkRate(0, dwLosses, RE_TWQS_C.disputeLossAvoidance, priors.disputeLossAvoidance);

        const axes = RE_TWQS_AXES.map((def) => {
            let score = null;
            let defined = true;
            let raw = {};
            switch (def.id) {
                case 'outcomeQuality':
                    score = oqScore;
                    raw = {
                        terminalTaskCount: oqTerminalCount,
                        weightedQualitySum: Math.round(oqKsumA * 1000) / 1000,
                        weightedN: Math.round(oqNsumA * 1000) / 1000,
                        statusWeightedScore: Math.round(oqScoreA * 1000) / 1000,
                        ignoreBuggedScore: oqScoreB != null ? Math.round(oqScoreB * 1000) / 1000 : null,
                        ignoreBuggedWeightedN: Math.round(oqNsumB * 1000) / 1000,
                        currentScore: Math.round(oqCurrentScore * 1000) / 1000,
                        closureScore: oqClosureScore != null ? Math.round(oqClosureScore * 1000) / 1000 : null,
                        closureN: oqClosureN,
                        closureStatusCounts: oqClosureStatuses,
                        blend: oqClosureScore != null
                            ? '0.5*currentOutcome + 0.5*closureOutcome'
                            : 'currentOutcome (no closure outcomes)',
                        observedCounts: {
                            terminalTasks: oqTerminalCount,
                            closureOutcomes: oqClosureN,
                            closureStatusCounts: oqClosureStatuses,
                        },
                    };
                    break;
                case 'positiveFeedbackRate':
                    score = pfScore;
                    raw = {
                        weightedPositive: Math.round(pfKsum * 1000) / 1000,
                        weightedTotal: Math.round(pfNsum * 1000) / 1000,
                        observedCounts: {
                            positive: pfPositiveCount,
                            total: pfTotalCount,
                        },
                    };
                    break;
                case 'taskRatingQuality':
                    score = trqScore;
                    raw = {
                        weightedQualityPoints: Math.round(trqKsum * 1000) / 1000,
                        weightedScored: Math.round(trqNsum * 1000) / 1000,
                        weightedBottom: Math.round(trqBottomW * 1000) / 1000,
                        weightedAverage: Math.round(trqAverageW * 1000) / 1000,
                        weightedTop: Math.round(trqTopW * 1000) / 1000,
                        // Aliases used by the stats-pane breakdown helper.
                        qualityPoints: Math.round(trqKsum * 1000) / 1000,
                        total: Math.round(trqNsum * 1000) / 1000,
                        observedCounts: {
                            bottom: trqBottomCount,
                            average: trqAverageCount,
                            top: trqTopCount,
                            scored: trqScoredCount,
                        },
                    };
                    break;
                case 'firstPassAcceptance':
                    score = fpScore;
                    raw = {
                        weightedAccepted: Math.round(fpKsum * 1000) / 1000,
                        weightedEligible: Math.round(fpNsum * 1000) / 1000,
                        taskCount: fpSeenTasks.size,
                        observedCounts: {
                            accepted: fpAcceptedCount,
                            eligible: fpEligibleCount,
                            tasks: fpSeenTasks.size,
                        },
                    };
                    break;
                case 'disputeLossAvoidance':
                    score = dwScore;
                    raw = {
                        losses: dwLosses,
                        wins: dwWins,
                        resolved: dwResolved,
                        observedCounts: {
                            losses: dwLosses,
                            wins: dwWins,
                            resolved: dwResolved,
                        },
                        neutralNoEvidence: dwResolved === 0,
                    };
                    break;
                default:
                    break;
            }
            return { id: def.id, label: def.label, baseWeight: def.weight, score, defined, raw };
        });

        const combined = reCombineAxes(axes);
        const params = RE_PERCENTILE_PARAMS.twqs[weighting] || {};
        combined.estimatedPercentile = reEstimatePercentile(combined.score, params);
        combined.confidence = reTwqsConfidenceBadge(oqTerminalCount);
        combined.priorSource = (cohort && cohort.priorSource) || null;
        combined.display = {
            writerItemCount: writerItems.length,
            terminalTaskCount: oqTerminalCount,
            tenureDays: earliestTs != null
                ? Math.max(0, Math.round((nowMs - earliestTs) / RE_MS_PER_DAY))
                : null
        };
        reAnnotatePopulationTier(combined, 'twqs', weighting);
        combined.raw = {
            oqKsum: Math.round(oqKsumA * 1000) / 1000,
            oqNsum: Math.round(oqNsumA * 1000) / 1000,
            pfKsum: Math.round(pfKsum * 1000) / 1000,
            pfNsum: Math.round(pfNsum * 1000) / 1000,
            trqKsum: Math.round(trqKsum * 1000) / 1000,
            trqNsum: Math.round(trqNsum * 1000) / 1000,
            fpKsum: Math.round(fpKsum * 1000) / 1000,
            fpNsum: Math.round(fpNsum * 1000) / 1000,
            oqClosureKsum: Math.round(oqClosureKsum * 1000) / 1000,
            oqClosureN,
            dwLosses,
            dwWins,
            dwResolved
        };

        return combined;
    },

    // Computes QPS-aligned QAQS (four-axis, rank-qa.py v2.1 formula).
    _computeQaqs(workerId, hydratedItems, weighting, window, nowMs, cohort) {
        const feedbackRows = reCollectQaqsFeedbackRows(workerId, hydratedItems);
        if (feedbackRows.length === 0) return null;

        // Return Effectiveness: neg feedback on terminal tasks → production
        let reKsum = 0, reNsum = 0;
        let reEffectiveCount = 0, reEligibleCount = 0;
        // Return Actionability: neg on production → next human row positive?
        let raKsum = 0, raNsum = 0;
        let raActionableCount = 0, raEligibleCount = 0;
        // Label Discrimination: explicit score labels (qualityRatingRaw)
        let ldKsum = 0, ldNsum = 0;
        let ldNonAvgCount = 0, ldScoredCount = 0;
        // Dispute Loss Avoidance: sole-neg attribution, unweighted.
        let ddLosses = 0, ddDenom = 0, ddWins = 0;

        let inScopeFeedbackCount = 0;
        let earliestTs = null;

        for (const { entry, task } of feedbackRows) {
            const fbAt = reFeedbackTimestamp(entry);
            const inScope = reEventWeight(fbAt, 'flat', nowMs, window) > 0;
            if (!inScope) continue;

            inScopeFeedbackCount += 1;
            const ts = Date.parse(fbAt);
            if (!Number.isNaN(ts) && (earliestTs == null || ts < earliestTs)) earliestTs = ts;

            const fw = reEventWeight(fbAt, weighting, nowMs, window);
            const taskStatus = String((task && task.status) || '').toLowerCase().trim();

            // Return Effectiveness: neg feedback on terminal tasks
            if (!entry.isPositive) {
                const termQ = reTaskTerminalQuality(task, nowMs);
                if (termQ !== null) {
                    reNsum += fw;
                    reEligibleCount += 1;
                    if (taskStatus === 'production') {
                        reKsum += fw;
                        reEffectiveCount += 1;
                    }
                }
            }

            // Return Actionability: neg on production → next human row positive?
            if (!entry.isPositive && taskStatus === 'production') {
                raNsum += fw;
                raEligibleCount += 1;
                const allHuman = reHumanFeedbackChronological(task);
                const idx = allHuman.findIndex((e) => reIdsEqual(e.id, entry.id));
                if (idx >= 0 && idx + 1 < allHuman.length && allHuman[idx + 1].isPositive) {
                    raKsum += fw;
                    raActionableCount += 1;
                }
            }

            // Label Discrimination: explicit score labels only (qualityRatingRaw)
            const rawRating = entry.display && entry.display.qualityRatingRaw;
            if (rawRating === 'Average' || rawRating === 'Top 10%' || rawRating === 'Bottom 10%') {
                ldNsum += fw;
                ldScoredCount += 1;
                if (rawRating !== 'Average') {
                    ldKsum += fw;
                    ldNonAvgCount += 1;
                }
            }
        }

        // Dispute Defense: sole-neg reviewer attribution (mirrors fill_dispute_defense).
        // A dispute is attributed to workerId only if workerId is the sole distinct
        // negative reviewer on that task. Counts are unweighted.
        for (const item of hydratedItems) {
            const task = item.task;
            if (!task) continue;

            // Collect distinct neg reviewer IDs on this task
            const negReviewerIds = new Set();
            for (const entry of task.allFeedback || []) {
                if (!reIsHumanFeedback(entry)) continue;
                if (!entry.isPositive) {
                    const rid = entry.reviewer && entry.reviewer.id;
                    if (rid) negReviewerIds.add(String(rid));
                }
            }

            if (negReviewerIds.size !== 1) continue;
            const soleNegId = [...negReviewerIds][0];
            if (!reIdsEqual(soleNegId, workerId)) continue;

            for (const dispute of item.disputes || []) {
                if (!dispute.resolutionAt) continue;
                if (reEventWeight(dispute.resolutionAt, 'flat', nowMs, window) <= 0) continue;
                ddDenom += 1;
                if (dispute.isApproved) ddLosses += 1;
                if (dispute.isRejected) ddWins += 1;
            }
        }

        // Shrunk scores.
        // returnEffectiveness stays defined (prior when n=0).
        // labelDiscrimination requires a minimum sample (else omitted; weight renormalizes).
        const priors = reCohortPriors('qaqs', cohort);
        if (!priors) return null;
        const reScore = reShrunkRate(reKsum, reNsum, RE_QAQS_RET_EFF_C, priors.returnEffectiveness);
        const raDefined = raNsum > 0;
        const raScore = raDefined ? reShrunkRate(raKsum, raNsum, RE_QAQS_RET_ACT_C, priors.returnActionability) : null;
        const ldDefined = inScopeFeedbackCount >= RE_QAQS_LABEL_DISC_MIN_N;
        const ldScore = ldDefined
            ? reShrunkRate(ldKsum, ldNsum, RE_QAQS_LABEL_DISC_C, priors.labelDiscrimination)
            : null;
        const ddScore = reShrunkRate(0, ddLosses, RE_QAQS_DISPUTE_DEF_C, priors.disputeDefense);

        const axes = RE_QAQS_AXES.map((def) => {
            let score = null;
            let defined = true;
            let raw = {};
            switch (def.id) {
                case 'returnEffectiveness':
                    score = reScore;
                    raw = {
                        weightedResolved: Math.round(reKsum * 1000) / 1000,
                        weightedNegTerminal: Math.round(reNsum * 1000) / 1000,
                        observedCounts: {
                            effective: reEffectiveCount,
                            eligible: reEligibleCount,
                        },
                    };
                    break;
                case 'returnActionability':
                    defined = raDefined;
                    score = raScore;
                    raw = {
                        weightedOneRound: Math.round(raKsum * 1000) / 1000,
                        weightedNegProduction: Math.round(raNsum * 1000) / 1000,
                        observedCounts: {
                            actionable: raActionableCount,
                            eligible: raEligibleCount,
                        },
                    };
                    break;
                case 'disputeDefense':
                    score = ddScore;
                    raw = {
                        losses: ddLosses,
                        wins: ddWins,
                        resolved: ddDenom,
                        observedCounts: {
                            losses: ddLosses,
                            wins: ddWins,
                            resolved: ddDenom,
                        },
                        neutralNoEvidence: ddDenom === 0,
                    };
                    break;
                case 'labelDiscrimination':
                    defined = ldDefined;
                    score = ldScore;
                    raw = {
                        weightedNonStd: Math.round(ldKsum * 1000) / 1000,
                        weightedScored: Math.round(ldNsum * 1000) / 1000,
                        sampleN: inScopeFeedbackCount,
                        minSampleN: RE_QAQS_LABEL_DISC_MIN_N,
                        observedCounts: {
                            nonAverageLabels: ldNonAvgCount,
                            scoredLabels: ldScoredCount,
                            sampleN: inScopeFeedbackCount,
                        },
                    };
                    break;
                default:
                    break;
            }
            return { id: def.id, label: def.label, baseWeight: def.weight, score, defined, raw };
        });

        const combined = reCombineAxes(axes);
        const params = RE_PERCENTILE_PARAMS.qaqs[weighting] || {};
        combined.estimatedPercentile = reEstimatePercentile(combined.score, params);
        combined.confidence = reQaqsConfidenceBadge(inScopeFeedbackCount);
        combined.priorSource = (cohort && cohort.priorSource) || null;
        combined.display = {
            feedbackRowCount: feedbackRows.length,
            inScopeFeedbackCount,
            tenureDays: earliestTs != null
                ? Math.max(0, Math.round((nowMs - earliestTs) / RE_MS_PER_DAY))
                : null,
            negOnTerminalCount: Math.round(reNsum),
            negOnProductionCount: Math.round(raNsum)
        };
        reAnnotatePopulationTier(combined, 'qaqs', weighting);
        combined.raw = {
            reKsum: Math.round(reKsum * 1000) / 1000,
            reNsum: Math.round(reNsum * 1000) / 1000,
            raKsum: Math.round(raKsum * 1000) / 1000,
            raNsum: Math.round(raNsum * 1000) / 1000,
            ldKsum: Math.round(ldKsum * 1000) / 1000,
            ldNsum: Math.round(ldNsum * 1000) / 1000,
            ddLosses,
            ddWins,
            ddDenom
        };

        return combined;
    },

    buildDiagnosticsReport(workerReport, context) {
        const ctx = context || {};
        const cachedItems = (ctx.cachedItems || []).filter((item) => item && item.hydrated === true);
        const workerId = workerReport.workerId;
        const window = workerReport.window || reResolveWindow(ctx.committed);
        const nowMs = Date.parse(workerReport.computedAt) || Date.now();

        const feedbackRows = reCollectQaqsFeedbackRows(workerId, cachedItems);
        let feedbackRowsBeforeDedupe = 0;
        for (const item of cachedItems) {
            const task = item.task;
            if (!task) continue;
            for (const entry of task.allFeedback || []) {
                if (!reIsHumanFeedback(entry)) continue;
                if (!reIdsEqual(entry.reviewer && entry.reviewer.id, workerId)) continue;
                feedbackRowsBeforeDedupe += 1;
            }
        }

        const returnTypeCounts = { accepted: 0, returned: 0, escalated: 0, bugged: 0, other: 0 };
        let timestampMissingCount = 0;
        let inScopeCount = 0;
        const fieldAuditSamples = [];
        const seenAuditIds = new Set();

        for (const { entry, task } of feedbackRows) {
            const ts = reFeedbackTimestamp(entry);
            if (!ts) timestampMissingCount += 1;
            if (reEventWeight(ts, 'flat', nowMs, window) > 0) inScopeCount += 1;

            if (entry.isPositive) returnTypeCounts.accepted += 1;
            else if (entry.isEscalated) returnTypeCounts.escalated += 1;
            else if (entry.isFlaggedAsBugged) returnTypeCounts.bugged += 1;
            else if (!entry.isSystemFeedback) returnTypeCounts.returned += 1;
            else returnTypeCounts.other += 1;

            const audit = reFieldAuditRow(entry, task, workerId);
            const isAnomalous = !audit.timestampResolvable;
            if (fieldAuditSamples.length < RE_DIAG_SAMPLE_ROWS || isAnomalous) {
                if (!seenAuditIds.has(audit.feedbackId)) {
                    seenAuditIds.add(audit.feedbackId);
                    fieldAuditSamples.push(audit);
                }
            }
        }

        const feedbackIds = new Set(feedbackRows.map((r) => String(r.entry.id)));
        const disputesInScope = [];

        for (const item of cachedItems) {
            const task = item.task;
            if (!task) continue;
            const remap = task.systemFeedbackIdRemap || {};
            const hasQaOnTask = (task.allFeedback || []).some((e) => {
                return reIsHumanFeedback(e) && reIdsEqual(e.reviewer && e.reviewer.id, workerId);
            });
            if (!hasQaOnTask) continue;

            for (const dispute of item.disputes || []) {
                const rawFid = String(dispute.feedbackId || '').trim();
                const resolvedFid = reResolveFeedbackId(dispute.feedbackId, remap);
                disputesInScope.push({
                    disputeId: String(dispute.id || ''),
                    feedbackId: rawFid,
                    resolvedFeedbackId: resolvedFid,
                    matchesWorkerFeedback: Boolean(resolvedFid && feedbackIds.has(resolvedFid)),
                    status: dispute.status || null,
                    resolutionAt: dispute.resolutionAt || null,
                    isRejected: Boolean(dispute.isRejected),
                    isApproved: Boolean(dispute.isApproved)
                });
            }
        }

        const recencyTwqs = workerReport.twqs && workerReport.twqs.recency;
        const recencyQaqs = workerReport.qaqs && workerReport.qaqs.recency;

        const qaqsAxisDebug = ((recencyQaqs && recencyQaqs.axes) || []).map((p) => ({
            id: p.id, label: p.label, defined: p.defined !== false,
            whyOmitted: reAxisOmitReason(p), score: p.score, raw: p.raw || {}
        }));

        const twqsAxisDebug = ((recencyTwqs && recencyTwqs.axes) || []).map((p) => ({
            id: p.id, label: p.label, defined: p.defined !== false,
            whyOmitted: reAxisOmitReason(p), score: p.score, raw: p.raw || {}
        }));

        return {
            meta: {
                engineVersion: RE_VERSION,
                computedAt: workerReport.computedAt || new Date(nowMs).toISOString(),
                workerId,
                name: workerReport.name || workerId,
                email: workerReport.email || '',
                window,
                hydratedCount: cachedItems.length,
                unhydratedCount: ctx.unhydratedCount != null
                    ? ctx.unhydratedCount
                    : Math.max(0, (ctx.cachedItems || []).length - cachedItems.length)
            },
            warnings: ctx.warnings || [],
            fieldAudit: {
                accessorNotes: {
                    feedbackTimestamp: 'Uses entry.feedbackAt with fallback to entry.created_at',
                    taskTimestamp: 'Uses task.createdAt with fallback to item.sortAt',
                    disputeFeedbackId: 'Applies task.systemFeedbackIdRemap before matching QA feedback rows'
                },
                samples: fieldAuditSamples
            },
            qaqs: {
                feedbackRowsBeforeDedupe,
                feedbackRowsDeduped: feedbackRows.length,
                inScopeCount,
                timestampMissingCount,
                returnTypeCounts,
                disputesInScope,
                axisDebug: qaqsAxisDebug
            },
            twqs: recencyTwqs ? {
                writerItemCount: this._writerItems(workerId, cachedItems).length,
                axisDebug: twqsAxisDebug
            } : null,
            scores: {
                flat: {
                    twqs: workerReport.twqs && workerReport.twqs.flat
                        ? { score: workerReport.twqs.flat.score, band: workerReport.twqs.flat.band } : null,
                    qaqs: workerReport.qaqs && workerReport.qaqs.flat
                        ? { score: workerReport.qaqs.flat.score, band: workerReport.qaqs.flat.band } : null
                },
                recency: {
                    twqs: recencyTwqs ? { score: recencyTwqs.score, band: recencyTwqs.band } : null,
                    qaqs: recencyQaqs ? { score: recencyQaqs.score, band: recencyQaqs.band } : null
                }
            }
        };
    },

    buildExportFilename(workerReport, scoreType, ext) {
        const name = reSlugify(workerReport.name || workerReport.workerId);
        const date = (workerReport.exportDate || new Date().toISOString().slice(0, 10));
        if (scoreType === 'llm-data') {
            return 'llm-data-' + reWorkerExportIdentity(workerReport) + '-'
                + reExportTimestampSlug(workerReport.exportedAt) + '.' + ext;
        }
        return 'rating-' + name + '-' + scoreType + '-' + date + '.' + ext;
    },

    buildDiagnosticsFilename(workerReport) {
        return 'diagnostic-' + reWorkerExportIdentity(workerReport) + '-'
            + reExportTimestampSlug(workerReport.exportedAt) + '.json';
    },

    serializeJson(report) {
        return JSON.stringify(reWorkerJsonExport(report), null, 2);
    },

    serializeDiagnosticsJson(report) {
        return JSON.stringify(report, null, 2);
    },

    serializeMarkdown(workerReport) {
        const lines = [];
        lines.push('# Worker Rating Report');
        lines.push('');
        lines.push('- **Worker:** ' + (workerReport.name || workerReport.workerId));
        if (workerReport.email) lines.push('- **Email:** ' + workerReport.email);
        lines.push('- **Computed:** ' + (workerReport.computedAt || new Date().toISOString()));
        const win = workerReport.window || {};
        if (win.afterLocal || win.beforeLocal) {
            lines.push('- **Window:** ' + (win.afterLocal || '…') + ' → ' + (win.beforeLocal || '…'));
        } else {
            lines.push('- **Window:** All time');
        }
        lines.push('- **Engine version:** ' + (workerReport.engineVersion || RE_VERSION));
        lines.push('');

        const renderScoreBlock = (title, block) => {
            if (!block || block.score == null) return;
            lines.push('## ' + title);
            lines.push('');
            let scoreStr = String(Math.round(block.score)) + ' / 100 · ' + block.band;
            if (block.estimatedPercentile != null) {
                scoreStr += ' · ~' + reFormatPercentile(block.estimatedPercentile) + ' percentile (estimated)';
            }
            lines.push('**Score:** ' + scoreStr);
            lines.push('**Confidence:** ' + (block.confidence && block.confidence.label));
            lines.push('');
            lines.push('| Axis | Sub-score | Weight |');
            lines.push('| --- | ---: | ---: |');
            for (const p of block.axes || []) {
                const wt = p.effectiveWeight != null
                    ? (Math.round(p.effectiveWeight * 1000) / 10) + '%'
                    : '—';
                const sc = p.defined === false ? 'omitted' : reFormatPct(p.score || 0);
                lines.push('| ' + p.label + ' | ' + sc + ' | ' + wt + ' |');
            }
            lines.push('');
        };

        for (const weighting of ['recency', 'flat']) {
            const label = weighting === 'recency' ? 'Recency-weighted (30-day half-life)' : 'Flat-weighted';
            const twqs = workerReport.twqs && workerReport.twqs[weighting];
            const qaqs = workerReport.qaqs && workerReport.qaqs[weighting];

            if (twqs || qaqs) {
                lines.push('---');
                lines.push('');
                lines.push('# ' + label);
                lines.push('');
                renderScoreBlock('Task Writer Quality Score (TWQS)', twqs);
                renderScoreBlock('QA Quality Score (QAQS)', qaqs);
            }
        }

        if (workerReport.meta) {
            lines.push('## Meta');
            lines.push('- Hydrated items used: ' + workerReport.meta.hydratedCount);
            lines.push('- Unhydrated items excluded: ' + workerReport.meta.unhydratedCount);
        }

        return lines.join('\n');
    }
};

const plugin = {
    id: 'rating-engine',
    name: 'Rating Engine',
    description: 'TWQS and QAQS computation for Worker Output Search ratings (WPS/QPS aligned)',
    _version: '11.0',
    phase: 'core',
    enabledByDefault: true,
    initialState: { registered: false },

    init(state) {
        if (state && state.registered) {
            Logger.debug('rating-engine: already registered — skipping re-init');
            return;
        }
        Context.ratingEngine = RatingEngine;
        if (state) state.registered = true;
        Logger.log('rating-engine: module registered (Context.ratingEngine) v' + RE_VERSION);
    }
};
