// rating-engine.js — TWQS / QAQS computation for Worker Output Search Ratings tab.
// Engine v16.0: Revision Efficiency replaces First-Pass Acceptance (0.5^(v-1)).

const RE_VERSION = '16.0';
const RE_MS_PER_DAY = 86400000;
const RE_HALFLIFE_DAYS = 30;
const RE_DIAG_SAMPLE_ROWS = 5;
const RE_DISCARDED_STALE_DAYS = 7;
// Dispute "Flag as Bug" creates a synthetic QA row by the resolver — exclude from QAQS
// when that row is flagged-as-bugged and timestamps align with their resolution.
const RE_DISPUTE_FLAG_QA_MAX_SKEW_MS = 5 * 60 * 1000;
// Reserved percent points on each end of the estimated-percentile scale (UI + exports).
const RE_PERCENTILE_MARGIN_BOTTOM = 10;
const RE_PERCENTILE_MARGIN_TOP = 20;
// Fallback tracked-time trapezoid when no baselines pack cutoffs are loaded.
const RE_TIME_T_LO = 15;
const RE_TIME_T_HI = 60;
const RE_TIME_MAX = 150;
const RE_TIME_SHRINK_C = 10;
const RE_TIME_FALLBACK_ANCHOR_CREDIT = 0.75;
const RE_TIME_AXIS_IDS = {
    v1CreationTime: true,
    qaTime: true,
};

// Terminal task status → quality score (mirrors rank-workers.py STATUS_QUALITY).
// Statuses not listed here are in-flight — excluded from outcome quality denominator.
const RE_STATUS_QUALITY = {
    production: 1.0,
    bugged: 0.5,
    'escalated-fleet-review': 0.5,
    discarded: 0.15,
    dismissed: 0.0,
};
const RE_CLOSURE_QUALITY = {
    production: 1.0,
    discarded: 0.5,
    dismissed: 0.0,
};

// Return Effectiveness: shippable-path statuses (task deaths excluded from denom).
const RE_QAQS_RET_EFF_DENOM_STATUSES = {
    production: true,
    bugged: true,
    'escalated-fleet-review': true,
};

// Explicit prompt-quality labels → ordinal Task Rating Quality points.
const RE_TASK_RATING_QUALITY_VALUE = {
    'Bottom 10%': 0,
    Average: 0.5,
    'Top 10%': 1,
};
// Explicit Top/Bottom labels count toward Label Discrimination usage rate.
const RE_EXPLICIT_LABEL_SET = {
    'Bottom 10%': true,
    'Top 10%': true,
};

// WPS (TWQS) per-axis shrinkage strengths (C). Priors come from encrypted Ops baselines.
// Dispute Loss Avoidance uses RE_DISPUTE_LOSS_RATE_* (not count shrinkage).
const RE_TWQS_C = {
    outcomeQuality:       10,
    positiveFeedbackRate: 10,
    taskRatingQuality:     5,
    revisionEfficiency:    5,
};

// QPS (QAQS) per-axis shrinkage strengths (C). Priors come from encrypted Ops baselines.
const RE_QAQS_RET_EFF_C         = 10;
const RE_QAQS_RET_ACT_C         = 10;
const RE_QAQS_ACCEPT_SCRUTINY_C = 10;
const RE_QAQS_LABEL_DISC_C      = 5;
// Omit Label Discrimination on thin QA samples (matches TW provisional threshold).
const RE_QAQS_LABEL_DISC_MIN_N  = 10;
// Label Discrimination: ideal Top/Bottom usage rate (tent peak); score 0 at 0% and at 2×ideal.
const RE_QAQS_LABEL_DISC_IDEAL  = 0.20;
// Acceptance Scrutiny: full credit between T_LO and T (high); taper to 0 at 0% and 100%.
const RE_QAQS_ACCEPT_SCRUTINY_T_LO = 0.40;
const RE_QAQS_ACCEPT_SCRUTINY_T = 0.60;
// Shared TWQS/QAQS Dispute Loss Avoidance: r = L/(T+C); score 0 when rate reaches R0.
const RE_DISPUTE_LOSS_RATE_C = 10;
const RE_DISPUTE_LOSS_RATE_R0 = 0.10;
// Aliases kept for any external readers of the old QAQS names.
const RE_QAQS_DISPUTE_DEF_C = RE_DISPUTE_LOSS_RATE_C;
const RE_QAQS_DISPUTE_DEF_R0 = RE_DISPUTE_LOSS_RATE_R0;

// Documented generation-time cutoffs (applied by compute-cohort-baselines.py).
// Live engine uses presence of a shipped role pack — not these numbers — for selection.
const RE_BASELINE_POLICY = {
    twqs: { minTasks: 500, minWriters: 20 },
    qaqs: { minFeedback: 500, minReviewers: 20 },
};

const RE_TWQS_AXES = [
    { id: 'outcomeQuality',       label: 'Outcome Quality',        weight: 0.35 },
    { id: 'v1CreationTime',       label: 'V1 Creation Time',       weight: 0.20 },
    { id: 'positiveFeedbackRate', label: 'Positive Feedback Rate', weight: 0.15 },
    { id: 'taskRatingQuality',    label: 'Task Rating Quality',    weight: 0.10 },
    { id: 'revisionEfficiency',   label: 'Revision Efficiency',    weight: 0.10 },
    { id: 'disputeLossAvoidance', label: 'Dispute Loss Avoidance', weight: 0.10 },
];

const RE_QAQS_AXES = [
    { id: 'returnEffectiveness', label: 'Return Effectiveness', weight: 0.30 },
    { id: 'qaTime',              label: 'QA Time',              weight: 0.20 },
    { id: 'returnActionability', label: 'Return Actionability', weight: 0.20 },
    { id: 'labelDiscrimination', label: 'Label Discrimination', weight: 0.10 },
    { id: 'acceptanceScrutiny',  label: 'Acceptance Scrutiny',  weight: 0.10 },
    { id: 'disputeDefense',      label: 'Dispute Loss Avoidance', weight: 0.10 },
];

// Population tier labels (card primary). Absolute top pegs + empirical p10/p30/p70.
// Regenerated by local/data/utils/compute-percentile-calibration.py (tierThresholds).
// Snapshot: 638 WPS / 242 QPS; flat + recency30d (engine 16.0 Revision Efficiency).
const RE_TIER_TOP_PEG = { twqs: 80, qaqs: 70 };
const RE_TIER_DEFS = [
    { id: 'poor', label: 'Poor' },
    { id: 'below_average', label: 'Below average' },
    { id: 'typical', label: 'Typical' },
    { id: 'above_average', label: 'Above average' },
    { id: 'top_tier', label: 'Top tier' },
];
const RE_TIER_THRESHOLDS = {
    twqs: {
        flat:         { p10: 66.743, p30: 72.211, p70: 78.152, topMin: 80 },
        recency:      { p10: 70.942, p30: 74.11, p70: 76.916, topMin: 80 },
        flatNoTime:   { p10: 66.12, p30: 72.22, p70: 78.74, topMin: 80 },
        recencyNoTime:{ p10: 70.23, p30: 74.081, p70: 77.34, topMin: 80 },
    },
    qaqs: {
        flat:         { p10: 69.09, p30: 73.428, p70: 78.247, topMin: 78.257 },
        recency:      { p10: 71.766, p30: 74.826, p70: 78.97, topMin: 78.98 },
        flatNoTime:   { p10: 68.963, p30: 73.441, p70: 78.897, topMin: 78.907 },
        recencyNoTime:{ p10: 72.071, p30: 74.593, p70: 79.657, topMin: 79.667 },
    },
};

// Parametric percentile distributions (μ, σ) fitted from current dive.db scores.
// Estimated percentile (shown on cards, included in exports) =
// bottom + (100 − bottom − top) × Φ((score − μ) / σ)
// with bottom=10, top=20. Regenerated by compute-percentile-calibration.py.
// Snapshot: 638 WPS / 242 QPS; flat + recency30d (engine 16.0 Revision Efficiency).
const RE_PERCENTILE_PARAMS = {
    twqs: {
        flat:         { mu: 74.6032, sigma: 6.0451 },
        recency:      { mu: 75.3654, sigma: 3.7703 },
        flatNoTime:   { mu: 74.8039, sigma: 6.8064 },
        recencyNoTime:{ mu: 75.4579, sigma: 4.2845 },
    },
    qaqs: {
        flat:         { mu: 75.7275, sigma: 4.9993 },
        recency:      { mu: 76.7142, sigma: 3.7064 },
        flatNoTime:   { mu: 76.2382, sigma: 5.4664 },
        recencyNoTime:{ mu: 77.1989, sigma: 4.2073 },
    },
};

// ---------------------------------------------------------------------------
// Utility helpers
// ---------------------------------------------------------------------------

function reLib() {
    return Context.dashboardLib || null;
}

function reFeedbackTimestamp(entry) {
    return String((entry && (entry.feedbackAt || entry.created_at)) || '').trim();
}

function reTaskTimestamp(task, item) {
    return String((task && (task.createdAt || task.created_at)) || (item && item.sortAt) || '').trim();
}

function reIdsEqual(a, b) {
    return String(a || '').trim() === String(b || '').trim();
}

function reResolveFeedbackId(id, remap) {
    const key = String(id || '').trim();
    if (!key) return '';
    return String((remap && remap[key]) || key);
}

function reFeedbackAtForResolvedId(task, feedbackId) {
    const fid = String(feedbackId || '').trim();
    if (!fid || !task) return '';
    for (const entry of task.allFeedback || []) {
        if (!reIsHumanFeedback(entry)) continue;
        if (reIdsEqual(entry.id, fid)) return reFeedbackTimestamp(entry);
    }
    return '';
}

function reIsHumanFeedback(entry) {
    if (!entry) return false;
    if (entry.isVerifierFailure || entry.isSystemFeedback) return false;
    if (entry.display && (entry.display.isVerifierFailure || entry.display.isSystemFeedback)) return false;
    return true;
}

// Returns quality score for terminal tasks; null for in-flight (mirrors rank-workers.py task_terminal_quality).
function reTaskTerminalQuality(task, nowMs) {
    const status = String((task && task.status) || '').toLowerCase().trim();
    if (!status) return null;
    if (status === 'discarded') {
        const createdAt = String((task && (task.createdAt || task.created_at)) || '').trim();
        const ts = Date.parse(createdAt);
        if (Number.isNaN(ts)) return null;
        const ageDays = Math.max(0, (nowMs - ts) / RE_MS_PER_DAY);
        if (ageDays < RE_DISCARDED_STALE_DAYS) return null;
        return RE_STATUS_QUALITY.discarded;
    }
    const quality = RE_STATUS_QUALITY[status];
    return quality !== undefined ? quality : null;
}

// Closure quality intentionally does not apply the discarded stale-age gate.
// It measures the eventual path for tasks that were not bugged/flagged.
function reTaskClosureQuality(task) {
    const status = String((task && task.status) || '').toLowerCase().trim();
    const quality = RE_CLOSURE_QUALITY[status];
    return quality !== undefined ? quality : null;
}

// Standard normal CDF approximation (Abramowitz–Stegun rational, max error ≈7.5×10⁻⁸).
function reNormalCdf(z) {
    const t = 1 / (1 + 0.2316419 * Math.abs(z));
    const poly = t * (0.319381530 + t * (-0.356563782 + t * (1.781477937 + t * (-1.821255978 + t * 1.330274429))));
    const pdf = Math.exp(-0.5 * z * z) / Math.sqrt(2 * Math.PI);
    const cdf = 1 - pdf * poly;
    return z >= 0 ? cdf : 1 - cdf;
}

// Estimated percentile via bottom + (100 − bottom − top) × Φ((score − μ) / σ).
// Returns integer in [bottom, 100−top] (currently 10–80), or null.
function reEstimatePercentile(score, params) {
    if (score == null || !Number.isFinite(score)) return null;
    if (!params || !Number.isFinite(params.mu) || !Number.isFinite(params.sigma) || params.sigma <= 0) return null;
    const bottom = RE_PERCENTILE_MARGIN_BOTTOM;
    const top = RE_PERCENTILE_MARGIN_TOP;
    const span = 100 - bottom - top;
    const z = (score - params.mu) / params.sigma;
    const pct = bottom + span * reNormalCdf(z);
    return Math.max(bottom, Math.min(100 - top, Math.round(pct)));
}

function reOrdinalSuffix(n) {
    const v = Math.abs(Math.trunc(Number(n)));
    if (!Number.isFinite(v)) return 'th';
    const mod100 = v % 100;
    if (mod100 >= 11 && mod100 <= 13) return 'th';
    const mod10 = v % 10;
    if (mod10 === 1) return 'st';
    if (mod10 === 2) return 'nd';
    if (mod10 === 3) return 'rd';
    return 'th';
}

/** Formats an integer percentile as e.g. "72nd". Returns '' if invalid. */
function reFormatPercentile(n) {
    if (n == null || !Number.isFinite(Number(n))) return '';
    const v = Math.round(Number(n));
    return String(v) + reOrdinalSuffix(v);
}

// Empirical-Bayes shrinkage toward cohort prior.
function reShrunkRate(k, n, C, prior) {
    return (k + C * prior) / (n + C);
}

/**
 * Revision Efficiency per-task credit: halve for each display version after v1.
 * Approved writer disputes subtract from the effective version count (floor 1).
 */
function reRevisionEfficiencyCredit(displayCount, approvedWins) {
    const count = Number(displayCount);
    if (!Number.isFinite(count) || count < 1) return null;
    const wins = Math.max(0, Number(approvedWins) || 0);
    const v = Math.max(1, count - wins);
    return Math.pow(0.5, v - 1);
}

/** Population tier from empirical cutoffs + absolute top peg. */
function reCalibrationKey(weighting, includeTime) {
    const base = weighting === 'flat' ? 'flat' : 'recency';
    return includeTime === false ? (base + 'NoTime') : base;
}

/** Population tier from empirical cutoffs + absolute top peg. */
function rePopulationTier(score, kind, weighting, includeTime) {
    const n = Number(score);
    if (!Number.isFinite(n)) return { id: null, label: '—' };
    const key = reCalibrationKey(weighting, includeTime);
    const params = (RE_TIER_THRESHOLDS[kind] && RE_TIER_THRESHOLDS[kind][key]) || null;
    if (!params) return { id: null, label: '—' };
    let topMin = Number(params.topMin);
    const p10 = Number(params.p10);
    const p30 = Number(params.p30);
    const p70 = Number(params.p70);
    if (!(topMin > p70)) topMin = p70 + 0.01;
    if (n >= topMin) return { id: RE_TIER_DEFS[4].id, label: RE_TIER_DEFS[4].label };
    if (n >= p70) return { id: RE_TIER_DEFS[3].id, label: RE_TIER_DEFS[3].label };
    if (n >= p30) return { id: RE_TIER_DEFS[2].id, label: RE_TIER_DEFS[2].label };
    if (n >= p10) return { id: RE_TIER_DEFS[1].id, label: RE_TIER_DEFS[1].label };
    return { id: RE_TIER_DEFS[0].id, label: RE_TIER_DEFS[0].label };
}

function reAnnotatePopulationTier(block, kind, weighting, includeTime) {
    if (!block) return block;
    if (block.score == null || !Number.isFinite(Number(block.score))) {
        block.band = '—';
        block.tierId = null;
        return block;
    }
    const tier = rePopulationTier(block.score, kind, weighting, includeTime);
    block.band = tier.label;
    block.tierId = tier.id;
    return block;
}

// TWQS confidence: based on terminal task count (mirrors rank-workers.py _confidence).
function reTwqsConfidenceBadge(terminalCount) {
    const n = Number(terminalCount) || 0;
    if (n < 10) return { tier: 'provisional', label: 'Provisional' };
    if (n < 50) return { tier: 'standard', label: 'Standard' };
    return { tier: 'high', label: 'High confidence' };
}

// QAQS confidence: based on feedback row count (mirrors rank-qa.py _confidence).
function reQaqsConfidenceBadge(feedbackRowCount) {
    const n = Number(feedbackRowCount) || 0;
    if (n < 25) return { tier: 'provisional', label: 'Provisional' };
    if (n < 100) return { tier: 'standard', label: 'Standard' };
    return { tier: 'high', label: 'High confidence' };
}

// Returns 0 when outside date window or timestamp unparseable.
// 'flat'    → 1.0 inside window (or always if no window)
// 'recency' → exp(−ln(2)·age/H) inside window (or always if no window)
function reEventWeight(isoTs, weighting, nowMs, window) {
    const ts = Date.parse(isoTs);
    if (Number.isNaN(ts)) return 0;
    if (window) {
        if (window.afterIso && isoTs < window.afterIso) return 0;
        if (window.beforeIso && isoTs > window.beforeIso) return 0;
    }
    if (weighting === 'flat') return 1;
    const ageDays = Math.max(0, (nowMs - ts) / RE_MS_PER_DAY);
    return Math.exp(-Math.LN2 * ageDays / RE_HALFLIFE_DAYS);
}

function reResolveWindow(committed) {
    const lib = reLib();
    const afterLocal = String((committed && committed.afterLocal) || '').trim();
    const beforeLocal = String((committed && committed.beforeLocal) || '').trim();
    let afterIso = '';
    let beforeIso = '';
    if (lib && typeof lib.validateCreatedAtRange === 'function') {
        const check = lib.validateCreatedAtRange(afterLocal, beforeLocal);
        if (check && check.valid) {
            afterIso = check.afterIso || '';
            beforeIso = check.beforeIso || '';
        }
    }
    return { afterLocal, beforeLocal, afterIso, beforeIso };
}

function reWeightedMean(pairs) {
    let wSum = 0;
    let total = 0;
    for (const { value, weight } of pairs) {
        if (!weight || weight <= 0) continue;
        wSum += weight;
        total += value * weight;
    }
    if (wSum <= 0) return null;
    return total / wSum;
}

function reCombineAxes(axisDefs) {
    const defined = axisDefs.filter((p) =>
        p.defined !== false
        && p.excluded !== true
        && p.score != null
        && Number.isFinite(p.score)
    );
    if (defined.length === 0) {
        return { score: null, band: '—', tierId: null, axes: axisDefs };
    }
    const baseSum = defined.reduce((s, p) => s + p.baseWeight, 0);
    let composite = 0;
    for (const p of axisDefs) {
        if (p.defined === false || p.excluded === true || p.score == null || !Number.isFinite(p.score)) {
            p.effectiveWeight = 0;
            continue;
        }
        p.effectiveWeight = p.baseWeight / baseSum;
        composite += p.score * p.effectiveWeight;
    }
    const score = Math.round(composite * 1000) / 10;
    return { score, band: '—', tierId: null, axes: axisDefs };
}

function reTaskRatingQualityValue(rawRating) {
    const key = String(rawRating || '').trim();
    return Object.prototype.hasOwnProperty.call(RE_TASK_RATING_QUALITY_VALUE, key)
        ? RE_TASK_RATING_QUALITY_VALUE[key]
        : null;
}

function reExportTimestampSlug(value) {
    const parsed = value ? new Date(value) : new Date();
    const date = Number.isNaN(parsed.getTime()) ? new Date() : parsed;
    return date.toISOString().replace(/[:.]/g, '-');
}

function reWorkerExportIdentity(workerReport) {
    const name = reSlugify(workerReport.name || '');
    const workerId = reSlugify(workerReport.workerId || '');
    if (name && workerId && name !== workerId) return name + '-' + workerId;
    return name || workerId || 'worker';
}

function reValidateRolePriors(kind, priors) {
    if (!priors || typeof priors !== 'object') return null;
    const required = kind === 'twqs'
        ? ['outcomeQuality', 'positiveFeedbackRate', 'taskRatingQuality', 'revisionEfficiency', 'disputeLossAvoidance']
        : ['returnEffectiveness', 'returnActionability', 'acceptanceScrutiny', 'disputeDefense', 'labelDiscrimination'];
    const out = {};
    for (const id of required) {
        const n = Number(priors[id]);
        if (!Number.isFinite(n)) return null;
        out[id] = n;
    }
    return out;
}

/** Two-sided Acceptance Scrutiny score from a shrunk accept rate (40–60% plateau). */
function reAcceptanceScrutinyScore(acceptRate) {
    const a = Number(acceptRate);
    if (!Number.isFinite(a)) return null;
    const tLo = RE_QAQS_ACCEPT_SCRUTINY_T_LO;
    const tHi = RE_QAQS_ACCEPT_SCRUTINY_T;
    if (a < tLo) {
        if (!(tLo > 0)) return 0;
        return Math.max(0, a / tLo);
    }
    if (a <= tHi) return 1;
    if (tHi >= 1) return 0;
    return Math.max(0, 1 - (a - tHi) / (1 - tHi));
}

/** Tent map: full credit at ideal usage rate; linear taper to 0 at 0 and at 2×ideal. */
function reLabelDiscriminationScore(usageRate) {
    const a = Number(usageRate);
    if (!Number.isFinite(a)) return null;
    const t = RE_QAQS_LABEL_DISC_IDEAL;
    if (!(t > 0)) return 0;
    return Math.max(0, 1 - Math.abs(a - t) / t);
}

/** Dispute Loss Avoidance (TW + QA): one-sided loss-rate curve. r = L/(T+C); 1 at r=0, 0 at r≥R0. */
function reDisputeLossRateScore(losses, tasks, C, R0) {
    const L = Number(losses);
    const T = Number(tasks);
    const c = Number(C);
    const r0 = Number(R0);
    if (!Number.isFinite(L) || !Number.isFinite(T) || L < 0 || T < 0) return null;
    if (!Number.isFinite(c) || c < 0) return null;
    const r = L / (T + c);
    if (!(r0 > 0)) return 0;
    return Math.max(0, 1 - r / r0);
}

/** Shrink a weighted mean toward a fixed mid-band anchor (pseudo-count C). */
function reShrunkMeanMinutes(sumWM, sumW, C, anchorMinutes) {
    const sw = Number(sumW);
    const swm = Number(sumWM);
    const c = Number(C);
    const m = Number(anchorMinutes);
    if (!Number.isFinite(sw) || sw <= 0) return null;
    if (!Number.isFinite(swm) || !Number.isFinite(c) || c < 0 || !Number.isFinite(m)) return null;
    return (swm + c * m) / (sw + c);
}

/** Shrink weighted mean credit toward population anchorCredit. */
function reShrunkCredit(sumWC, sumW, C, anchorCredit) {
    const sw = Number(sumW);
    const swc = Number(sumWC);
    const c = Number(C);
    const a = Number(anchorCredit);
    if (!Number.isFinite(sw) || sw <= 0) return null;
    if (!Number.isFinite(swc) || !Number.isFinite(c) || c < 0 || !Number.isFinite(a)) return null;
    return (swc + c * a) / (sw + c);
}

/**
 * Tracked-time trapezoid on minutes with optional cohort cutoffs.
 * Full credit between T_LO and T_HI; linear taper to 0 at 0 and at MAX.
 */
function reTimeTrapezoidScore(avgMinutes, cutoffs) {
    const minutes = Number(avgMinutes);
    if (!Number.isFinite(minutes)) return null;
    const tLo = Number(cutoffs && cutoffs.tLo);
    const tHi = Number(cutoffs && cutoffs.tHi);
    const tMax = Number(cutoffs && cutoffs.tMax);
    const lo = Number.isFinite(tLo) && tLo > 0 ? tLo : RE_TIME_T_LO;
    const hi = Number.isFinite(tHi) && tHi > lo ? tHi : RE_TIME_T_HI;
    const mx = Number.isFinite(tMax) && tMax > hi ? tMax : RE_TIME_MAX;
    if (minutes < lo) {
        if (!(lo > 0)) return 0;
        return Math.max(0, minutes / lo);
    }
    if (minutes <= hi) return 1;
    const span = mx - hi;
    if (!(span > 0)) return 0;
    return Math.max(0, 1 - (minutes - hi) / span);
}

function reValidateTimeCutoffs(raw) {
    if (!raw || typeof raw !== 'object') return null;
    const tLo = Number(raw.tLo);
    const tHi = Number(raw.tHi);
    const tMax = Number(raw.tMax);
    if (!(tLo > 0 && tHi > tLo && tMax > tHi)) return null;
    let anchorCredit = Number(raw.anchorCredit);
    if (!Number.isFinite(anchorCredit) || anchorCredit < 0 || anchorCredit > 1) {
        anchorCredit = RE_TIME_FALLBACK_ANCHOR_CREDIT;
    }
    const out = { tLo, tHi, tMax, anchorCredit };
    if (Number.isFinite(Number(raw.n))) out.n = Number(raw.n);
    if (Number.isFinite(Number(raw.people))) out.people = Number(raw.people);
    return out;
}

function reFallbackTimeCutoffs() {
    return {
        tLo: RE_TIME_T_LO,
        tHi: RE_TIME_T_HI,
        tMax: RE_TIME_MAX,
        anchorCredit: RE_TIME_FALLBACK_ANCHOR_CREDIT,
    };
}

/** Resolve env → team → global time cutoffs for kind ('twqs' | 'qaqs'). */
function reResolveTimeCutoffs(baselines, kind, task) {
    const fb = reFallbackTimeCutoffs();
    if (!baselines) return { cutoffs: fb, source: 'fallback' };
    const envKey = reCohortKey(task, 'env');
    const teamKey = reCohortKey(task, 'team');
    const pick = (pack) => {
        if (!pack || typeof pack !== 'object') return null;
        const tc = pack.timeCutoffs && pack.timeCutoffs[kind];
        return reValidateTimeCutoffs(tc);
    };
    if (envKey) {
        const cut = pick(baselines.env && baselines.env[envKey]);
        if (cut) return { cutoffs: cut, source: 'env', key: envKey };
    }
    if (teamKey) {
        const cut = pick(baselines.team && baselines.team[teamKey]);
        if (cut) return { cutoffs: cut, source: 'team', key: teamKey };
    }
    const globalCut = pick(baselines.global);
    if (globalCut) return { cutoffs: globalCut, source: 'global' };
    return { cutoffs: fb, source: 'fallback' };
}

function reGlobalTimeAnchorCredit(baselines, kind) {
    const resolved = reResolveTimeCutoffs(baselines, kind, null);
    const a = Number(resolved.cutoffs && resolved.cutoffs.anchorCredit);
    return Number.isFinite(a) ? a : RE_TIME_FALLBACK_ANCHOR_CREDIT;
}

function reIsTimeAxisId(id) {
    return !!RE_TIME_AXIS_IDS[String(id || '')];
}

function reValidateRatingBaselines(raw) {
    if (!raw || typeof raw !== 'object') return null;
    const globalTw = reValidateRolePriors('twqs', raw.global && raw.global.priors && raw.global.priors.twqs);
    const globalQa = reValidateRolePriors('qaqs', raw.global && raw.global.priors && raw.global.priors.qaqs);
    if (!globalTw || !globalQa) return null;
    const policy = {
        twqs: {
            minTasks: Number((raw.policy && raw.policy.twqs && raw.policy.twqs.minTasks)
                || RE_BASELINE_POLICY.twqs.minTasks),
            minWriters: Number((raw.policy && raw.policy.twqs && raw.policy.twqs.minWriters)
                || RE_BASELINE_POLICY.twqs.minWriters),
        },
        qaqs: {
            minFeedback: Number((raw.policy && raw.policy.qaqs && raw.policy.qaqs.minFeedback)
                || RE_BASELINE_POLICY.qaqs.minFeedback),
            minReviewers: Number((raw.policy && raw.policy.qaqs && raw.policy.qaqs.minReviewers)
                || RE_BASELINE_POLICY.qaqs.minReviewers),
        },
    };
    return {
        schemaVersion: Number(raw.schemaVersion) || 1,
        generatedAt: String(raw.generatedAt || '') || null,
        policy,
        global: {
            priors: { twqs: globalTw, qaqs: globalQa },
            volume: (raw.global && raw.global.volume) || null,
            timeCutoffs: (raw.global && raw.global.timeCutoffs) || null,
        },
        team: (raw.team && typeof raw.team === 'object') ? raw.team : {},
        env: (raw.env && typeof raw.env === 'object') ? raw.env : {},
        month: (raw.month && typeof raw.month === 'object') ? raw.month : {},
    };
}

function reLoadRatingBaselines(opts) {
    if (opts && opts.cohortBaselines) {
        const validated = reValidateRatingBaselines(opts.cohortBaselines);
        if (validated) return validated;
    }
    if (Context.ratingCohortBaselines) {
        const validated = reValidateRatingBaselines(Context.ratingCohortBaselines);
        if (validated) return validated;
    }
    const ops = Context.opsTab;
    if (ops && typeof ops.getRatingBaselines === 'function') {
        try {
            const fromOps = ops.getRatingBaselines();
            const validated = reValidateRatingBaselines(fromOps);
            if (validated) {
                Context.ratingCohortBaselines = validated;
                return validated;
            }
        } catch (_e) {
            // Fall through to unavailable.
        }
    }
    return null;
}

/** Resolve effective priors for a role. Subset packs are only present when eligible. */
function reResolveRolePriors(baselines, kind, dimension, key) {
    const globalPriors = baselines.global.priors[kind];
    if (!dimension || !key) {
        return {
            priors: globalPriors,
            source: 'global',
            reason: 'main',
            volume: baselines.global.volume || null,
        };
    }
    const pack = baselines[dimension] && baselines[dimension][key];
    const slicePriors = pack
        ? reValidateRolePriors(kind, pack.priors && pack.priors[kind])
        : null;
    if (!slicePriors) {
        return {
            priors: globalPriors,
            source: 'global',
            reason: 'notShipped',
            volume: (pack && pack.volume) || null,
            key,
            dimension,
        };
    }
    return {
        priors: slicePriors,
        source: 'subset',
        reason: 'shipped',
        volume: pack.volume || null,
        key,
        dimension,
    };
}

function reCohortPack(kind, resolved) {
    return {
        priors: { [kind]: resolved.priors },
        priorSource: {
            source: resolved.source,
            reason: resolved.reason,
            volume: resolved.volume,
            key: resolved.key || null,
            dimension: resolved.dimension || null,
        },
    };
}

function reCohortPriors(kind, cohort) {
    const supplied = cohort && cohort.priors && cohort.priors[kind];
    return supplied && typeof supplied === 'object' ? { ...supplied } : null;
}

function reCohortKey(task, dimension) {
    if (!task) return '';
    if (dimension === 'team') return String(task.team || task.teamId || '').trim();
    if (dimension === 'env') return String(task.envKey || task.environment || '').trim();
    if (dimension === 'month') {
        const ts = String(task.createdAt || task.created_at || '').trim();
        return /^\d{4}-\d{2}/.test(ts) ? ts.slice(0, 7) : '';
    }
    return '';
}

function reVolumeWeightedAxes(usable) {
    const byId = new Map();
    for (const row of usable || []) {
        const vol = Number(row.volume) || 0;
        if (vol <= 0 || !row.block) continue;
        for (const axis of row.block.axes || []) {
            if (!axis || axis.defined === false || axis.score == null) continue;
            const id = axis.id || axis.label;
            if (!id) continue;
            let agg = byId.get(id);
            if (!agg) {
                agg = {
                    id: axis.id,
                    label: axis.label,
                    baseWeight: axis.baseWeight,
                    scoreSum: 0,
                    volume: 0,
                };
                byId.set(id, agg);
            }
            agg.scoreSum += axis.score * vol;
            agg.volume += vol;
        }
    }
    return [...byId.values()].map((agg) => ({
        id: agg.id,
        label: agg.label,
        baseWeight: agg.baseWeight,
        score: agg.volume > 0 ? agg.scoreSum / agg.volume : null,
        defined: true,
        effectiveWeight: null,
        raw: { volume: Math.round(agg.volume * 1000) / 1000 },
    }));
}

function reBlendCohortBlocks(mainBlock, slices, confidenceFn, kind, weighting, includeTime) {
    if (!mainBlock || mainBlock.score == null) return null;
    let mainWeight = 0.5;
    const channels = {};
    for (const dimension of ['team', 'env', 'month']) {
        const rows = slices[dimension] || [];
        const usable = rows.filter((row) => row.block && row.block.score != null && row.volume > 0);
        const initialWeight = 1 / 6;
        if (!usable.length) {
            mainWeight += initialWeight;
            channels[dimension] = {
                score: null, volume: 0, weight: 0, provisional: false, keys: [], axes: [], slices: [],
            };
            continue;
        }
        const totalVolume = usable.reduce((sum, row) => sum + row.volume, 0);
        const score = usable.reduce((sum, row) => sum + row.block.score * row.volume, 0) / totalVolume;
        const provisional = confidenceFn(totalVolume).tier === 'provisional';
        const weight = provisional ? initialWeight / 2 : initialWeight;
        mainWeight += initialWeight - weight;
        channels[dimension] = {
            score,
            volume: totalVolume,
            weight,
            provisional,
            keys: usable.map((row) => row.key),
            axes: reVolumeWeightedAxes(usable),
            slices: usable
                .slice()
                .sort((a, b) => {
                    // Months are YYYY-MM keys — always chronological for the breakdown UI.
                    if (dimension === 'month') {
                        return String(a.key).localeCompare(String(b.key));
                    }
                    return (b.volume || 0) - (a.volume || 0)
                        || String(a.key).localeCompare(String(b.key));
                })
                .map((row) => {
                    const sliceTier = rePopulationTier(row.block.score, kind, weighting, includeTime);
                    return {
                        key: row.key,
                        score: row.block.score,
                        volume: row.volume,
                        band: sliceTier.label,
                        tierId: sliceTier.id,
                        estimatedPercentile: row.block.estimatedPercentile != null
                            ? row.block.estimatedPercentile
                            : null,
                        priorSource: row.priorSource || (row.block && row.block.priorSource) || null,
                        axes: (row.block.axes || []).map((axis) => ({ ...axis })),
                    };
                }),
        };
    }
    const score = mainWeight * mainBlock.score
        + Object.values(channels).reduce((sum, channel) => sum + (channel.score == null ? 0 : channel.weight * channel.score), 0);
    const rounded = Math.round(score * 10) / 10;
    const tier = rePopulationTier(rounded, kind, weighting, includeTime);
    const calKey = reCalibrationKey(weighting, includeTime);
    const pctParams = (RE_PERCENTILE_PARAMS[kind] && RE_PERCENTILE_PARAMS[kind][calKey]) || {};
    return {
        score: rounded,
        band: tier.label,
        tierId: tier.id,
        estimatedPercentile: reEstimatePercentile(rounded, pctParams),
        confidence: mainBlock.confidence,
        main: {
            score: mainBlock.score,
            weight: mainWeight,
            axes: (mainBlock.axes || []).map((axis) => ({ ...axis })),
        },
        channels,
    };
}

function reHumanFeedbackChronological(task) {
    return (task.allFeedback || [])
        .filter(reIsHumanFeedback)
        .sort((a, b) => reFeedbackTimestamp(a).localeCompare(reFeedbackTimestamp(b)));
}

function reIsoWeekKey(iso) {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return null;
    const utc = new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
    const dayNum = utc.getUTCDay() || 7;
    utc.setUTCDate(utc.getUTCDate() + 4 - dayNum);
    const yearStart = new Date(Date.UTC(utc.getUTCFullYear(), 0, 1));
    const weekNo = Math.ceil((((utc - yearStart) / RE_MS_PER_DAY) + 1) / 7);
    return utc.getUTCFullYear() + '-W' + String(weekNo).padStart(2, '0');
}

function reMedian(values) {
    const nums = values.filter((v) => Number.isFinite(v)).sort((a, b) => a - b);
    if (!nums.length) return null;
    const mid = Math.floor(nums.length / 2);
    return nums.length % 2 ? nums[mid] : (nums[mid - 1] + nums[mid]) / 2;
}

function reSlugify(text) {
    return String(text || 'worker')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '')
        .slice(0, 48) || 'worker';
}

function reFormatPct(score) {
    const lib = reLib();
    if (lib && typeof lib.formatPercent === 'function') return lib.formatPercent(score * 100);
    return (Math.round(score * 1000) / 10).toFixed(1);
}

function rePctOneDecimal(fraction) {
    if (fraction == null || !Number.isFinite(fraction)) return null;
    return Math.round(fraction * 1000) / 10;
}

function reAxisExportRow(axis) {
    const defined = axis && axis.defined !== false && axis.score != null && Number.isFinite(axis.score);
    const excluded = !!(axis && axis.excluded);
    return {
        id: String((axis && axis.id) || ''),
        label: String((axis && axis.label) || ''),
        baseWeightPct: rePctOneDecimal(axis && axis.baseWeight),
        effectiveWeightPct: (defined && !excluded) ? rePctOneDecimal(axis.effectiveWeight) : 0,
        subScorePct: defined ? rePctOneDecimal(axis.score) : null,
        defined,
        excluded
    };
}

function reSortedAxesForExport(axes) {
    // Highest baseWeight first; equal weights keep engine definition order (stable sort).
    return [...(axes || [])].sort((a, b) =>
        (b.baseWeight || 0) - (a.baseWeight || 0)
    );
}

function reScoreBlockExport(block) {
    if (!block) return null;
    return {
        score: block.score,
        band: block.band,
        tierId: block.tierId != null ? block.tierId : null,
        estimatedPercentile: block.estimatedPercentile != null ? block.estimatedPercentile : null,
        confidence: block.confidence || null,
        axes: reSortedAxesForExport(block.axes).map(reAxisExportRow)
    };
}

function reWorkerJsonExport(workerReport) {
    const src = workerReport || {};
    const flatTwqs = src.twqs && src.twqs.flat;
    const recencyTwqs = src.twqs && src.twqs.recency;
    const flatQaqs = src.qaqs && src.qaqs.flat;
    const recencyQaqs = src.qaqs && src.qaqs.recency;

    return {
        workerId: src.workerId,
        name: src.name,
        email: src.email || '',
        window: src.window || {},
        computedAt: src.computedAt || null,
        engineVersion: src.engineVersion || RE_VERSION,
        exportDate: src.exportDate || null,
        weighting: {
            flat: {
                twqs: reScoreBlockExport(flatTwqs),
                qaqs: reScoreBlockExport(flatQaqs),
            },
            recency: {
                twqs: reScoreBlockExport(recencyTwqs),
                qaqs: reScoreBlockExport(recencyQaqs),
            }
        }
    };
}

function reAxisOmitReason(axis) {
    if (!axis || axis.defined !== false) return null;
    switch (axis.id) {
        case 'outcomeQuality':
            return 'No terminal tasks in scope';
        case 'positiveFeedbackRate':
            return 'No human feedback on authored tasks in scope';
        case 'taskRatingQuality':
        case 'nonBottomScoreRate':
            return 'No explicitly scored feedback in scope';
        case 'revisionEfficiency':
            return 'No terminal tasks with version history in scope';
        case 'firstPassAcceptance':
            return 'No authored tasks with human feedback in scope';
        case 'disputeWinRate':
        case 'disputeLossAvoidance':
            return 'No resolved disputes in scope';
        case 'returnEffectiveness':
            return 'No shippable-path tasks returned by this reviewer in scope';
        case 'returnActionability':
            return 'No return feedback episodes in scope';
        case 'labelDiscrimination':
            return 'Fewer than 10 feedback rows in scope';
        case 'acceptanceScrutiny':
            return 'No human feedback rows in scope';
        case 'disputeDefense':
            return 'No resolved disputes linked to this reviewer in scope';
        case 'v1CreationTime':
            return 'No tracked v1 creation time in scope';
        case 'qaTime':
            return 'No tracked QA review time in scope';
        case 'feedbackResolution':
            return 'No return episodes by this QA in scope';
        case 'reviewCallAccuracy':
        case 'disputeOutcomes':
            return 'No resolved disputes in scope';
        case 'consistency':
            return 'Fewer than 2 active calendar weeks of activity in scope';
        default:
            return 'Axis omitted';
    }
}

/** Integer in-window observation counts for LLM explain (never weighted mass). */
function reAxisObservedCountsForLlm(axis) {
    if (!axis) return null;
    const raw = axis.raw || {};
    if (raw.observedCounts && typeof raw.observedCounts === 'object') {
        return { ...raw.observedCounts };
    }
    switch (axis.id) {
        case 'outcomeQuality':
            return {
                terminalTasks: raw.terminalTaskCount != null ? raw.terminalTaskCount : null,
                closureOutcomes: raw.closureN != null ? raw.closureN : null,
                closureStatusCounts: raw.closureStatusCounts || null,
            };
        case 'disputeLossAvoidance':
        case 'disputeWinRate':
        case 'disputeDefense':
            return {
                losses: raw.losses != null ? raw.losses : null,
                wins: raw.wins != null ? raw.wins : null,
                resolved: raw.resolved != null ? raw.resolved : null,
            };
        default:
            return null;
    }
}

function reAxisIsNeutralNoEvidence(axis) {
    if (!axis) return false;
    const raw = axis.raw || {};
    if (raw.neutralNoEvidence === true) return true;
    if (axis.id === 'disputeLossAvoidance' || axis.id === 'disputeDefense' || axis.id === 'disputeWinRate') {
        return Number(raw.resolved) === 0;
    }
    return false;
}

function reSampleStatusForVolume(kind, volume) {
    const n = Number(volume) || 0;
    if (kind === 'qaqs') return reQaqsConfidenceBadge(n).tier;
    return reTwqsConfidenceBadge(n).tier;
}

function reAxisRowForLlm(axis) {
    const defined = axis && axis.defined !== false && axis.score != null && Number.isFinite(axis.score);
    const excluded = !!(axis && axis.excluded);
    const neutralNoEvidence = reAxisIsNeutralNoEvidence(axis);
    const row = {
        id: String((axis && axis.id) || ''),
        label: String((axis && axis.label) || ''),
        weightPct: rePctOneDecimal(axis && axis.baseWeight),
        // Recency-weighted + prior-shrunk axis score (0–100). Not a raw observed ratio.
        axisScorePct: defined ? rePctOneDecimal(axis.score) : null,
        defined,
        excluded,
        neutralNoEvidence,
    };
    if (!defined) {
        row.omittedReason = reAxisOmitReason(axis);
    } else {
        const observedCounts = reAxisObservedCountsForLlm(axis);
        if (observedCounts) row.observedCounts = observedCounts;
        if (excluded) row.excludedFromComposite = true;
    }
    return row;
}

function reExtremeAxesForSlice(axes) {
    const usable = reSortedAxesForExport(axes).filter((axis) => {
        if (!axis || axis.defined === false || axis.score == null || !Number.isFinite(axis.score)) return false;
        if (reAxisIsNeutralNoEvidence(axis)) return false;
        return true;
    });
    if (!usable.length) return { strongestAxis: null, weakestAxis: null };
    let strongest = usable[0];
    let weakest = usable[0];
    for (const axis of usable) {
        if (axis.score > strongest.score) strongest = axis;
        if (axis.score < weakest.score) weakest = axis;
    }
    const toRef = (axis) => ({
        id: String(axis.id || ''),
        axisScorePct: rePctOneDecimal(axis.score),
    });
    if (strongest === weakest) {
        return { strongestAxis: toRef(strongest), weakestAxis: null };
    }
    return { strongestAxis: toRef(strongest), weakestAxis: toRef(weakest) };
}

function reCompactSliceForLlm(slice, kind, overallPercentile) {
    if (!slice) return null;
    const volume = slice.volume != null ? slice.volume : null;
    const estPct = slice.estimatedPercentile != null ? slice.estimatedPercentile : null;
    const overall = overallPercentile != null && Number.isFinite(Number(overallPercentile))
        ? Number(overallPercentile)
        : null;
    const extremes = reExtremeAxesForSlice(slice.axes);
    return {
        key: String(slice.key || ''),
        tier: slice.band || null,
        tierId: slice.tierId != null ? slice.tierId : null,
        estimatedPercentile: estPct,
        volume,
        sampleStatus: reSampleStatusForVolume(kind, volume),
        priorSource: (slice.priorSource && slice.priorSource.source) || null,
        percentileDeltaFromOverall: (estPct != null && overall != null)
            ? Math.round((Number(estPct) - overall) * 10) / 10
            : null,
        strongestAxis: extremes.strongestAxis,
        weakestAxis: extremes.weakestAxis,
    };
}

function reCompactSlicesForLlm(cohortEntry, kind, overallPercentile) {
    if (!cohortEntry || !cohortEntry.channels) return null;
    const dimensions = {};
    for (const dim of ['team', 'env', 'month']) {
        const channel = cohortEntry.channels[dim];
        const slices = (channel && Array.isArray(channel.slices)) ? channel.slices : [];
        if (!slices.length) continue;
        dimensions[dim] = slices
            .map((slice) => reCompactSliceForLlm(slice, kind, overallPercentile))
            .filter(Boolean)
            .sort((a, b) => {
                const volDiff = (Number(b.volume) || 0) - (Number(a.volume) || 0);
                if (volDiff !== 0) return volDiff;
                const deltaDiff = Math.abs(Number(b.percentileDeltaFromOverall) || 0)
                    - Math.abs(Number(a.percentileDeltaFromOverall) || 0);
                if (deltaDiff !== 0) return deltaDiff;
                return String(a.key).localeCompare(String(b.key));
            });
    }
    return Object.keys(dimensions).length ? dimensions : null;
}

/**
 * Card-aligned score block for LLM explain.
 * Headline fields match the main (pre-blend) card display; team/env/month
 * slices remain available as compact contrasts only.
 */
function reScoreBlockForLlm(mainBlock, kind, cohortEntry) {
    if (!mainBlock || mainBlock.score == null) return null;
    const display = mainBlock.display || {};
    const volume = kind === 'qaqs'
        ? {
            feedbackRows: display.inScopeFeedbackCount != null
                ? display.inScopeFeedbackCount
                : display.feedbackRowCount,
            tenureDays: display.tenureDays != null ? display.tenureDays : null,
        }
        : {
            terminalTasks: display.terminalTaskCount != null ? display.terminalTaskCount : null,
            tenureDays: display.tenureDays != null ? display.tenureDays : null,
        };
    const overallPct = mainBlock.estimatedPercentile != null
        ? mainBlock.estimatedPercentile
        : null;
    const axes = reSortedAxesForExport(mainBlock.axes).map(reAxisRowForLlm);
    const out = {
        score: mainBlock.score,
        tier: mainBlock.band || null,
        tierId: mainBlock.tierId != null ? mainBlock.tierId : null,
        estimatedPercentile: overallPct != null ? overallPct : null,
        confidence: (mainBlock.confidence && mainBlock.confidence.label) || null,
        volume,
        // axisScorePct values are recency-weighted (when weighting=recency) and prior-shrunk.
        axisScoreNote: 'axisScorePct is recency-weighted (when weighting is recency) and prior-shrunk; cite observedCounts for event totals, not axisScorePct as a raw ratio.',
        axes,
    };
    const slices = reCompactSlicesForLlm(cohortEntry, kind, overallPct);
    if (slices) out.slices = slices;
    return out;
}

/**
 * Token-lean per-worker payload for LLM explain / "LLM Data" export.
 * Headline matches the card; slices are compact; counts are integers.
 */
function reBuildLlmExplainData(worker, report, weighting) {
    const src = worker || {};
    const weight = (weighting === 'flat' || weighting === 'recency') ? weighting : 'recency';
    const pickBlock = (entry) => {
        if (!entry) return null;
        if (entry[weight]) return entry[weight];
        if (entry.score != null) return entry;
        return null;
    };
    const twqsBlock = pickBlock(src.twqs);
    const qaqsBlock = pickBlock(src.qaqs);
    const cohortEntry = src.cohort && src.cohort[weight] ? src.cohort[weight] : null;
    const out = {
        engineVersion: (report && report.version) || src.engineVersion || RE_VERSION,
        computedAt: (report && report.computedAt) || src.computedAt || null,
        window: (report && report.window) || src.window || {},
        worker: {
            name: src.name || src.workerId || '',
            // workerId intentionally omitted from LLM payload (token lean / privacy)
        },
        weighting: weight,
        scores: {},
    };
    const twqs = reScoreBlockForLlm(twqsBlock, 'twqs', cohortEntry && cohortEntry.twqs);
    const qaqs = reScoreBlockForLlm(qaqsBlock, 'qaqs', cohortEntry && cohortEntry.qaqs);
    if (twqs) out.scores.twqs = twqs;
    if (qaqs) out.scores.qaqs = qaqs;
    return out;
}

function reFieldAuditRow(entry, task, workerId) {
    const ts = reFeedbackTimestamp(entry);
    const allFb = reHumanFeedbackChronological(task);
    const chronoIdx = allFb.findIndex((e) => String(e.id) === String(entry.id));
    return {
        feedbackId: String(entry.id || ''),
        taskId: String((task && task.id) || ''),
        feedbackAt: ts || null,
        created_at_legacy: String((entry && entry.created_at) || '') || null,
        reviewerId: String((entry.reviewer && entry.reviewer.id) || ''),
        returnType: (() => {
            if (entry.isPositive) return 'accepted';
            if (entry.isEscalated) return 'escalated';
            if (entry.isFlaggedAsBugged) return 'bugged';
            return 'returned';
        })(),
        chronologicalIndex: chronoIdx,
        totalHumanFeedbackOnTask: allFb.length,
        isFirstQaOnTask: chronoIdx === 0,
        timestampResolvable: Boolean(ts)
    };
}

/** Ordinary return: negative human feedback that is neither escalated nor Flag-as-Bug. */
function reIsOrdinaryReturn(entry) {
    return Boolean(entry) && !entry.isPositive && !entry.isEscalated && !entry.isFlaggedAsBugged;
}

// Collects all QA feedback rows for a reviewer across hydrated items, deduped by feedback ID.
// Excludes system/verifier entries, self-reviews (reviewer === task author), and synthetic
// dispute "Flag as Bug" rows (same person resolved a dispute and left flagged-as-bugged QA).
function reIsDisputeResolutionFlagQa(entry, item, workerId) {
    if (!entry || !entry.isFlaggedAsBugged) return false;
    const fbAt = Date.parse(reFeedbackTimestamp(entry));
    for (const dispute of (item && item.disputes) || []) {
        if (!dispute || !dispute.resolutionAt) continue;
        if (!reIdsEqual(dispute.resolverId, workerId)) continue;
        const resolvedAt = Date.parse(dispute.resolutionAt);
        if (!Number.isFinite(fbAt) || !Number.isFinite(resolvedAt)) return true;
        if (Math.abs(fbAt - resolvedAt) <= RE_DISPUTE_FLAG_QA_MAX_SKEW_MS) return true;
    }
    return false;
}

function reCollectQaqsFeedbackRows(workerId, hydratedItems) {
    const feedbackById = new Map();
    for (const item of hydratedItems) {
        const task = item.task;
        if (!task) continue;
        const authorId = task.author && task.author.id;
        for (const entry of task.allFeedback || []) {
            if (!reIsHumanFeedback(entry)) continue;
            const reviewerId = entry.reviewer && entry.reviewer.id;
            if (!reIdsEqual(reviewerId, workerId)) continue;
            if (authorId && reIdsEqual(reviewerId, authorId)) continue;
            if (reIsDisputeResolutionFlagQa(entry, item, workerId)) continue;
            feedbackById.set(String(entry.id), { entry, task, item });
        }
    }
    return [...feedbackById.values()];
}

// ---------------------------------------------------------------------------
// RatingEngine
// ---------------------------------------------------------------------------

const RatingEngine = {
    VERSION: RE_VERSION,
    ordinalSuffix: reOrdinalSuffix,
    formatPercentile: reFormatPercentile,
    populationTier: rePopulationTier,
    TIER_DEFS: RE_TIER_DEFS,
    TIER_THRESHOLDS: RE_TIER_THRESHOLDS,
    TIER_TOP_PEG: RE_TIER_TOP_PEG,
    setCohortBaselines(baselines) {
        Context.ratingCohortBaselines = reValidateRatingBaselines(baselines) || baselines || {};
    },

    getBaselinePolicy() {
        return { ...RE_BASELINE_POLICY };
    },

    /** Estimated percentile (integer, margin-clamped) for a composite score. */
    estimatePercentile(score, kind, weighting, includeTime) {
        const key = reCalibrationKey(weighting, includeTime);
        const params = (RE_PERCENTILE_PARAMS[kind] && RE_PERCENTILE_PARAMS[kind][key]) || null;
        return reEstimatePercentile(score, params);
    },

    /** Token-lean explain payload for cards / LLM Data export. */
    buildLlmExplainData(worker, report, weighting) {
        return reBuildLlmExplainData(worker, report, weighting);
    },

    compute(options) {
        const opts = options || {};
        const cachedItems = opts.cachedItems || [];
        const committed = opts.committed || {};
        const nowMs = Number.isFinite(opts.nowMs) ? opts.nowMs : Date.now();
        const includeTime = opts.includeTime !== false;
        const authorIds = [...new Set((committed.authorIds || []).filter(Boolean))];
        const hydratedItems = cachedItems.filter((item) => item && item.hydrated === true);
        const unhydratedCount = cachedItems.length - hydratedItems.length;
        const window = reResolveWindow(committed);
        const profiles = opts.workerProfiles || {};
        const baselines = reLoadRatingBaselines(opts);
        if (!baselines) {
            Logger.warn('baselines unavailable — unlock Ops secrets with ratingBaselines');
            return {
                version: RE_VERSION,
                computedAt: new Date(nowMs).toISOString(),
                window,
                workers: [],
                includeTime,
                error: {
                    code: 'baselinesUnavailable',
                    message: 'Rating baselines are unavailable. Unlock the Ops dashboard so encrypted priors can load, then retry.'
                },
                meta: {
                    hydratedCount: hydratedItems.length,
                    unhydratedCount,
                    totalCount: cachedItems.length,
                    workerCount: 0,
                    baselinesReady: false,
                    includeTime
                }
            };
        }

        const globalTwCohort = reCohortPack('twqs', reResolveRolePriors(baselines, 'twqs', null, null));
        const globalQaCohort = reCohortPack('qaqs', reResolveRolePriors(baselines, 'qaqs', null, null));

        const workers = authorIds.map((workerId) => {
            const profile = profiles[workerId] || {};

            const flatTwqs = this._computeTwqs(workerId, hydratedItems, 'flat', window, nowMs, globalTwCohort, includeTime, baselines);
            const recencyTwqs = this._computeTwqs(workerId, hydratedItems, 'recency', window, nowMs, globalTwCohort, includeTime, baselines);
            const flatQaqs = this._computeQaqs(workerId, hydratedItems, 'flat', window, nowMs, globalQaCohort, includeTime, baselines);
            const recencyQaqs = this._computeQaqs(workerId, hydratedItems, 'recency', window, nowMs, globalQaCohort, includeTime, baselines);

            const cohort = this._computeCohortBlend(
                workerId, hydratedItems, window, nowMs, baselines,
                { flatTwqs, recencyTwqs, flatQaqs, recencyQaqs },
                includeTime
            );

            return {
                workerId,
                name: profile.name || profile.label || workerId,
                email: profile.email || '',
                window,
                twqs: { flat: flatTwqs, recency: recencyTwqs },
                qaqs: { flat: flatQaqs, recency: recencyQaqs },
                cohort,
                meta: { hydratedCount: hydratedItems.length, unhydratedCount }
            };
        });

        return {
            version: RE_VERSION,
            computedAt: new Date(nowMs).toISOString(),
            window,
            workers,
            includeTime,
            meta: {
                hydratedCount: hydratedItems.length,
                unhydratedCount,
                totalCount: cachedItems.length,
                workerCount: workers.length,
                baselinesReady: true,
                baselinesGeneratedAt: baselines.generatedAt,
                includeTime
            }
        };
    },

    _computeCohortBlend(workerId, hydratedItems, window, nowMs, baselines, main, includeTime) {
        const output = { flat: {}, recency: {} };
        for (const weighting of ['flat', 'recency']) {
            const twSlices = { team: [], env: [], month: [] };
            const qaSlices = { team: [], env: [], month: [] };
            for (const dimension of ['team', 'env', 'month']) {
                const keyedItems = new Map();
                for (const item of hydratedItems) {
                    const key = reCohortKey(item.task, dimension);
                    if (!key) continue;
                    if (!keyedItems.has(key)) keyedItems.set(key, []);
                    keyedItems.get(key).push(item);
                }
                for (const [key, sliceItems] of keyedItems) {
                    const twResolved = reResolveRolePriors(baselines, 'twqs', dimension, key);
                    const qaResolved = reResolveRolePriors(baselines, 'qaqs', dimension, key);
                    const twCohort = reCohortPack('twqs', twResolved);
                    const qaCohort = reCohortPack('qaqs', qaResolved);
                    const twBlock = this._computeTwqs(workerId, sliceItems, weighting, window, nowMs, twCohort, includeTime, baselines);
                    const qaBlock = this._computeQaqs(workerId, sliceItems, weighting, window, nowMs, qaCohort, includeTime, baselines);
                    if (twBlock) twSlices[dimension].push({
                        key,
                        block: twBlock,
                        volume: (twBlock.display && twBlock.display.terminalTaskCount) || 0,
                        priorSource: twCohort.priorSource,
                    });
                    if (qaBlock) qaSlices[dimension].push({
                        key,
                        block: qaBlock,
                        volume: (qaBlock.display && qaBlock.display.inScopeFeedbackCount) || 0,
                        priorSource: qaCohort.priorSource,
                    });
                }
            }
            const twqs = reBlendCohortBlocks(main[weighting + 'Twqs'], twSlices, reTwqsConfidenceBadge, 'twqs', weighting, includeTime);
            const qaqs = reBlendCohortBlocks(main[weighting + 'Qaqs'], qaSlices, reQaqsConfidenceBadge, 'qaqs', weighting, includeTime);
            output[weighting] = { twqs, qaqs };
        }
        return output;
    },

    _writerItems(workerId, hydratedItems) {
        return hydratedItems.filter((item) => {
            const authorId = item.task && item.task.author && item.task.author.id;
            return reIdsEqual(authorId, workerId);
        });
    },

    // Computes WPS-aligned TWQS (six-axis, rank-workers.py formula).
    _computeTwqs(workerId, hydratedItems, weighting, window, nowMs, cohort, includeTime, baselines) {
        const writerItems = this._writerItems(workerId, hydratedItems);
        if (writerItems.length === 0) return null;

        // Outcome Quality: terminal tasks, recency-weighted quality sum
        // A = status-weighted (includes bugged); B = excludes bugged statuses entirely
        let oqKsumA = 0, oqNsumA = 0, oqTerminalCount = 0;
        let oqKsumB = 0, oqNsumB = 0;
        // Positive Feedback Rate: all human feedback, recency-weighted
        let pfKsum = 0, pfNsum = 0;
        let pfPositiveCount = 0, pfTotalCount = 0;
        // Task Rating Quality: explicitly scored feedback only (qualityRatingRaw), ordinal 0/0.5/1
        let trqKsum = 0, trqNsum = 0;
        let trqBottomW = 0, trqAverageW = 0, trqTopW = 0;
        let trqBottomCount = 0, trqAverageCount = 0, trqTopCount = 0, trqScoredCount = 0;
        // Revision Efficiency: terminal tasks with display version history; 0.5^(v-1).
        let revEffKsum = 0, revEffNsum = 0;
        let revEffSumVersionsW = 0;
        let revEffTaskCount = 0, revEffV1 = 0, revEffV2 = 0, revEffV3plus = 0;
        let revEffApprovedSubtracted = 0;
        // Closure outcome: flat-only production/discarded/dismissed path.
        let oqClosureKsum = 0, oqClosureN = 0;
        const oqClosureStatuses = { production: 0, discarded: 0, dismissed: 0 };
        // Dispute Loss Avoidance: only rejected writer disputes are adverse.
        let dwLosses = 0, dwResolved = 0, dwWins = 0;
        // Distinct in-window authored tasks (DD loss-rate denominator).
        const dwTaskIds = new Set();
        // V1 Creation Time: per-event cohort credit.
        let vtSumWM = 0, vtSumW = 0, vtSumWC = 0, vtCount = 0;

        let earliestTs = null;

        for (const item of writerItems) {
            const task = item.task;
            if (!task) continue;
            const taskCreatedAt = reTaskTimestamp(task, item);

            const tts = Date.parse(taskCreatedAt);
            if (!Number.isNaN(tts) && (earliestTs == null || tts < earliestTs)) earliestTs = tts;

            // Outcome Quality: terminal tasks only
            const terminalQuality = reTaskTerminalQuality(task, nowMs);
            const taskInScope = reEventWeight(taskCreatedAt, 'flat', nowMs, window) > 0;
            const taskStatus = String((task && task.status) || '').toLowerCase().trim();
            const taskId = String(task.id || '').trim();
            if (taskInScope && taskId) dwTaskIds.add(taskId);

            if (terminalQuality !== null && taskInScope) {
                oqTerminalCount += 1;
                const taskW = reEventWeight(taskCreatedAt, weighting, nowMs, window);
                if (taskW > 0) {
                    oqKsumA += terminalQuality * taskW;
                    oqNsumA += taskW;
                    if (taskStatus !== 'bugged') {
                        oqKsumB += terminalQuality * taskW;
                        oqNsumB += taskW;
                    }
                }

                // Revision Efficiency: display version count (omit if no history).
                const displayCount = Array.isArray(task.promptVersions) ? task.promptVersions.length : 0;
                if (displayCount > 0 && taskW > 0) {
                    let approvedWins = 0;
                    for (const dispute of item.disputes || []) {
                        if (!dispute.resolutionAt) continue;
                        if (dispute.isApproved) approvedWins += 1;
                    }
                    const credit = reRevisionEfficiencyCredit(displayCount, approvedWins);
                    if (credit != null) {
                        revEffKsum += credit * taskW;
                        revEffNsum += taskW;
                        revEffSumVersionsW += displayCount * taskW;
                        revEffTaskCount += 1;
                        revEffApprovedSubtracted += approvedWins;
                        const effectiveV = Math.max(1, displayCount - approvedWins);
                        if (effectiveV <= 1) revEffV1 += 1;
                        else if (effectiveV === 2) revEffV2 += 1;
                        else revEffV3plus += 1;
                    }
                }
            }

            // Intentionally flat in both variants; window filtering still applies.
            const closureQuality = reTaskClosureQuality(task);
            if (closureQuality !== null && taskInScope) {
                oqClosureKsum += closureQuality;
                oqClosureN += 1;
                oqClosureStatuses[taskStatus] += 1;
            }

            // V1 Creation Time: platform-tracked problem_creation_time on version 1.
            if (taskInScope) {
                const ictSec = Number(task.initialCreationTimeSeconds);
                if (Number.isFinite(ictSec) && ictSec > 0) {
                    const timeW = reEventWeight(taskCreatedAt, weighting, nowMs, window);
                    if (timeW > 0) {
                        const minutes = ictSec / 60;
                        const resolved = reResolveTimeCutoffs(baselines, 'twqs', task);
                        const credit = reTimeTrapezoidScore(minutes, resolved.cutoffs);
                        if (credit != null) {
                            vtSumWM += minutes * timeW;
                            vtSumWC += credit * timeW;
                            vtSumW += timeW;
                            vtCount += 1;
                        }
                    }
                }
            }

            // Human feedback axes: positive rate, task rating quality
            const authorId = task.author && task.author.id;
            const allHumanFb = reHumanFeedbackChronological(task);

            for (const entry of allHumanFb) {
                const reviewerId = entry.reviewer && entry.reviewer.id;
                if (authorId && reviewerId && reIdsEqual(reviewerId, authorId)) continue;

                const fbAt = reFeedbackTimestamp(entry);
                const fw = reEventWeight(fbAt, weighting, nowMs, window);
                if (fw <= 0) continue;

                // Positive Feedback Rate
                pfNsum += fw;
                pfTotalCount += 1;
                if (entry.isPositive) {
                    pfKsum += fw;
                    pfPositiveCount += 1;
                }

                // Task Rating Quality (explicit score labels only via qualityRatingRaw)
                const rawRating = entry.display && entry.display.qualityRatingRaw;
                const ratingValue = reTaskRatingQualityValue(rawRating);
                if (ratingValue != null) {
                    trqNsum += fw;
                    trqKsum += ratingValue * fw;
                    trqScoredCount += 1;
                    if (rawRating === 'Bottom 10%') {
                        trqBottomW += fw;
                        trqBottomCount += 1;
                    } else if (rawRating === 'Average') {
                        trqAverageW += fw;
                        trqAverageCount += 1;
                    } else if (rawRating === 'Top 10%') {
                        trqTopW += fw;
                        trqTopCount += 1;
                    }
                }
            }

            // Dispute Loss Avoidance: wins are informational only.
            for (const dispute of item.disputes || []) {
                if (!dispute.resolutionAt) continue;
                if (reEventWeight(dispute.resolutionAt, 'flat', nowMs, window) <= 0) continue;
                dwResolved += 1;
                if (dispute.isRejected) dwLosses += 1;
                if (dispute.isApproved) dwWins += 1;
            }
        }

        const priors = reCohortPriors('twqs', cohort);
        if (!priors) return null;
        const oqScoreA = reShrunkRate(oqKsumA, oqNsumA, RE_TWQS_C.outcomeQuality, priors.outcomeQuality);
        const oqScoreB = oqNsumB > 0
            ? reShrunkRate(oqKsumB, oqNsumB, RE_TWQS_C.outcomeQuality, priors.outcomeQuality)
            : null;
        const oqCurrentScore = oqScoreB != null
            ? (0.5 * oqScoreA + 0.5 * oqScoreB)
            : oqScoreA;
        const oqClosureScore = oqClosureN > 0
            ? reShrunkRate(oqClosureKsum, oqClosureN, RE_TWQS_C.outcomeQuality, priors.outcomeQuality)
            : null;
        const oqScore = oqClosureScore != null
            ? (0.5 * oqCurrentScore + 0.5 * oqClosureScore)
            : oqCurrentScore;
        const pfScore = reShrunkRate(pfKsum, pfNsum, RE_TWQS_C.positiveFeedbackRate, priors.positiveFeedbackRate);
        const trqScore = reShrunkRate(trqKsum, trqNsum, RE_TWQS_C.taskRatingQuality, priors.taskRatingQuality);
        const revEffDefined = revEffNsum > 0;
        const revEffRawCredit = revEffDefined ? (revEffKsum / revEffNsum) : null;
        const revEffAvgVersions = revEffDefined ? (revEffSumVersionsW / revEffNsum) : null;
        const revEffScore = revEffDefined
            ? reShrunkRate(revEffKsum, revEffNsum, RE_TWQS_C.revisionEfficiency, priors.revisionEfficiency)
            : null;
        const dwTasksAuthored = dwTaskIds.size;
        const dwLossRate = dwLosses / (dwTasksAuthored + RE_DISPUTE_LOSS_RATE_C);
        const dwScore = reDisputeLossRateScore(
            dwLosses, dwTasksAuthored, RE_DISPUTE_LOSS_RATE_C, RE_DISPUTE_LOSS_RATE_R0
        );
        const vtDefined = vtSumW > 0;
        const vtRawMean = vtDefined ? (vtSumWM / vtSumW) : null;
        const vtRawCredit = vtDefined ? (vtSumWC / vtSumW) : null;
        const vtAnchor = reGlobalTimeAnchorCredit(baselines, 'twqs');
        const vtScore = vtDefined
            ? reShrunkCredit(vtSumWC, vtSumW, RE_TIME_SHRINK_C, vtAnchor)
            : null;
        const vtGlobalCut = reResolveTimeCutoffs(baselines, 'twqs', null).cutoffs;

        const axes = RE_TWQS_AXES.map((def) => {
            let score = null;
            let defined = true;
            let excluded = false;
            let raw = {};
            switch (def.id) {
                case 'outcomeQuality':
                    score = oqScore;
                    raw = {
                        terminalTaskCount: oqTerminalCount,
                        weightedQualitySum: Math.round(oqKsumA * 1000) / 1000,
                        weightedN: Math.round(oqNsumA * 1000) / 1000,
                        statusWeightedScore: Math.round(oqScoreA * 1000) / 1000,
                        ignoreBuggedScore: oqScoreB != null ? Math.round(oqScoreB * 1000) / 1000 : null,
                        ignoreBuggedWeightedN: Math.round(oqNsumB * 1000) / 1000,
                        currentScore: Math.round(oqCurrentScore * 1000) / 1000,
                        closureScore: oqClosureScore != null ? Math.round(oqClosureScore * 1000) / 1000 : null,
                        closureN: oqClosureN,
                        closureStatusCounts: oqClosureStatuses,
                        blend: oqClosureScore != null
                            ? '0.5*currentOutcome + 0.5*closureOutcome'
                            : 'currentOutcome (no closure outcomes)',
                        observedCounts: {
                            terminalTasks: oqTerminalCount,
                            closureOutcomes: oqClosureN,
                            closureStatusCounts: oqClosureStatuses,
                        },
                    };
                    break;
                case 'positiveFeedbackRate':
                    score = pfScore;
                    raw = {
                        weightedPositive: Math.round(pfKsum * 1000) / 1000,
                        weightedTotal: Math.round(pfNsum * 1000) / 1000,
                        observedCounts: {
                            positive: pfPositiveCount,
                            total: pfTotalCount,
                        },
                    };
                    break;
                case 'taskRatingQuality':
                    score = trqScore;
                    raw = {
                        weightedQualityPoints: Math.round(trqKsum * 1000) / 1000,
                        weightedScored: Math.round(trqNsum * 1000) / 1000,
                        weightedBottom: Math.round(trqBottomW * 1000) / 1000,
                        weightedAverage: Math.round(trqAverageW * 1000) / 1000,
                        weightedTop: Math.round(trqTopW * 1000) / 1000,
                        // Aliases used by the stats-pane breakdown helper.
                        qualityPoints: Math.round(trqKsum * 1000) / 1000,
                        total: Math.round(trqNsum * 1000) / 1000,
                        observedCounts: {
                            bottom: trqBottomCount,
                            average: trqAverageCount,
                            top: trqTopCount,
                            scored: trqScoredCount,
                        },
                    };
                    break;
                case 'revisionEfficiency':
                    defined = revEffDefined;
                    score = revEffScore;
                    raw = {
                        avgVersions: revEffAvgVersions != null
                            ? Math.round(revEffAvgVersions * 100) / 100
                            : null,
                        avgCredit: revEffRawCredit != null
                            ? Math.round(revEffRawCredit * 1000) / 1000
                            : null,
                        weightedN: Math.round(revEffNsum * 1000) / 1000,
                        observedCounts: {
                            tasks: revEffTaskCount,
                            v1: revEffV1,
                            v2: revEffV2,
                            v3plus: revEffV3plus,
                            approvedDisputesSubtracted: revEffApprovedSubtracted,
                        },
                    };
                    break;
                case 'disputeLossAvoidance':
                    score = dwScore;
                    raw = {
                        losses: dwLosses,
                        wins: dwWins,
                        resolved: dwResolved,
                        tasksAuthored: dwTasksAuthored,
                        lossRate: Math.round(dwLossRate * 10000) / 10000,
                        threshold: RE_DISPUTE_LOSS_RATE_R0,
                        observedCounts: {
                            losses: dwLosses,
                            wins: dwWins,
                            resolved: dwResolved,
                            tasksAuthored: dwTasksAuthored,
                        },
                        neutralNoEvidence: dwResolved === 0,
                    };
                    break;
                case 'v1CreationTime':
                    defined = vtDefined;
                    excluded = includeTime === false;
                    score = vtScore;
                    raw = {
                        avgMinutes: vtRawMean != null ? Math.round(vtRawMean * 10) / 10 : null,
                        rawAvgMinutes: vtRawMean != null ? Math.round(vtRawMean * 10) / 10 : null,
                        avgCredit: vtRawCredit != null ? Math.round(vtRawCredit * 1000) / 1000 : null,
                        weightedN: Math.round(vtSumW * 1000) / 1000,
                        thresholdLow: vtGlobalCut.tLo,
                        thresholdHigh: vtGlobalCut.tHi,
                        thresholdMax: vtGlobalCut.tMax,
                        anchorCredit: vtAnchor,
                        shrinkC: RE_TIME_SHRINK_C,
                        cutoffSource: 'perEventEnvTeamGlobal',
                        observedCounts: {
                            timedTasks: vtCount,
                        },
                    };
                    break;
                default:
                    break;
            }
            return { id: def.id, label: def.label, baseWeight: def.weight, score, defined, excluded, raw };
        });

        const combined = reCombineAxes(axes);
        const calKey = reCalibrationKey(weighting, includeTime);
        const params = RE_PERCENTILE_PARAMS.twqs[calKey] || {};
        combined.estimatedPercentile = reEstimatePercentile(combined.score, params);
        combined.confidence = reTwqsConfidenceBadge(oqTerminalCount);
        combined.priorSource = (cohort && cohort.priorSource) || null;
        combined.includeTime = includeTime !== false;
        combined.display = {
            writerItemCount: writerItems.length,
            terminalTaskCount: oqTerminalCount,
            tenureDays: earliestTs != null
                ? Math.max(0, Math.round((nowMs - earliestTs) / RE_MS_PER_DAY))
                : null
        };
        reAnnotatePopulationTier(combined, 'twqs', weighting, includeTime);
        combined.raw = {
            oqKsum: Math.round(oqKsumA * 1000) / 1000,
            oqNsum: Math.round(oqNsumA * 1000) / 1000,
            pfKsum: Math.round(pfKsum * 1000) / 1000,
            pfNsum: Math.round(pfNsum * 1000) / 1000,
            trqKsum: Math.round(trqKsum * 1000) / 1000,
            trqNsum: Math.round(trqNsum * 1000) / 1000,
            revEffKsum: Math.round(revEffKsum * 1000) / 1000,
            revEffNsum: Math.round(revEffNsum * 1000) / 1000,
            oqClosureKsum: Math.round(oqClosureKsum * 1000) / 1000,
            oqClosureN,
            dwLosses,
            dwWins,
            dwResolved,
            vtSumWM: Math.round(vtSumWM * 1000) / 1000,
            vtSumW: Math.round(vtSumW * 1000) / 1000,
            vtCount
        };

        return combined;
    },

    // Computes QPS-aligned QAQS (six-axis, rank-qa.py formula).
    _computeQaqs(workerId, hydratedItems, weighting, window, nowMs, cohort, includeTime, baselines) {
        const feedbackRows = reCollectQaqsFeedbackRows(workerId, hydratedItems);
        if (feedbackRows.length === 0) return null;

        // Return Effectiveness: ordinary returns on shippable-path tasks → production
        let reKsum = 0, reNsum = 0;
        let reEffectiveCount = 0, reEligibleCount = 0;
        // Return Actionability: neg on production → next human row positive?
        let raKsum = 0, raNsum = 0;
        let raActionableCount = 0, raEligibleCount = 0;
        // Label Discrimination: usage rate of explicit Top/Bottom labels
        let ldKsum = 0, ldNsum = 0;
        let ldLabeledCount = 0;
        // Acceptance Scrutiny: accept rate vs threshold
        let asKsum = 0, asNsum = 0;
        let asAcceptedCount = 0;
        // Dispute Loss Avoidance: feedbackId attribution, unweighted.
        let ddLosses = 0, ddDenom = 0, ddWins = 0;
        // Distinct in-scope tasks this reviewer QA'd (DD loss-rate denominator).
        const ddTaskIds = new Set();
        // QA Time: per-event cohort credit.
        let qtSumWM = 0, qtSumW = 0, qtSumWC = 0, qtCount = 0;

        let inScopeFeedbackCount = 0;
        let earliestTs = null;

        for (const { entry, task } of feedbackRows) {
            const fbAt = reFeedbackTimestamp(entry);
            const inScope = reEventWeight(fbAt, 'flat', nowMs, window) > 0;
            if (!inScope) continue;

            inScopeFeedbackCount += 1;
            const ts = Date.parse(fbAt);
            if (!Number.isNaN(ts) && (earliestTs == null || ts < earliestTs)) earliestTs = ts;

            const fw = reEventWeight(fbAt, weighting, nowMs, window);
            const taskStatus = String((task && task.status) || '').toLowerCase().trim();
            const taskId = String((task && task.id) || '').trim();
            if (taskId) ddTaskIds.add(taskId);

            // Acceptance Scrutiny / Label Discrimination: all in-scope rows
            asNsum += fw;
            ldNsum += fw;
            if (entry.isPositive) {
                asKsum += fw;
                asAcceptedCount += 1;
            }
            const rawRating = entry.display && entry.display.qualityRatingRaw;
            if (rawRating && RE_EXPLICIT_LABEL_SET[rawRating]) {
                ldKsum += fw;
                ldLabeledCount += 1;
            }

            // QA Time: platform-tracked qa_review_duration_seconds (skip zeros).
            const reviewSec = Number(entry.display && entry.display.reviewDurationSeconds);
            if (Number.isFinite(reviewSec) && reviewSec > 0 && fw > 0) {
                const minutes = reviewSec / 60;
                const resolved = reResolveTimeCutoffs(baselines, 'qaqs', task);
                const credit = reTimeTrapezoidScore(minutes, resolved.cutoffs);
                if (credit != null) {
                    qtSumWM += minutes * fw;
                    qtSumWC += credit * fw;
                    qtSumW += fw;
                    qtCount += 1;
                }
            }

            // Return Effectiveness: ordinary returns on shippable-path statuses only
            // (escalations / Flag-as-Bug excluded; discarded/dismissed task deaths excluded).
            if (reIsOrdinaryReturn(entry) && RE_QAQS_RET_EFF_DENOM_STATUSES[taskStatus]) {
                reNsum += fw;
                reEligibleCount += 1;
                if (taskStatus === 'production') {
                    reKsum += fw;
                    reEffectiveCount += 1;
                }
            }

            // Return Actionability: neg on production → next human row positive?
            if (!entry.isPositive && taskStatus === 'production') {
                raNsum += fw;
                raEligibleCount += 1;
                const allHuman = reHumanFeedbackChronological(task);
                const idx = allHuman.findIndex((e) => reIdsEqual(e.id, entry.id));
                if (idx >= 0 && idx + 1 < allHuman.length && allHuman[idx + 1].isPositive) {
                    raKsum += fw;
                    raActionableCount += 1;
                }
            }
        }

        // Dispute Defense: attribute via dispute.feedbackId → reviewer
        // (after systemFeedbackIdRemap). Counts are unweighted.
        for (const item of hydratedItems) {
            const task = item.task;
            if (!task) continue;
            const remap = task.systemFeedbackIdRemap || {};
            const feedbackById = new Map();
            for (const entry of task.allFeedback || []) {
                if (!reIsHumanFeedback(entry)) continue;
                const fid = String(entry.id || '').trim();
                if (fid) feedbackById.set(fid, entry);
            }

            for (const dispute of item.disputes || []) {
                if (!dispute.resolutionAt) continue;
                if (reEventWeight(dispute.resolutionAt, 'flat', nowMs, window) <= 0) continue;
                const resolvedFid = reResolveFeedbackId(dispute.feedbackId, remap);
                const linked = resolvedFid ? feedbackById.get(String(resolvedFid)) : null;
                if (!linked) continue;
                const rid = linked.reviewer && linked.reviewer.id;
                if (!reIdsEqual(rid, workerId)) continue;
                ddDenom += 1;
                if (dispute.isApproved) ddLosses += 1;
                if (dispute.isRejected) ddWins += 1;
            }
        }

        // Shrunk scores.
        // returnEffectiveness / acceptanceScrutiny stay defined (prior when n=0).
        // labelDiscrimination requires a minimum sample (else omitted; weight renormalizes).
        const priors = reCohortPriors('qaqs', cohort);
        if (!priors) return null;
        const reScore = reShrunkRate(reKsum, reNsum, RE_QAQS_RET_EFF_C, priors.returnEffectiveness);
        const raDefined = raNsum > 0;
        const raScore = raDefined ? reShrunkRate(raKsum, raNsum, RE_QAQS_RET_ACT_C, priors.returnActionability) : null;
        const ldDefined = inScopeFeedbackCount >= RE_QAQS_LABEL_DISC_MIN_N;
        const ldUsageRate = ldDefined
            ? reShrunkRate(ldKsum, ldNsum, RE_QAQS_LABEL_DISC_C, priors.labelDiscrimination)
            : null;
        const ldScore = ldDefined ? reLabelDiscriminationScore(ldUsageRate) : null;
        const asAcceptRate = reShrunkRate(asKsum, asNsum, RE_QAQS_ACCEPT_SCRUTINY_C, priors.acceptanceScrutiny);
        const asScore = reAcceptanceScrutinyScore(asAcceptRate);
        const ddTasksReviewed = ddTaskIds.size;
        const ddLossRate = ddLosses / (ddTasksReviewed + RE_DISPUTE_LOSS_RATE_C);
        const ddScore = reDisputeLossRateScore(
            ddLosses, ddTasksReviewed, RE_DISPUTE_LOSS_RATE_C, RE_DISPUTE_LOSS_RATE_R0
        );
        const qtDefined = qtSumW > 0;
        const qtRawMean = qtDefined ? (qtSumWM / qtSumW) : null;
        const qtRawCredit = qtDefined ? (qtSumWC / qtSumW) : null;
        const qtAnchor = reGlobalTimeAnchorCredit(baselines, 'qaqs');
        const qtScore = qtDefined
            ? reShrunkCredit(qtSumWC, qtSumW, RE_TIME_SHRINK_C, qtAnchor)
            : null;
        const qtGlobalCut = reResolveTimeCutoffs(baselines, 'qaqs', null).cutoffs;

        const axes = RE_QAQS_AXES.map((def) => {
            let score = null;
            let defined = true;
            let excluded = false;
            let raw = {};
            switch (def.id) {
                case 'returnEffectiveness':
                    score = reScore;
                    raw = {
                        weightedResolved: Math.round(reKsum * 1000) / 1000,
                        weightedNegShippable: Math.round(reNsum * 1000) / 1000,
                        observedCounts: {
                            effective: reEffectiveCount,
                            eligible: reEligibleCount,
                        },
                    };
                    break;
                case 'returnActionability':
                    defined = raDefined;
                    score = raScore;
                    raw = {
                        weightedOneRound: Math.round(raKsum * 1000) / 1000,
                        weightedNegProduction: Math.round(raNsum * 1000) / 1000,
                        observedCounts: {
                            actionable: raActionableCount,
                            eligible: raEligibleCount,
                        },
                    };
                    break;
                case 'acceptanceScrutiny':
                    score = asScore;
                    raw = {
                        acceptRate: Math.round(asAcceptRate * 1000) / 1000,
                        threshold: RE_QAQS_ACCEPT_SCRUTINY_T,
                        thresholdLow: RE_QAQS_ACCEPT_SCRUTINY_T_LO,
                        thresholdHigh: RE_QAQS_ACCEPT_SCRUTINY_T,
                        weightedAccepted: Math.round(asKsum * 1000) / 1000,
                        weightedTotal: Math.round(asNsum * 1000) / 1000,
                        observedCounts: {
                            accepted: asAcceptedCount,
                            total: inScopeFeedbackCount,
                        },
                    };
                    break;
                case 'disputeDefense':
                    score = ddScore;
                    raw = {
                        losses: ddLosses,
                        wins: ddWins,
                        resolved: ddDenom,
                        tasksReviewed: ddTasksReviewed,
                        lossRate: Math.round(ddLossRate * 10000) / 10000,
                        threshold: RE_DISPUTE_LOSS_RATE_R0,
                        observedCounts: {
                            losses: ddLosses,
                            wins: ddWins,
                            resolved: ddDenom,
                            tasksReviewed: ddTasksReviewed,
                        },
                        neutralNoEvidence: ddDenom === 0,
                    };
                    break;
                case 'labelDiscrimination':
                    defined = ldDefined;
                    score = ldScore;
                    raw = {
                        usageRate: ldUsageRate != null ? Math.round(ldUsageRate * 1000) / 1000 : null,
                        idealRate: RE_QAQS_LABEL_DISC_IDEAL,
                        weightedLabeled: Math.round(ldKsum * 1000) / 1000,
                        weightedTotal: Math.round(ldNsum * 1000) / 1000,
                        sampleN: inScopeFeedbackCount,
                        minSampleN: RE_QAQS_LABEL_DISC_MIN_N,
                        observedCounts: {
                            labeled: ldLabeledCount,
                            total: inScopeFeedbackCount,
                            sampleN: inScopeFeedbackCount,
                        },
                    };
                    break;
                case 'qaTime':
                    defined = qtDefined;
                    excluded = includeTime === false;
                    score = qtScore;
                    raw = {
                        avgMinutes: qtRawMean != null ? Math.round(qtRawMean * 10) / 10 : null,
                        rawAvgMinutes: qtRawMean != null ? Math.round(qtRawMean * 10) / 10 : null,
                        avgCredit: qtRawCredit != null ? Math.round(qtRawCredit * 1000) / 1000 : null,
                        weightedN: Math.round(qtSumW * 1000) / 1000,
                        thresholdLow: qtGlobalCut.tLo,
                        thresholdHigh: qtGlobalCut.tHi,
                        thresholdMax: qtGlobalCut.tMax,
                        anchorCredit: qtAnchor,
                        shrinkC: RE_TIME_SHRINK_C,
                        cutoffSource: 'perEventEnvTeamGlobal',
                        observedCounts: {
                            timedReviews: qtCount,
                        },
                    };
                    break;
                default:
                    break;
            }
            return { id: def.id, label: def.label, baseWeight: def.weight, score, defined, excluded, raw };
        });

        const combined = reCombineAxes(axes);
        const calKey = reCalibrationKey(weighting, includeTime);
        const params = RE_PERCENTILE_PARAMS.qaqs[calKey] || {};
        combined.estimatedPercentile = reEstimatePercentile(combined.score, params);
        combined.confidence = reQaqsConfidenceBadge(inScopeFeedbackCount);
        combined.priorSource = (cohort && cohort.priorSource) || null;
        combined.includeTime = includeTime !== false;
        combined.display = {
            feedbackRowCount: feedbackRows.length,
            inScopeFeedbackCount,
            tenureDays: earliestTs != null
                ? Math.max(0, Math.round((nowMs - earliestTs) / RE_MS_PER_DAY))
                : null,
            negOnShippableCount: Math.round(reNsum),
            negOnProductionCount: Math.round(raNsum)
        };
        reAnnotatePopulationTier(combined, 'qaqs', weighting, includeTime);
        combined.raw = {
            reKsum: Math.round(reKsum * 1000) / 1000,
            reNsum: Math.round(reNsum * 1000) / 1000,
            raKsum: Math.round(raKsum * 1000) / 1000,
            raNsum: Math.round(raNsum * 1000) / 1000,
            asKsum: Math.round(asKsum * 1000) / 1000,
            asNsum: Math.round(asNsum * 1000) / 1000,
            ldKsum: Math.round(ldKsum * 1000) / 1000,
            ldNsum: Math.round(ldNsum * 1000) / 1000,
            ddLosses,
            ddWins,
            ddDenom,
            qtSumWM: Math.round(qtSumWM * 1000) / 1000,
            qtSumW: Math.round(qtSumW * 1000) / 1000,
            qtCount
        };

        return combined;
    },

    buildDiagnosticsReport(workerReport, context) {
        const ctx = context || {};
        const cachedItems = (ctx.cachedItems || []).filter((item) => item && item.hydrated === true);
        const workerId = workerReport.workerId;
        const window = workerReport.window || reResolveWindow(ctx.committed);
        const nowMs = Date.parse(workerReport.computedAt) || Date.now();

        const feedbackRows = reCollectQaqsFeedbackRows(workerId, cachedItems);
        let feedbackRowsBeforeDedupe = 0;
        for (const item of cachedItems) {
            const task = item.task;
            if (!task) continue;
            for (const entry of task.allFeedback || []) {
                if (!reIsHumanFeedback(entry)) continue;
                if (!reIdsEqual(entry.reviewer && entry.reviewer.id, workerId)) continue;
                feedbackRowsBeforeDedupe += 1;
            }
        }

        const returnTypeCounts = { accepted: 0, returned: 0, escalated: 0, bugged: 0, other: 0 };
        let timestampMissingCount = 0;
        let inScopeCount = 0;
        const fieldAuditSamples = [];
        const seenAuditIds = new Set();

        for (const { entry, task } of feedbackRows) {
            const ts = reFeedbackTimestamp(entry);
            if (!ts) timestampMissingCount += 1;
            if (reEventWeight(ts, 'flat', nowMs, window) > 0) inScopeCount += 1;

            if (entry.isPositive) returnTypeCounts.accepted += 1;
            else if (entry.isEscalated) returnTypeCounts.escalated += 1;
            else if (entry.isFlaggedAsBugged) returnTypeCounts.bugged += 1;
            else if (!entry.isSystemFeedback) returnTypeCounts.returned += 1;
            else returnTypeCounts.other += 1;

            const audit = reFieldAuditRow(entry, task, workerId);
            const isAnomalous = !audit.timestampResolvable;
            if (fieldAuditSamples.length < RE_DIAG_SAMPLE_ROWS || isAnomalous) {
                if (!seenAuditIds.has(audit.feedbackId)) {
                    seenAuditIds.add(audit.feedbackId);
                    fieldAuditSamples.push(audit);
                }
            }
        }

        const feedbackIds = new Set(feedbackRows.map((r) => String(r.entry.id)));
        const disputesInScope = [];

        for (const item of cachedItems) {
            const task = item.task;
            if (!task) continue;
            const remap = task.systemFeedbackIdRemap || {};
            const hasQaOnTask = (task.allFeedback || []).some((e) => {
                return reIsHumanFeedback(e) && reIdsEqual(e.reviewer && e.reviewer.id, workerId);
            });
            if (!hasQaOnTask) continue;

            for (const dispute of item.disputes || []) {
                const rawFid = String(dispute.feedbackId || '').trim();
                const resolvedFid = reResolveFeedbackId(dispute.feedbackId, remap);
                disputesInScope.push({
                    disputeId: String(dispute.id || ''),
                    feedbackId: rawFid,
                    resolvedFeedbackId: resolvedFid,
                    matchesWorkerFeedback: Boolean(resolvedFid && feedbackIds.has(resolvedFid)),
                    status: dispute.status || null,
                    resolutionAt: dispute.resolutionAt || null,
                    isRejected: Boolean(dispute.isRejected),
                    isApproved: Boolean(dispute.isApproved)
                });
            }
        }

        const recencyTwqs = workerReport.twqs && workerReport.twqs.recency;
        const recencyQaqs = workerReport.qaqs && workerReport.qaqs.recency;

        const qaqsAxisDebug = ((recencyQaqs && recencyQaqs.axes) || []).map((p) => ({
            id: p.id, label: p.label, defined: p.defined !== false,
            whyOmitted: reAxisOmitReason(p), score: p.score, raw: p.raw || {}
        }));

        const twqsAxisDebug = ((recencyTwqs && recencyTwqs.axes) || []).map((p) => ({
            id: p.id, label: p.label, defined: p.defined !== false,
            whyOmitted: reAxisOmitReason(p), score: p.score, raw: p.raw || {}
        }));

        return {
            meta: {
                engineVersion: RE_VERSION,
                computedAt: workerReport.computedAt || new Date(nowMs).toISOString(),
                workerId,
                name: workerReport.name || workerId,
                email: workerReport.email || '',
                window,
                hydratedCount: cachedItems.length,
                unhydratedCount: ctx.unhydratedCount != null
                    ? ctx.unhydratedCount
                    : Math.max(0, (ctx.cachedItems || []).length - cachedItems.length)
            },
            warnings: ctx.warnings || [],
            fieldAudit: {
                accessorNotes: {
                    feedbackTimestamp: 'Uses entry.feedbackAt with fallback to entry.created_at',
                    taskTimestamp: 'Uses task.createdAt with fallback to item.sortAt',
                    disputeFeedbackId: 'Applies task.systemFeedbackIdRemap before matching QA feedback rows'
                },
                samples: fieldAuditSamples
            },
            qaqs: {
                feedbackRowsBeforeDedupe,
                feedbackRowsDeduped: feedbackRows.length,
                inScopeCount,
                timestampMissingCount,
                returnTypeCounts,
                disputesInScope,
                axisDebug: qaqsAxisDebug
            },
            twqs: recencyTwqs ? {
                writerItemCount: this._writerItems(workerId, cachedItems).length,
                axisDebug: twqsAxisDebug
            } : null,
            scores: {
                flat: {
                    twqs: workerReport.twqs && workerReport.twqs.flat
                        ? { score: workerReport.twqs.flat.score, band: workerReport.twqs.flat.band } : null,
                    qaqs: workerReport.qaqs && workerReport.qaqs.flat
                        ? { score: workerReport.qaqs.flat.score, band: workerReport.qaqs.flat.band } : null
                },
                recency: {
                    twqs: recencyTwqs ? { score: recencyTwqs.score, band: recencyTwqs.band } : null,
                    qaqs: recencyQaqs ? { score: recencyQaqs.score, band: recencyQaqs.band } : null
                }
            }
        };
    },

    buildExportFilename(workerReport, scoreType, ext) {
        const name = reSlugify(workerReport.name || workerReport.workerId);
        const date = (workerReport.exportDate || new Date().toISOString().slice(0, 10));
        if (scoreType === 'llm-data') {
            return 'llm-data-' + reWorkerExportIdentity(workerReport) + '-'
                + reExportTimestampSlug(workerReport.exportedAt) + '.' + ext;
        }
        return 'rating-' + name + '-' + scoreType + '-' + date + '.' + ext;
    },

    buildDiagnosticsFilename(workerReport) {
        return 'diagnostic-' + reWorkerExportIdentity(workerReport) + '-'
            + reExportTimestampSlug(workerReport.exportedAt) + '.json';
    },

    serializeJson(report) {
        return JSON.stringify(reWorkerJsonExport(report), null, 2);
    },

    serializeDiagnosticsJson(report) {
        return JSON.stringify(report, null, 2);
    },

    serializeMarkdown(workerReport) {
        const lines = [];
        lines.push('# Worker Rating Report');
        lines.push('');
        lines.push('- **Worker:** ' + (workerReport.name || workerReport.workerId));
        if (workerReport.email) lines.push('- **Email:** ' + workerReport.email);
        lines.push('- **Computed:** ' + (workerReport.computedAt || new Date().toISOString()));
        const win = workerReport.window || {};
        if (win.afterLocal || win.beforeLocal) {
            lines.push('- **Window:** ' + (win.afterLocal || '…') + ' → ' + (win.beforeLocal || '…'));
        } else {
            lines.push('- **Window:** All time');
        }
        lines.push('- **Engine version:** ' + (workerReport.engineVersion || RE_VERSION));
        lines.push('');

        const renderScoreBlock = (title, block) => {
            if (!block || block.score == null) return;
            lines.push('## ' + title);
            lines.push('');
            let scoreStr = String(Math.round(block.score)) + ' / 100 · ' + block.band;
            if (block.estimatedPercentile != null) {
                scoreStr += ' · ~' + reFormatPercentile(block.estimatedPercentile) + ' percentile (estimated)';
            }
            lines.push('**Score:** ' + scoreStr);
            lines.push('**Confidence:** ' + (block.confidence && block.confidence.label));
            lines.push('');
            lines.push('| Axis | Sub-score | Weight |');
            lines.push('| --- | ---: | ---: |');
            for (const p of block.axes || []) {
                const wt = p.effectiveWeight != null
                    ? (Math.round(p.effectiveWeight * 1000) / 10) + '%'
                    : '—';
                const sc = p.defined === false ? 'omitted' : reFormatPct(p.score || 0);
                lines.push('| ' + p.label + ' | ' + sc + ' | ' + wt + ' |');
            }
            lines.push('');
        };

        for (const weighting of ['recency', 'flat']) {
            const label = weighting === 'recency' ? 'Recency-weighted (30-day half-life)' : 'Flat-weighted';
            const twqs = workerReport.twqs && workerReport.twqs[weighting];
            const qaqs = workerReport.qaqs && workerReport.qaqs[weighting];

            if (twqs || qaqs) {
                lines.push('---');
                lines.push('');
                lines.push('# ' + label);
                lines.push('');
                renderScoreBlock('Task Writer Quality Score (TWQS)', twqs);
                renderScoreBlock('QA Quality Score (QAQS)', qaqs);
            }
        }

        if (workerReport.meta) {
            lines.push('## Meta');
            lines.push('- Hydrated items used: ' + workerReport.meta.hydratedCount);
            lines.push('- Unhydrated items excluded: ' + workerReport.meta.unhydratedCount);
        }

        return lines.join('\n');
    }
};

const plugin = {
    id: 'rating-engine',
    name: 'Rating Engine',
    description: 'TWQS and QAQS computation for Worker Output Search ratings (WPS/QPS aligned)',
    _version: '16.0',
    phase: 'core',
    enabledByDefault: true,
    initialState: { registered: false },

    init(state) {
        if (state && state.registered) {
            Logger.debug('already registered — skipping re-init');
            return;
        }
        Context.ratingEngine = RatingEngine;
        if (state) state.registered = true;
        Logger.log('module registered (Context.ratingEngine) v' + RE_VERSION);
    }
};
